"""Generated from Smithy shape ``com.amazonaws.resiliencehub#ListResourceGroupingRecommendationsResponse``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_resiliencehub.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_resiliencehub.types.grouping_recommendation_list
    import aws_sdk_resiliencehub.types.next_token


class ListResourceGroupingRecommendationsResponse(TypedDict, closed=True):
    grouping_recommendations: "aws_sdk_resiliencehub.types.grouping_recommendation_list.GroupingRecommendationList"
    """<p>List of resource grouping recommendations generated by Resilience Hub.</p>"""
    next_token: NotRequired["aws_sdk_resiliencehub.types.next_token.NextToken"]
    """<p>Null, or the token from a previous call to get the next set of results.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ListResourceGroupingRecommendationsResponse) -> dict:
    out: dict = {}
    import aws_sdk_resiliencehub.types.grouping_recommendation_list

    out["groupingRecommendations"] = (
        aws_sdk_resiliencehub.types.grouping_recommendation_list.serialize_json(
            value["grouping_recommendations"]
        )
    )
    if "next_token" in value:
        out["nextToken"] = value["next_token"]
    return out


def deserialize_json(data: dict) -> ListResourceGroupingRecommendationsResponse:
    out: ListResourceGroupingRecommendationsResponse = {}  # type: ignore[typeddict-item]
    if "groupingRecommendations" in data:
        import aws_sdk_resiliencehub.types.grouping_recommendation_list

        out["grouping_recommendations"] = (
            aws_sdk_resiliencehub.types.grouping_recommendation_list.deserialize_json(
                data["groupingRecommendations"]
            )
        )
    else:
        raise DeserializationError(
            "ListResourceGroupingRecommendationsResponse.grouping_recommendations required"
        )
    if "nextToken" in data:
        out["next_token"] = data["nextToken"]
    return out
