"""Generated from Smithy shape ``com.amazonaws.bedrockruntime#GuardrailContextualGroundingFilter``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

from aws_sdk_bedrock_runtime.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_filter_type
    import aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_policy_action


class GuardrailContextualGroundingFilter(TypedDict):
    type: "aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_filter_type.GuardrailContextualGroundingFilterType"
    """<p>The contextual grounding filter type.</p>"""
    threshold: "float"
    """<p>The threshold used by contextual grounding filter to determine whether the content is grounded or not.</p>"""
    score: "float"
    """<p>The score generated by contextual grounding filter.</p>"""
    action: "aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_policy_action.GuardrailContextualGroundingPolicyAction"
    """<p>The action performed by the guardrails contextual grounding filter.</p>"""
    detected: NotRequired["bool"]
    """<p>Indicates whether content that fails the contextual grounding evaluation (grounding or relevance score less than the corresponding threshold) was detected.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: GuardrailContextualGroundingFilter) -> dict:
    out: dict = {}
    import aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_filter_type

    out["type"] = (
        aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_filter_type.serialize_json(
            value["type"]
        )
    )
    out["threshold"] = value["threshold"]
    out["score"] = value["score"]
    import aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_policy_action

    out["action"] = (
        aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_policy_action.serialize_json(
            value["action"]
        )
    )
    if "detected" in value:
        out["detected"] = value["detected"]
    return out


def deserialize_json(data: dict) -> GuardrailContextualGroundingFilter:
    out: GuardrailContextualGroundingFilter = {}  # type: ignore[typeddict-item]
    if "type" in data:
        import aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_filter_type

        out["type"] = (
            aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_filter_type.deserialize_json(
                data["type"]
            )
        )
    else:
        raise DeserializationError("GuardrailContextualGroundingFilter.type required")
    if "threshold" in data:
        out["threshold"] = data["threshold"]
    else:
        raise DeserializationError(
            "GuardrailContextualGroundingFilter.threshold required"
        )
    if "score" in data:
        out["score"] = data["score"]
    else:
        raise DeserializationError("GuardrailContextualGroundingFilter.score required")
    if "action" in data:
        import aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_policy_action

        out["action"] = (
            aws_sdk_bedrock_runtime.types.guardrail_contextual_grounding_policy_action.deserialize_json(
                data["action"]
            )
        )
    else:
        raise DeserializationError("GuardrailContextualGroundingFilter.action required")
    if "detected" in data:
        out["detected"] = data["detected"]
    return out
