"""Generated from Smithy shape ``com.amazonaws.workspacesweb#UpdateNetworkSettingsRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_workspaces_web.types.arn
    import capo_workspaces_web.types.client_token
    import capo_workspaces_web.types.security_group_id_list
    import capo_workspaces_web.types.subnet_id_list
    import capo_workspaces_web.types.vpc_id


class UpdateNetworkSettingsRequest(TypedDict, closed=True):
    network_settings_arn: "capo_workspaces_web.types.arn.ARN"
    """<p>The ARN of the network settings.</p>"""
    vpc_id: NotRequired["capo_workspaces_web.types.vpc_id.VpcId"]
    """<p>The VPC that streaming instances will connect to.</p>"""
    subnet_ids: NotRequired["capo_workspaces_web.types.subnet_id_list.SubnetIdList"]
    """<p>The subnets in which network interfaces are created to connect streaming instances to your VPC. At least two of these subnets must be in different availability zones.</p>"""
    security_group_ids: NotRequired[
        "capo_workspaces_web.types.security_group_id_list.SecurityGroupIdList"
    ]
    """<p>One or more security groups used to control access from streaming instances to your VPC.</p>"""
    client_token: NotRequired["capo_workspaces_web.types.client_token.ClientToken"]
    """<p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: UpdateNetworkSettingsRequest) -> dict:
    out: dict = {}
    if "vpc_id" in value:
        out["vpcId"] = value["vpc_id"]
    if "subnet_ids" in value:
        import capo_workspaces_web.types.subnet_id_list

        out["subnetIds"] = capo_workspaces_web.types.subnet_id_list.serialize_json(
            value["subnet_ids"]
        )
    if "security_group_ids" in value:
        import capo_workspaces_web.types.security_group_id_list

        out["securityGroupIds"] = (
            capo_workspaces_web.types.security_group_id_list.serialize_json(
                value["security_group_ids"]
            )
        )
    if "client_token" in value:
        out["clientToken"] = value["client_token"]
    return out


def deserialize_json(data: dict) -> UpdateNetworkSettingsRequest:
    out: UpdateNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
    if "vpcId" in data:
        out["vpc_id"] = data["vpcId"]
    if "subnetIds" in data:
        import capo_workspaces_web.types.subnet_id_list

        out["subnet_ids"] = capo_workspaces_web.types.subnet_id_list.deserialize_json(
            data["subnetIds"]
        )
    if "securityGroupIds" in data:
        import capo_workspaces_web.types.security_group_id_list

        out["security_group_ids"] = (
            capo_workspaces_web.types.security_group_id_list.deserialize_json(
                data["securityGroupIds"]
            )
        )
    if "clientToken" in data:
        out["client_token"] = data["clientToken"]
    return out
