"""Generated from Smithy shape ``com.amazonaws.athena#ListPreparedStatementsInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_athena.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_athena.types.max_prepared_statements_count
    import aws_sdk_athena.types.token
    import aws_sdk_athena.types.work_group_name


class ListPreparedStatementsInput(TypedDict, closed=True):
    work_group: "aws_sdk_athena.types.work_group_name.WorkGroupName"
    """<p>The workgroup to list the prepared statements for.</p>"""
    next_token: NotRequired["aws_sdk_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the <code>NextToken</code> from the response object of the previous page call.</p>"""
    max_results: NotRequired[
        "aws_sdk_athena.types.max_prepared_statements_count.MaxPreparedStatementsCount"
    ]
    """<p>The maximum number of results to return in this request.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListPreparedStatementsInput) -> dict:
    out: dict = {}
    out["WorkGroup"] = value["work_group"]
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    if "max_results" in value:
        out["MaxResults"] = value["max_results"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListPreparedStatementsInput:
    out: ListPreparedStatementsInput = {}  # type: ignore[typeddict-item]
    if "WorkGroup" in data:
        out["work_group"] = data["WorkGroup"]
    else:
        raise DeserializationError("ListPreparedStatementsInput.work_group required")
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    if "MaxResults" in data:
        out["max_results"] = data["MaxResults"]
    return out
