"""Generated from Smithy shape ``com.amazonaws.athena#ListEngineVersionsOutput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import aws_sdk_athena.types.engine_versions_list
    import aws_sdk_athena.types.token


class ListEngineVersionsOutput(TypedDict, closed=True):
    engine_versions: NotRequired[
        "aws_sdk_athena.types.engine_versions_list.EngineVersionsList"
    ]
    """<p>A list of engine versions that are available to choose from.</p>"""
    next_token: NotRequired["aws_sdk_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the <code>NextToken</code> from the response object of the previous page call.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListEngineVersionsOutput) -> dict:
    out: dict = {}
    if "engine_versions" in value:
        import aws_sdk_athena.types.engine_versions_list

        out["EngineVersions"] = (
            aws_sdk_athena.types.engine_versions_list.serialize_aws_json_1_1(
                value["engine_versions"]
            )
        )
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListEngineVersionsOutput:
    out: ListEngineVersionsOutput = {}  # type: ignore[typeddict-item]
    if "EngineVersions" in data:
        import aws_sdk_athena.types.engine_versions_list

        out["engine_versions"] = (
            aws_sdk_athena.types.engine_versions_list.deserialize_aws_json_1_1(
                data["EngineVersions"]
            )
        )
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    return out
