"""Generated from Smithy shape ``com.amazonaws.athena#ListCapacityReservationsOutput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_athena.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_athena.types.capacity_reservations_list
    import aws_sdk_athena.types.token


class ListCapacityReservationsOutput(TypedDict, closed=True):
    next_token: NotRequired["aws_sdk_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call.</p>"""
    capacity_reservations: (
        "aws_sdk_athena.types.capacity_reservations_list.CapacityReservationsList"
    )
    """<p>The capacity reservations for the current account.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListCapacityReservationsOutput) -> dict:
    out: dict = {}
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    import aws_sdk_athena.types.capacity_reservations_list

    out["CapacityReservations"] = (
        aws_sdk_athena.types.capacity_reservations_list.serialize_aws_json_1_1(
            value["capacity_reservations"]
        )
    )
    return out


def deserialize_aws_json_1_1(data: dict) -> ListCapacityReservationsOutput:
    out: ListCapacityReservationsOutput = {}  # type: ignore[typeddict-item]
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    if "CapacityReservations" in data:
        import aws_sdk_athena.types.capacity_reservations_list

        out["capacity_reservations"] = (
            aws_sdk_athena.types.capacity_reservations_list.deserialize_aws_json_1_1(
                data["CapacityReservations"]
            )
        )
    else:
        raise DeserializationError(
            "ListCapacityReservationsOutput.capacity_reservations required"
        )
    return out
