"""Generated from Smithy shape ``com.amazonaws.athena#ListExecutorsRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_athena.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_athena.types.executor_state
    import aws_sdk_athena.types.max_list_executors_count
    import aws_sdk_athena.types.session_id
    import aws_sdk_athena.types.session_manager_token


class ListExecutorsRequest(TypedDict, closed=True):
    session_id: "aws_sdk_athena.types.session_id.SessionId"
    """<p>The session ID.</p>"""
    executor_state_filter: NotRequired[
        "aws_sdk_athena.types.executor_state.ExecutorState"
    ]
    """<p>A filter for a specific executor state. A description of each state follows.</p> <p> <code>CREATING</code> - The executor is being started, including acquiring resources.</p> <p> <code>CREATED</code> - The executor has been started.</p> <p> <code>REGISTERED</code> - The executor has been registered.</p> <p> <code>TERMINATING</code> - The executor is in the process of shutting down.</p> <p> <code>TERMINATED</code> - The executor is no longer running.</p> <p> <code>FAILED</code> - Due to a failure, the executor is no longer running.</p>"""
    max_results: NotRequired[
        "aws_sdk_athena.types.max_list_executors_count.MaxListExecutorsCount"
    ]
    """<p>The maximum number of executors to return.</p>"""
    next_token: NotRequired[
        "aws_sdk_athena.types.session_manager_token.SessionManagerToken"
    ]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the <code>NextToken</code> from the response object of the previous page call.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListExecutorsRequest) -> dict:
    out: dict = {}
    out["SessionId"] = value["session_id"]
    if "executor_state_filter" in value:
        import aws_sdk_athena.types.executor_state

        out["ExecutorStateFilter"] = (
            aws_sdk_athena.types.executor_state.serialize_aws_json_1_1(
                value["executor_state_filter"]
            )
        )
    if "max_results" in value:
        out["MaxResults"] = value["max_results"]
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListExecutorsRequest:
    out: ListExecutorsRequest = {}  # type: ignore[typeddict-item]
    if "SessionId" in data:
        out["session_id"] = data["SessionId"]
    else:
        raise DeserializationError("ListExecutorsRequest.session_id required")
    if "ExecutorStateFilter" in data:
        import aws_sdk_athena.types.executor_state

        out["executor_state_filter"] = (
            aws_sdk_athena.types.executor_state.deserialize_aws_json_1_1(
                data["ExecutorStateFilter"]
            )
        )
    if "MaxResults" in data:
        out["max_results"] = data["MaxResults"]
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    return out
