"""Generated from Smithy shape ``com.amazonaws.athena#ListTableMetadataInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_athena.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_athena.types.catalog_name_string
    import aws_sdk_athena.types.expression_string
    import aws_sdk_athena.types.max_table_metadata_count
    import aws_sdk_athena.types.name_string
    import aws_sdk_athena.types.token
    import aws_sdk_athena.types.work_group_name


class ListTableMetadataInput(TypedDict, closed=True):
    catalog_name: "aws_sdk_athena.types.catalog_name_string.CatalogNameString"
    """<p>The name of the data catalog for which table metadata should be returned.</p>"""
    database_name: "aws_sdk_athena.types.name_string.NameString"
    """<p>The name of the database for which table metadata should be returned.</p>"""
    expression: NotRequired["aws_sdk_athena.types.expression_string.ExpressionString"]
    """<p>A regex filter that pattern-matches table names. If no expression is supplied, metadata for all tables are listed.</p>"""
    next_token: NotRequired["aws_sdk_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken from the response object of the previous page call.</p>"""
    max_results: NotRequired[
        "aws_sdk_athena.types.max_table_metadata_count.MaxTableMetadataCount"
    ]
    """<p>Specifies the maximum number of results to return.</p>"""
    work_group: NotRequired["aws_sdk_athena.types.work_group_name.WorkGroupName"]
    """<p>The name of the workgroup for which the metadata is being fetched. Required if requesting an IAM Identity Center enabled Glue Data Catalog.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListTableMetadataInput) -> dict:
    out: dict = {}
    out["CatalogName"] = value["catalog_name"]
    out["DatabaseName"] = value["database_name"]
    if "expression" in value:
        out["Expression"] = value["expression"]
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    if "max_results" in value:
        out["MaxResults"] = value["max_results"]
    if "work_group" in value:
        out["WorkGroup"] = value["work_group"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListTableMetadataInput:
    out: ListTableMetadataInput = {}  # type: ignore[typeddict-item]
    if "CatalogName" in data:
        out["catalog_name"] = data["CatalogName"]
    else:
        raise DeserializationError("ListTableMetadataInput.catalog_name required")
    if "DatabaseName" in data:
        out["database_name"] = data["DatabaseName"]
    else:
        raise DeserializationError("ListTableMetadataInput.database_name required")
    if "Expression" in data:
        out["expression"] = data["Expression"]
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    if "MaxResults" in data:
        out["max_results"] = data["MaxResults"]
    if "WorkGroup" in data:
        out["work_group"] = data["WorkGroup"]
    return out
