"""Generated from Smithy shape ``com.amazonaws.athena#ListNotebookMetadataInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_athena.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_athena.types.filter_definition
    import aws_sdk_athena.types.max_notebooks_count
    import aws_sdk_athena.types.token
    import aws_sdk_athena.types.work_group_name


class ListNotebookMetadataInput(TypedDict, closed=True):
    filters: NotRequired["aws_sdk_athena.types.filter_definition.FilterDefinition"]
    """<p>Search filter string.</p>"""
    next_token: NotRequired["aws_sdk_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated.</p>"""
    max_results: NotRequired[
        "aws_sdk_athena.types.max_notebooks_count.MaxNotebooksCount"
    ]
    """<p>Specifies the maximum number of results to return.</p>"""
    work_group: "aws_sdk_athena.types.work_group_name.WorkGroupName"
    """<p>The name of the Spark enabled workgroup to retrieve notebook metadata for.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListNotebookMetadataInput) -> dict:
    out: dict = {}
    if "filters" in value:
        import aws_sdk_athena.types.filter_definition

        out["Filters"] = aws_sdk_athena.types.filter_definition.serialize_aws_json_1_1(
            value["filters"]
        )
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    if "max_results" in value:
        out["MaxResults"] = value["max_results"]
    out["WorkGroup"] = value["work_group"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListNotebookMetadataInput:
    out: ListNotebookMetadataInput = {}  # type: ignore[typeddict-item]
    if "Filters" in data:
        import aws_sdk_athena.types.filter_definition

        out["filters"] = (
            aws_sdk_athena.types.filter_definition.deserialize_aws_json_1_1(
                data["Filters"]
            )
        )
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    if "MaxResults" in data:
        out["max_results"] = data["MaxResults"]
    if "WorkGroup" in data:
        out["work_group"] = data["WorkGroup"]
    else:
        raise DeserializationError("ListNotebookMetadataInput.work_group required")
    return out
