"""Generated from Smithy shape ``com.amazonaws.athena#ListWorkGroupsOutput``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

if TYPE_CHECKING:
    import aws_sdk_athena.types.token
    import aws_sdk_athena.types.work_groups_list


class ListWorkGroupsOutput(TypedDict):
    work_groups: NotRequired["aws_sdk_athena.types.work_groups_list.WorkGroupsList"]
    """<p>A list of <a>WorkGroupSummary</a> objects that include the names, descriptions, creation times, and states for each workgroup.</p>"""
    next_token: NotRequired["aws_sdk_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the <code>NextToken</code> from the response object of the previous page call.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListWorkGroupsOutput) -> dict:
    out: dict = {}
    if "work_groups" in value:
        import aws_sdk_athena.types.work_groups_list

        out["WorkGroups"] = (
            aws_sdk_athena.types.work_groups_list.serialize_aws_json_1_1(
                value["work_groups"]
            )
        )
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListWorkGroupsOutput:
    out: ListWorkGroupsOutput = {}  # type: ignore[typeddict-item]
    if "WorkGroups" in data:
        import aws_sdk_athena.types.work_groups_list

        out["work_groups"] = (
            aws_sdk_athena.types.work_groups_list.deserialize_aws_json_1_1(
                data["WorkGroups"]
            )
        )
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    return out
