"""Generated from Smithy shape ``com.amazonaws.athena#ListCapacityReservationsInput``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

if TYPE_CHECKING:
    import aws_sdk_athena.types.max_capacity_reservations_count
    import aws_sdk_athena.types.token


class ListCapacityReservationsInput(TypedDict):
    next_token: NotRequired["aws_sdk_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated.</p>"""
    max_results: NotRequired[
        "aws_sdk_athena.types.max_capacity_reservations_count.MaxCapacityReservationsCount"
    ]
    """<p>Specifies the maximum number of results to return.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListCapacityReservationsInput) -> dict:
    out: dict = {}
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    if "max_results" in value:
        out["MaxResults"] = value["max_results"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListCapacityReservationsInput:
    out: ListCapacityReservationsInput = {}  # type: ignore[typeddict-item]
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    if "MaxResults" in data:
        out["max_results"] = data["MaxResults"]
    return out
