"""Generated from Smithy shape ``com.amazonaws.redshiftdata#DescribeStatementResponse``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_redshift_data.errors import DeserializationError

if TYPE_CHECKING:
    import datetime

    import aws_sdk_redshift_data.types.long
    import aws_sdk_redshift_data.types.result_format_string
    import aws_sdk_redshift_data.types.secret_arn
    import aws_sdk_redshift_data.types.sql_parameters_list
    import aws_sdk_redshift_data.types.statement_string
    import aws_sdk_redshift_data.types.status_string
    import aws_sdk_redshift_data.types.string
    import aws_sdk_redshift_data.types.sub_statement_list
    import aws_sdk_redshift_data.types.uuid
    import aws_sdk_redshift_data.types.workgroup_name_string


class DescribeStatementResponse(TypedDict, closed=True):
    id: "aws_sdk_redshift_data.types.uuid.UUID"
    """<p>The identifier of the SQL statement described. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. </p>"""
    secret_arn: NotRequired["aws_sdk_redshift_data.types.secret_arn.SecretArn"]
    """<p>The name or Amazon Resource Name (ARN) of the secret that enables access to the database. </p>"""
    db_user: NotRequired["aws_sdk_redshift_data.types.string.String"]
    """<p>The database user name. </p>"""
    database: NotRequired["aws_sdk_redshift_data.types.string.String"]
    """<p>The name of the database. </p>"""
    cluster_identifier: NotRequired["aws_sdk_redshift_data.types.string.String"]
    """<p>The cluster identifier. </p>"""
    duration: "aws_sdk_redshift_data.types.long.Long"
    """<p>The amount of time in nanoseconds that the statement ran. </p>"""
    error: NotRequired["aws_sdk_redshift_data.types.string.String"]
    """<p>The error message from the cluster if the SQL statement encountered an error while running. </p>"""
    status: NotRequired["aws_sdk_redshift_data.types.status_string.StatusString"]
    """<p>The status of the SQL statement being described. Status values are defined as follows: </p> <ul> <li> <p>ABORTED - The query run was stopped by the user. </p> </li> <li> <p>ALL - A status value that includes all query statuses. This value can be used to filter results. </p> </li> <li> <p>FAILED - The query run failed. </p> </li> <li> <p>FINISHED - The query has finished running. </p> </li> <li> <p>PICKED - The query has been chosen to be run. </p> </li> <li> <p>STARTED - The query run has started. </p> </li> <li> <p>SUBMITTED - The query was submitted, but not yet processed. </p> </li> </ul>"""
    created_at: NotRequired["datetime.datetime"]
    """<p>The date and time (UTC) when the SQL statement was submitted to run. </p>"""
    updated_at: NotRequired["datetime.datetime"]
    """<p>The date and time (UTC) that the metadata for the SQL statement was last updated. An example is the time the status last changed. </p>"""
    redshift_pid: "aws_sdk_redshift_data.types.long.Long"
    """<p>The process identifier from Amazon Redshift. </p>"""
    has_result_set: NotRequired["bool"]
    """<p>A value that indicates whether the statement has a result set. The result set can be empty. The value is true for an empty result set. The value is true if any substatement returns a result set.</p>"""
    query_string: NotRequired[
        "aws_sdk_redshift_data.types.statement_string.StatementString"
    ]
    """<p>The SQL statement text. </p>"""
    result_rows: "aws_sdk_redshift_data.types.long.Long"
    """<p>Either the number of rows returned from the SQL statement or the number of rows affected. If result size is greater than zero, the result rows can be the number of rows affected by SQL statements such as INSERT, UPDATE, DELETE, COPY, and others. A <code>-1</code> indicates the value is null.</p>"""
    result_size: "aws_sdk_redshift_data.types.long.Long"
    """<p>The size in bytes of the returned results. A <code>-1</code> indicates the value is null.</p>"""
    redshift_query_id: "aws_sdk_redshift_data.types.long.Long"
    """<p>The identifier of the query generated by Amazon Redshift. These identifiers are also available in the <code>query</code> column of the <code>STL_QUERY</code> system view. </p>"""
    query_parameters: NotRequired[
        "aws_sdk_redshift_data.types.sql_parameters_list.SqlParametersList"
    ]
    """<p>The parameters for the SQL statement.</p>"""
    sub_statements: NotRequired[
        "aws_sdk_redshift_data.types.sub_statement_list.SubStatementList"
    ]
    """<p>The SQL statements from a multiple statement run.</p>"""
    workgroup_name: NotRequired[
        "aws_sdk_redshift_data.types.workgroup_name_string.WorkgroupNameString"
    ]
    """<p>The serverless workgroup name or Amazon Resource Name (ARN).</p>"""
    result_format: NotRequired[
        "aws_sdk_redshift_data.types.result_format_string.ResultFormatString"
    ]
    """<p>The data format of the result of the SQL statement.</p>"""
    session_id: NotRequired["aws_sdk_redshift_data.types.string.String"]
    """<p>The session identifier of the query.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: DescribeStatementResponse) -> dict:
    out: dict = {}
    out["Id"] = value["id"]
    if "secret_arn" in value:
        out["SecretArn"] = value["secret_arn"]
    if "db_user" in value:
        out["DbUser"] = value["db_user"]
    if "database" in value:
        out["Database"] = value["database"]
    if "cluster_identifier" in value:
        out["ClusterIdentifier"] = value["cluster_identifier"]
    out["Duration"] = value.get("duration", 0)
    if "error" in value:
        out["Error"] = value["error"]
    if "status" in value:
        out["Status"] = value["status"]
    if "created_at" in value:
        import aws_sdk_redshift_data.types._prelude.timestamp

        out["CreatedAt"] = (
            aws_sdk_redshift_data.types._prelude.timestamp.serialize_aws_json_1_1(
                value["created_at"]
            )
        )
    if "updated_at" in value:
        import aws_sdk_redshift_data.types._prelude.timestamp

        out["UpdatedAt"] = (
            aws_sdk_redshift_data.types._prelude.timestamp.serialize_aws_json_1_1(
                value["updated_at"]
            )
        )
    out["RedshiftPid"] = value.get("redshift_pid", 0)
    if "has_result_set" in value:
        out["HasResultSet"] = value["has_result_set"]
    if "query_string" in value:
        out["QueryString"] = value["query_string"]
    out["ResultRows"] = value.get("result_rows", 0)
    out["ResultSize"] = value.get("result_size", 0)
    out["RedshiftQueryId"] = value.get("redshift_query_id", 0)
    if "query_parameters" in value:
        import aws_sdk_redshift_data.types.sql_parameters_list

        out["QueryParameters"] = (
            aws_sdk_redshift_data.types.sql_parameters_list.serialize_aws_json_1_1(
                value["query_parameters"]
            )
        )
    if "sub_statements" in value:
        import aws_sdk_redshift_data.types.sub_statement_list

        out["SubStatements"] = (
            aws_sdk_redshift_data.types.sub_statement_list.serialize_aws_json_1_1(
                value["sub_statements"]
            )
        )
    if "workgroup_name" in value:
        out["WorkgroupName"] = value["workgroup_name"]
    if "result_format" in value:
        out["ResultFormat"] = value["result_format"]
    if "session_id" in value:
        out["SessionId"] = value["session_id"]
    return out


def deserialize_aws_json_1_1(data: dict) -> DescribeStatementResponse:
    out: DescribeStatementResponse = {}  # type: ignore[typeddict-item]
    if "Id" in data:
        out["id"] = data["Id"]
    else:
        raise DeserializationError("DescribeStatementResponse.id required")
    if "SecretArn" in data:
        out["secret_arn"] = data["SecretArn"]
    if "DbUser" in data:
        out["db_user"] = data["DbUser"]
    if "Database" in data:
        out["database"] = data["Database"]
    if "ClusterIdentifier" in data:
        out["cluster_identifier"] = data["ClusterIdentifier"]
    if "Duration" in data:
        out["duration"] = data["Duration"]
    else:
        out["duration"] = 0
    if "Error" in data:
        out["error"] = data["Error"]
    if "Status" in data:
        out["status"] = data["Status"]
    if "CreatedAt" in data:
        import aws_sdk_redshift_data.types._prelude.timestamp

        out["created_at"] = (
            aws_sdk_redshift_data.types._prelude.timestamp.deserialize_aws_json_1_1(
                data["CreatedAt"]
            )
        )
    if "UpdatedAt" in data:
        import aws_sdk_redshift_data.types._prelude.timestamp

        out["updated_at"] = (
            aws_sdk_redshift_data.types._prelude.timestamp.deserialize_aws_json_1_1(
                data["UpdatedAt"]
            )
        )
    if "RedshiftPid" in data:
        out["redshift_pid"] = data["RedshiftPid"]
    else:
        out["redshift_pid"] = 0
    if "HasResultSet" in data:
        out["has_result_set"] = data["HasResultSet"]
    if "QueryString" in data:
        out["query_string"] = data["QueryString"]
    if "ResultRows" in data:
        out["result_rows"] = data["ResultRows"]
    else:
        out["result_rows"] = 0
    if "ResultSize" in data:
        out["result_size"] = data["ResultSize"]
    else:
        out["result_size"] = 0
    if "RedshiftQueryId" in data:
        out["redshift_query_id"] = data["RedshiftQueryId"]
    else:
        out["redshift_query_id"] = 0
    if "QueryParameters" in data:
        import aws_sdk_redshift_data.types.sql_parameters_list

        out["query_parameters"] = (
            aws_sdk_redshift_data.types.sql_parameters_list.deserialize_aws_json_1_1(
                data["QueryParameters"]
            )
        )
    if "SubStatements" in data:
        import aws_sdk_redshift_data.types.sub_statement_list

        out["sub_statements"] = (
            aws_sdk_redshift_data.types.sub_statement_list.deserialize_aws_json_1_1(
                data["SubStatements"]
            )
        )
    if "WorkgroupName" in data:
        out["workgroup_name"] = data["WorkgroupName"]
    if "ResultFormat" in data:
        out["result_format"] = data["ResultFormat"]
    if "SessionId" in data:
        out["session_id"] = data["SessionId"]
    return out
