"""Generated from Smithy shape ``com.amazonaws.redshiftdata#StatementData``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_redshift_data.errors import DeserializationError

if TYPE_CHECKING:
    import datetime

    import aws_sdk_redshift_data.types.result_format_string
    import aws_sdk_redshift_data.types.secret_arn
    import aws_sdk_redshift_data.types.sql_parameters_list
    import aws_sdk_redshift_data.types.statement_name_string
    import aws_sdk_redshift_data.types.statement_string
    import aws_sdk_redshift_data.types.statement_string_list
    import aws_sdk_redshift_data.types.status_string
    import aws_sdk_redshift_data.types.uuid


class StatementData(TypedDict, closed=True):
    id: "aws_sdk_redshift_data.types.uuid.UUID"
    """<p>The SQL statement identifier. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. </p>"""
    query_string: NotRequired[
        "aws_sdk_redshift_data.types.statement_string.StatementString"
    ]
    """<p>The SQL statement.</p>"""
    query_strings: NotRequired[
        "aws_sdk_redshift_data.types.statement_string_list.StatementStringList"
    ]
    """<p>One or more SQL statements. Each query string in the array corresponds to one of the queries in a batch query request.</p>"""
    secret_arn: NotRequired["aws_sdk_redshift_data.types.secret_arn.SecretArn"]
    """<p>The name or Amazon Resource Name (ARN) of the secret that enables access to the database. </p>"""
    status: NotRequired["aws_sdk_redshift_data.types.status_string.StatusString"]
    """<p>The status of the SQL statement. An example is the that the SQL statement finished. </p>"""
    statement_name: NotRequired[
        "aws_sdk_redshift_data.types.statement_name_string.StatementNameString"
    ]
    """<p>The name of the SQL statement. </p>"""
    created_at: NotRequired["datetime.datetime"]
    """<p>The date and time (UTC) the statement was created. </p>"""
    updated_at: NotRequired["datetime.datetime"]
    """<p>The date and time (UTC) that the statement metadata was last updated.</p>"""
    query_parameters: NotRequired[
        "aws_sdk_redshift_data.types.sql_parameters_list.SqlParametersList"
    ]
    """<p>The parameters used in a SQL statement.</p>"""
    is_batch_statement: NotRequired["bool"]
    """<p>A value that indicates whether the statement is a batch query request.</p>"""
    result_format: NotRequired[
        "aws_sdk_redshift_data.types.result_format_string.ResultFormatString"
    ]
    """<p>The data format of the result of the SQL statement.</p>"""
    session_id: NotRequired["aws_sdk_redshift_data.types.uuid.UUID"]
    """<p>The session identifier of the query.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: StatementData) -> dict:
    out: dict = {}
    out["Id"] = value["id"]
    if "query_string" in value:
        out["QueryString"] = value["query_string"]
    if "query_strings" in value:
        import aws_sdk_redshift_data.types.statement_string_list

        out["QueryStrings"] = (
            aws_sdk_redshift_data.types.statement_string_list.serialize_aws_json_1_1(
                value["query_strings"]
            )
        )
    if "secret_arn" in value:
        out["SecretArn"] = value["secret_arn"]
    if "status" in value:
        out["Status"] = value["status"]
    if "statement_name" in value:
        out["StatementName"] = value["statement_name"]
    if "created_at" in value:
        import aws_sdk_redshift_data.types._prelude.timestamp

        out["CreatedAt"] = (
            aws_sdk_redshift_data.types._prelude.timestamp.serialize_aws_json_1_1(
                value["created_at"]
            )
        )
    if "updated_at" in value:
        import aws_sdk_redshift_data.types._prelude.timestamp

        out["UpdatedAt"] = (
            aws_sdk_redshift_data.types._prelude.timestamp.serialize_aws_json_1_1(
                value["updated_at"]
            )
        )
    if "query_parameters" in value:
        import aws_sdk_redshift_data.types.sql_parameters_list

        out["QueryParameters"] = (
            aws_sdk_redshift_data.types.sql_parameters_list.serialize_aws_json_1_1(
                value["query_parameters"]
            )
        )
    if "is_batch_statement" in value:
        out["IsBatchStatement"] = value["is_batch_statement"]
    if "result_format" in value:
        out["ResultFormat"] = value["result_format"]
    if "session_id" in value:
        out["SessionId"] = value["session_id"]
    return out


def deserialize_aws_json_1_1(data: dict) -> StatementData:
    out: StatementData = {}  # type: ignore[typeddict-item]
    if "Id" in data:
        out["id"] = data["Id"]
    else:
        raise DeserializationError("StatementData.id required")
    if "QueryString" in data:
        out["query_string"] = data["QueryString"]
    if "QueryStrings" in data:
        import aws_sdk_redshift_data.types.statement_string_list

        out["query_strings"] = (
            aws_sdk_redshift_data.types.statement_string_list.deserialize_aws_json_1_1(
                data["QueryStrings"]
            )
        )
    if "SecretArn" in data:
        out["secret_arn"] = data["SecretArn"]
    if "Status" in data:
        out["status"] = data["Status"]
    if "StatementName" in data:
        out["statement_name"] = data["StatementName"]
    if "CreatedAt" in data:
        import aws_sdk_redshift_data.types._prelude.timestamp

        out["created_at"] = (
            aws_sdk_redshift_data.types._prelude.timestamp.deserialize_aws_json_1_1(
                data["CreatedAt"]
            )
        )
    if "UpdatedAt" in data:
        import aws_sdk_redshift_data.types._prelude.timestamp

        out["updated_at"] = (
            aws_sdk_redshift_data.types._prelude.timestamp.deserialize_aws_json_1_1(
                data["UpdatedAt"]
            )
        )
    if "QueryParameters" in data:
        import aws_sdk_redshift_data.types.sql_parameters_list

        out["query_parameters"] = (
            aws_sdk_redshift_data.types.sql_parameters_list.deserialize_aws_json_1_1(
                data["QueryParameters"]
            )
        )
    if "IsBatchStatement" in data:
        out["is_batch_statement"] = data["IsBatchStatement"]
    if "ResultFormat" in data:
        out["result_format"] = data["ResultFormat"]
    if "SessionId" in data:
        out["session_id"] = data["SessionId"]
    return out
