from __future__ import annotations

from typing import TYPE_CHECKING, Optional

import aws_sdk_workspaces_web._auth._signers
import aws_sdk_workspaces_web._auth._sigv4
from aws_sdk_workspaces_web._services._pipeline import (
    AsyncOperationRequest,
    AsyncOperationResponse,
    OperationRequest,
    OperationResponse,
    aexecute_pipeline,
    execute_pipeline,
)

if TYPE_CHECKING:
    import aws_sdk_workspaces_web.types.arn
    import aws_sdk_workspaces_web.types.browser_policy
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.create_browser_settings_request
    import aws_sdk_workspaces_web.types.create_browser_settings_response
    import aws_sdk_workspaces_web.types.delete_browser_settings_request
    import aws_sdk_workspaces_web.types.delete_browser_settings_response
    import aws_sdk_workspaces_web.types.encryption_context_map
    import aws_sdk_workspaces_web.types.get_browser_settings_request
    import aws_sdk_workspaces_web.types.get_browser_settings_response
    import aws_sdk_workspaces_web.types.key_arn
    import aws_sdk_workspaces_web.types.list_browser_settings_request
    import aws_sdk_workspaces_web.types.list_browser_settings_response
    import aws_sdk_workspaces_web.types.max_results
    import aws_sdk_workspaces_web.types.pagination_token
    import aws_sdk_workspaces_web.types.tag_list
    import aws_sdk_workspaces_web.types.update_browser_settings_request
    import aws_sdk_workspaces_web.types.update_browser_settings_response
    import aws_sdk_workspaces_web.types.web_content_filtering_policy
    from aws_sdk_workspaces_web._services.async_work_spaces_web import (
        AsyncWorkSpacesWebClient,
        AsyncWorkSpacesWebClientConfig,
    )
    from aws_sdk_workspaces_web._services.work_spaces_web import (
        WorkSpacesWebClient,
        WorkSpacesWebClientConfig,
    )


class BrowserSettingsResource:
    def __init__(self, service: WorkSpacesWebClient) -> None:
        self._service = service

    def create(
        self,
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None,
        customer_managed_key: Optional[
            "aws_sdk_workspaces_web.types.key_arn.keyArn"
        ] = None,
        additional_encryption_context: Optional[
            "aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"
        ] = None,
        browser_policy: Optional[
            "aws_sdk_workspaces_web.types.browser_policy.BrowserPolicy"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
        web_content_filtering_policy: Optional[
            "aws_sdk_workspaces_web.types.web_content_filtering_policy.WebContentFilteringPolicy"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.create_browser_settings_response.CreateBrowserSettingsResponse":
        """<p>Creates a browser settings resource that can be associated with a web portal. Once associated with a web portal, browser settings control how the browser will behave once a user starts a streaming session for the web portal. </p>

        Args:
            tags: <p>The tags to add to the browser settings resource. A tag is a key-value pair.</p>
            customer_managed_key: <p>The custom managed key of the browser settings.</p>
            additional_encryption_context: <p>Additional encryption context of the browser settings.</p>
            browser_policy: <p>A JSON string containing Chrome Enterprise policies that will be applied to all streaming sessions.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request.</p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK. </p>
            web_content_filtering_policy: <p>The policy that specifies which URLs end users are allowed to access or which URLs or domain categories they are restricted from accessing for enhanced security.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.conflict_exception.ConflictException: <p>There is a conflict.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.service_quota_exceeded_exception.ServiceQuotaExceededException: <p>The service quota has been exceeded.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.create_browser_settings_request.CreateBrowserSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.create_browser_settings_response.CreateBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_browser_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_browser_settings.create_browser_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.create_browser_settings_request.CreateBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        if tags is not None:
            input_["tags"] = tags
        if customer_managed_key is not None:
            input_["customer_managed_key"] = customer_managed_key
        if additional_encryption_context is not None:
            input_["additional_encryption_context"] = additional_encryption_context
        if browser_policy is not None:
            input_["browser_policy"] = browser_policy
        if client_token is not None:
            input_["client_token"] = client_token
        if web_content_filtering_policy is not None:
            input_["web_content_filtering_policy"] = web_content_filtering_policy

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def read(
        self,
        browser_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_browser_settings_response.GetBrowserSettingsResponse":
        """<p>Gets browser settings.</p>

        Args:
            browser_settings_arn: <p>The ARN of the browser settings.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.get_browser_settings_request.GetBrowserSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.get_browser_settings_response.GetBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_browser_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_browser_settings.get_browser_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_browser_settings_request.GetBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["browser_settings_arn"] = browser_settings_arn

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def update(
        self,
        browser_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        browser_policy: Optional[
            "aws_sdk_workspaces_web.types.browser_policy.BrowserPolicy"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
        web_content_filtering_policy: Optional[
            "aws_sdk_workspaces_web.types.web_content_filtering_policy.WebContentFilteringPolicy"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.update_browser_settings_response.UpdateBrowserSettingsResponse":
        """<p>Updates browser settings.</p>

        Args:
            browser_settings_arn: <p>The ARN of the browser settings.</p>
            browser_policy: <p>A JSON string containing Chrome Enterprise policies that will be applied to all streaming sessions. </p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
            web_content_filtering_policy: <p>The policy that specifies which URLs end users are allowed to access or which URLs or domain categories they are restricted from accessing for enhanced security.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.update_browser_settings_request.UpdateBrowserSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.update_browser_settings_response.UpdateBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_browser_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_browser_settings.update_browser_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.update_browser_settings_request.UpdateBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["browser_settings_arn"] = browser_settings_arn
        if browser_policy is not None:
            input_["browser_policy"] = browser_policy
        if client_token is not None:
            input_["client_token"] = client_token
        if web_content_filtering_policy is not None:
            input_["web_content_filtering_policy"] = web_content_filtering_policy

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def delete(
        self,
        browser_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.delete_browser_settings_response.DeleteBrowserSettingsResponse":
        """<p>Deletes browser settings.</p>

        Args:
            browser_settings_arn: <p>The ARN of the browser settings.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.conflict_exception.ConflictException: <p>There is a conflict.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.delete_browser_settings_request.DeleteBrowserSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.delete_browser_settings_response.DeleteBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_browser_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_browser_settings.delete_browser_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.delete_browser_settings_request.DeleteBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["browser_settings_arn"] = browser_settings_arn

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def list(
        self,
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_browser_settings_response.ListBrowserSettingsResponse":
        """<p>Retrieves a list of browser settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.list_browser_settings_request.ListBrowserSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.list_browser_settings_response.ListBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_browser_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_browser_settings.list_browser_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_browser_settings_request.ListBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output


class AsyncBrowserSettingsResource:
    def __init__(self, service: AsyncWorkSpacesWebClient) -> None:
        self._service = service

    async def create(
        self,
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None,
        customer_managed_key: Optional[
            "aws_sdk_workspaces_web.types.key_arn.keyArn"
        ] = None,
        additional_encryption_context: Optional[
            "aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"
        ] = None,
        browser_policy: Optional[
            "aws_sdk_workspaces_web.types.browser_policy.BrowserPolicy"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
        web_content_filtering_policy: Optional[
            "aws_sdk_workspaces_web.types.web_content_filtering_policy.WebContentFilteringPolicy"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.create_browser_settings_response.CreateBrowserSettingsResponse":
        """<p>Creates a browser settings resource that can be associated with a web portal. Once associated with a web portal, browser settings control how the browser will behave once a user starts a streaming session for the web portal. </p>

        Args:
            tags: <p>The tags to add to the browser settings resource. A tag is a key-value pair.</p>
            customer_managed_key: <p>The custom managed key of the browser settings.</p>
            additional_encryption_context: <p>Additional encryption context of the browser settings.</p>
            browser_policy: <p>A JSON string containing Chrome Enterprise policies that will be applied to all streaming sessions.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request.</p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK. </p>
            web_content_filtering_policy: <p>The policy that specifies which URLs end users are allowed to access or which URLs or domain categories they are restricted from accessing for enhanced security.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.conflict_exception.ConflictException: <p>There is a conflict.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.service_quota_exceeded_exception.ServiceQuotaExceededException: <p>The service quota has been exceeded.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.create_browser_settings_request.CreateBrowserSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.create_browser_settings_response.CreateBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_browser_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_browser_settings.async_create_browser_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.create_browser_settings_request.CreateBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        if tags is not None:
            input_["tags"] = tags
        if customer_managed_key is not None:
            input_["customer_managed_key"] = customer_managed_key
        if additional_encryption_context is not None:
            input_["additional_encryption_context"] = additional_encryption_context
        if browser_policy is not None:
            input_["browser_policy"] = browser_policy
        if client_token is not None:
            input_["client_token"] = client_token
        if web_content_filtering_policy is not None:
            input_["web_content_filtering_policy"] = web_content_filtering_policy

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def read(
        self,
        browser_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_browser_settings_response.GetBrowserSettingsResponse":
        """<p>Gets browser settings.</p>

        Args:
            browser_settings_arn: <p>The ARN of the browser settings.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.get_browser_settings_request.GetBrowserSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.get_browser_settings_response.GetBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_browser_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_browser_settings.async_get_browser_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_browser_settings_request.GetBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["browser_settings_arn"] = browser_settings_arn

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def update(
        self,
        browser_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        browser_policy: Optional[
            "aws_sdk_workspaces_web.types.browser_policy.BrowserPolicy"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
        web_content_filtering_policy: Optional[
            "aws_sdk_workspaces_web.types.web_content_filtering_policy.WebContentFilteringPolicy"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.update_browser_settings_response.UpdateBrowserSettingsResponse":
        """<p>Updates browser settings.</p>

        Args:
            browser_settings_arn: <p>The ARN of the browser settings.</p>
            browser_policy: <p>A JSON string containing Chrome Enterprise policies that will be applied to all streaming sessions. </p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
            web_content_filtering_policy: <p>The policy that specifies which URLs end users are allowed to access or which URLs or domain categories they are restricted from accessing for enhanced security.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.update_browser_settings_request.UpdateBrowserSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.update_browser_settings_response.UpdateBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_browser_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_browser_settings.async_update_browser_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.update_browser_settings_request.UpdateBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["browser_settings_arn"] = browser_settings_arn
        if browser_policy is not None:
            input_["browser_policy"] = browser_policy
        if client_token is not None:
            input_["client_token"] = client_token
        if web_content_filtering_policy is not None:
            input_["web_content_filtering_policy"] = web_content_filtering_policy

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def delete(
        self,
        browser_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.delete_browser_settings_response.DeleteBrowserSettingsResponse":
        """<p>Deletes browser settings.</p>

        Args:
            browser_settings_arn: <p>The ARN of the browser settings.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.conflict_exception.ConflictException: <p>There is a conflict.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.delete_browser_settings_request.DeleteBrowserSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.delete_browser_settings_response.DeleteBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_browser_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_browser_settings.async_delete_browser_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.delete_browser_settings_request.DeleteBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["browser_settings_arn"] = browser_settings_arn

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def list(
        self,
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_browser_settings_response.ListBrowserSettingsResponse":
        """<p>Retrieves a list of browser settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.list_browser_settings_request.ListBrowserSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.list_browser_settings_response.ListBrowserSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_browser_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_browser_settings.async_list_browser_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_browser_settings_request.ListBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output
