from typing import Optional, TYPE_CHECKING
from aws_sdk_workspaces_web._services.async_work_spaces_web import ensure_async_iterator
from aws_sdk_workspaces_web._services.work_spaces_web import ensure_sync_iterator
from aws_sdk_workspaces_web._services._pipeline import OperationRequest, OperationResponse, execute_pipeline, AsyncOperationRequest, AsyncOperationResponse, aexecute_pipeline
import aws_sdk_workspaces_web._auth._signers
import aws_sdk_workspaces_web._auth._sigv4
if TYPE_CHECKING:
    from aws_sdk_workspaces_web._services.work_spaces_web import WorkSpacesWebClient, WorkSpacesWebClientConfig
    from aws_sdk_workspaces_web._services.async_work_spaces_web import AsyncWorkSpacesWebClient, AsyncWorkSpacesWebClientConfig
    import aws_sdk_workspaces_web.types.arn
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.create_data_protection_settings_request
    import aws_sdk_workspaces_web.types.create_data_protection_settings_response
    import aws_sdk_workspaces_web.types.data_protection_settings_summary
    import aws_sdk_workspaces_web.types.delete_data_protection_settings_request
    import aws_sdk_workspaces_web.types.delete_data_protection_settings_response
    import aws_sdk_workspaces_web.types.description_safe
    import aws_sdk_workspaces_web.types.display_name_safe
    import aws_sdk_workspaces_web.types.encryption_context_map
    import aws_sdk_workspaces_web.types.get_data_protection_settings_request
    import aws_sdk_workspaces_web.types.get_data_protection_settings_response
    import aws_sdk_workspaces_web.types.inline_redaction_configuration
    import aws_sdk_workspaces_web.types.key_arn
    import aws_sdk_workspaces_web.types.list_data_protection_settings_request
    import aws_sdk_workspaces_web.types.list_data_protection_settings_response
    import aws_sdk_workspaces_web.types.max_results
    import aws_sdk_workspaces_web.types.pagination_token
    import aws_sdk_workspaces_web.types.tag_list
    import aws_sdk_workspaces_web.types.update_data_protection_settings_request
    import aws_sdk_workspaces_web.types.update_data_protection_settings_response

class DataProtectionSettingsResource:
    def __init__(self, service: WorkSpacesWebClient) -> None:
        self._service = service
    def create(self, *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, display_name: Optional["aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"] = None, description: Optional["aws_sdk_workspaces_web.types.description_safe.DescriptionSafe"] = None, tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None, customer_managed_key: Optional["aws_sdk_workspaces_web.types.key_arn.keyArn"] = None, additional_encryption_context: Optional["aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"] = None, inline_redaction_configuration: Optional["aws_sdk_workspaces_web.types.inline_redaction_configuration.InlineRedactionConfiguration"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.create_data_protection_settings_response.CreateDataProtectionSettingsResponse":
        """<p>Creates a data protection settings resource that can be associated with a web portal.</p>

        Args:
            display_name: <p>The display name of the data protection settings.</p>
            description: <p>The description of the data protection settings.</p>
            tags: <p>The tags to add to the data protection settings resource. A tag is a key-value pair.</p>
            customer_managed_key: <p>The custom managed key of the data protection settings.</p>
            additional_encryption_context: <p>Additional encryption context of the data protection settings.</p>
            inline_redaction_configuration: <p>The inline redaction configuration of the data protection settings that will be applied to all sessions.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.create_data_protection_settings_request.CreateDataProtectionSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.create_data_protection_settings_response.CreateDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_data_protection_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_data_protection_settings.create_data_protection_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.create_data_protection_settings_request.CreateDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        if display_name is not None:
            input["display_name"] = display_name
        if description is not None:
            input["description"] = description
        if tags is not None:
            input["tags"] = tags
        if customer_managed_key is not None:
            input["customer_managed_key"] = customer_managed_key
        if additional_encryption_context is not None:
            input["additional_encryption_context"] = additional_encryption_context
        if inline_redaction_configuration is not None:
            input["inline_redaction_configuration"] = inline_redaction_configuration
        if client_token is not None:
            input["client_token"] = client_token

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def read(self, data_protection_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.get_data_protection_settings_response.GetDataProtectionSettingsResponse":
        """<p>Gets the data protection settings.</p>

        Args:
            data_protection_settings_arn: <p>The ARN of the data protection settings.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.get_data_protection_settings_request.GetDataProtectionSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.get_data_protection_settings_response.GetDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_data_protection_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_data_protection_settings.get_data_protection_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.get_data_protection_settings_request.GetDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        input["data_protection_settings_arn"] = data_protection_settings_arn

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def update(self, data_protection_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, inline_redaction_configuration: Optional["aws_sdk_workspaces_web.types.inline_redaction_configuration.InlineRedactionConfiguration"] = None, display_name: Optional["aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"] = None, description: Optional["aws_sdk_workspaces_web.types.description_safe.DescriptionSafe"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.update_data_protection_settings_response.UpdateDataProtectionSettingsResponse":
        """<p>Updates data protection settings.</p>

        Args:
            data_protection_settings_arn: <p>The ARN of the data protection settings.</p>
            inline_redaction_configuration: <p>The inline redaction configuration of the data protection settings that will be applied to all sessions.</p>
            display_name: <p>The display name of the data protection settings.</p>
            description: <p>The description of the data protection settings.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.update_data_protection_settings_request.UpdateDataProtectionSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.update_data_protection_settings_response.UpdateDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_data_protection_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_data_protection_settings.update_data_protection_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.update_data_protection_settings_request.UpdateDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        input["data_protection_settings_arn"] = data_protection_settings_arn
        if inline_redaction_configuration is not None:
            input["inline_redaction_configuration"] = inline_redaction_configuration
        if display_name is not None:
            input["display_name"] = display_name
        if description is not None:
            input["description"] = description
        if client_token is not None:
            input["client_token"] = client_token

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def delete(self, data_protection_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.delete_data_protection_settings_response.DeleteDataProtectionSettingsResponse":
        """<p>Deletes data protection settings.</p>

        Args:
            data_protection_settings_arn: <p>The ARN of the data protection settings.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.delete_data_protection_settings_request.DeleteDataProtectionSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.delete_data_protection_settings_response.DeleteDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_data_protection_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_data_protection_settings.delete_data_protection_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.delete_data_protection_settings_request.DeleteDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        input["data_protection_settings_arn"] = data_protection_settings_arn

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def list(self, *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, next_token: Optional["aws_sdk_workspaces_web.types.pagination_token.PaginationToken"] = None, max_results: Optional["aws_sdk_workspaces_web.types.max_results.MaxResults"] = None) -> "aws_sdk_workspaces_web.types.list_data_protection_settings_response.ListDataProtectionSettingsResponse":
        """<p>Retrieves a list of data protection settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.list_data_protection_settings_request.ListDataProtectionSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.list_data_protection_settings_response.ListDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_data_protection_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_data_protection_settings.list_data_protection_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.list_data_protection_settings_request.ListDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input["next_token"] = next_token
        if max_results is not None:
            input["max_results"] = max_results

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output

class AsyncDataProtectionSettingsResource:
    def __init__(self, service: AsyncWorkSpacesWebClient) -> None:
        self._service = service
    async def create(self, *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, display_name: Optional["aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"] = None, description: Optional["aws_sdk_workspaces_web.types.description_safe.DescriptionSafe"] = None, tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None, customer_managed_key: Optional["aws_sdk_workspaces_web.types.key_arn.keyArn"] = None, additional_encryption_context: Optional["aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"] = None, inline_redaction_configuration: Optional["aws_sdk_workspaces_web.types.inline_redaction_configuration.InlineRedactionConfiguration"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.create_data_protection_settings_response.CreateDataProtectionSettingsResponse":
        """<p>Creates a data protection settings resource that can be associated with a web portal.</p>

        Args:
            display_name: <p>The display name of the data protection settings.</p>
            description: <p>The description of the data protection settings.</p>
            tags: <p>The tags to add to the data protection settings resource. A tag is a key-value pair.</p>
            customer_managed_key: <p>The custom managed key of the data protection settings.</p>
            additional_encryption_context: <p>Additional encryption context of the data protection settings.</p>
            inline_redaction_configuration: <p>The inline redaction configuration of the data protection settings that will be applied to all sessions.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.create_data_protection_settings_request.CreateDataProtectionSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.create_data_protection_settings_response.CreateDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_data_protection_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_data_protection_settings.async_create_data_protection_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.create_data_protection_settings_request.CreateDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        if display_name is not None:
            input["display_name"] = display_name
        if description is not None:
            input["description"] = description
        if tags is not None:
            input["tags"] = tags
        if customer_managed_key is not None:
            input["customer_managed_key"] = customer_managed_key
        if additional_encryption_context is not None:
            input["additional_encryption_context"] = additional_encryption_context
        if inline_redaction_configuration is not None:
            input["inline_redaction_configuration"] = inline_redaction_configuration
        if client_token is not None:
            input["client_token"] = client_token

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def read(self, data_protection_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.get_data_protection_settings_response.GetDataProtectionSettingsResponse":
        """<p>Gets the data protection settings.</p>

        Args:
            data_protection_settings_arn: <p>The ARN of the data protection settings.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.get_data_protection_settings_request.GetDataProtectionSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.get_data_protection_settings_response.GetDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_data_protection_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_data_protection_settings.async_get_data_protection_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.get_data_protection_settings_request.GetDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        input["data_protection_settings_arn"] = data_protection_settings_arn

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def update(self, data_protection_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, inline_redaction_configuration: Optional["aws_sdk_workspaces_web.types.inline_redaction_configuration.InlineRedactionConfiguration"] = None, display_name: Optional["aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"] = None, description: Optional["aws_sdk_workspaces_web.types.description_safe.DescriptionSafe"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.update_data_protection_settings_response.UpdateDataProtectionSettingsResponse":
        """<p>Updates data protection settings.</p>

        Args:
            data_protection_settings_arn: <p>The ARN of the data protection settings.</p>
            inline_redaction_configuration: <p>The inline redaction configuration of the data protection settings that will be applied to all sessions.</p>
            display_name: <p>The display name of the data protection settings.</p>
            description: <p>The description of the data protection settings.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.update_data_protection_settings_request.UpdateDataProtectionSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.update_data_protection_settings_response.UpdateDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_data_protection_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_data_protection_settings.async_update_data_protection_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.update_data_protection_settings_request.UpdateDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        input["data_protection_settings_arn"] = data_protection_settings_arn
        if inline_redaction_configuration is not None:
            input["inline_redaction_configuration"] = inline_redaction_configuration
        if display_name is not None:
            input["display_name"] = display_name
        if description is not None:
            input["description"] = description
        if client_token is not None:
            input["client_token"] = client_token

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def delete(self, data_protection_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.delete_data_protection_settings_response.DeleteDataProtectionSettingsResponse":
        """<p>Deletes data protection settings.</p>

        Args:
            data_protection_settings_arn: <p>The ARN of the data protection settings.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.delete_data_protection_settings_request.DeleteDataProtectionSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.delete_data_protection_settings_response.DeleteDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_data_protection_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_data_protection_settings.async_delete_data_protection_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.delete_data_protection_settings_request.DeleteDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        input["data_protection_settings_arn"] = data_protection_settings_arn

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def list(self, *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, next_token: Optional["aws_sdk_workspaces_web.types.pagination_token.PaginationToken"] = None, max_results: Optional["aws_sdk_workspaces_web.types.max_results.MaxResults"] = None) -> "aws_sdk_workspaces_web.types.list_data_protection_settings_response.ListDataProtectionSettingsResponse":
        """<p>Retrieves a list of data protection settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.list_data_protection_settings_request.ListDataProtectionSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.list_data_protection_settings_response.ListDataProtectionSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_data_protection_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_data_protection_settings.async_list_data_protection_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.list_data_protection_settings_request.ListDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input["next_token"] = next_token
        if max_results is not None:
            input["max_results"] = max_results

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output