from __future__ import annotations

from typing import TYPE_CHECKING, Optional

import aws_sdk_workspaces_web._auth._signers
import aws_sdk_workspaces_web._auth._sigv4
from aws_sdk_workspaces_web._services._pipeline import (
    AsyncOperationRequest,
    AsyncOperationResponse,
    OperationRequest,
    OperationResponse,
    aexecute_pipeline,
    execute_pipeline,
)

if TYPE_CHECKING:
    import aws_sdk_workspaces_web.types.arn
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.create_ip_access_settings_request
    import aws_sdk_workspaces_web.types.create_ip_access_settings_response
    import aws_sdk_workspaces_web.types.delete_ip_access_settings_request
    import aws_sdk_workspaces_web.types.delete_ip_access_settings_response
    import aws_sdk_workspaces_web.types.description
    import aws_sdk_workspaces_web.types.display_name
    import aws_sdk_workspaces_web.types.encryption_context_map
    import aws_sdk_workspaces_web.types.get_ip_access_settings_request
    import aws_sdk_workspaces_web.types.get_ip_access_settings_response
    import aws_sdk_workspaces_web.types.ip_rule_list
    import aws_sdk_workspaces_web.types.key_arn
    import aws_sdk_workspaces_web.types.list_ip_access_settings_request
    import aws_sdk_workspaces_web.types.list_ip_access_settings_response
    import aws_sdk_workspaces_web.types.max_results
    import aws_sdk_workspaces_web.types.pagination_token
    import aws_sdk_workspaces_web.types.tag_list
    import aws_sdk_workspaces_web.types.update_ip_access_settings_request
    import aws_sdk_workspaces_web.types.update_ip_access_settings_response
    from aws_sdk_workspaces_web._services.async_work_spaces_web import (
        AsyncWorkSpacesWebClient,
        AsyncWorkSpacesWebClientConfig,
    )
    from aws_sdk_workspaces_web._services.work_spaces_web import (
        WorkSpacesWebClient,
        WorkSpacesWebClientConfig,
    )


class IpAccessSettingsResource:
    def __init__(self, service: WorkSpacesWebClient) -> None:
        self._service = service

    def create(
        self,
        ip_rules: "aws_sdk_workspaces_web.types.ip_rule_list.IpRuleList",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        display_name: Optional[
            "aws_sdk_workspaces_web.types.display_name.DisplayName"
        ] = None,
        description: Optional[
            "aws_sdk_workspaces_web.types.description.Description"
        ] = None,
        tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None,
        customer_managed_key: Optional[
            "aws_sdk_workspaces_web.types.key_arn.keyArn"
        ] = None,
        additional_encryption_context: Optional[
            "aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.create_ip_access_settings_response.CreateIpAccessSettingsResponse":
        """<p>Creates an IP access settings resource that can be associated with a web portal.</p>

        Args:
            display_name: <p>The display name of the IP access settings.</p>
            description: <p>The description of the IP access settings.</p>
            tags: <p>The tags to add to the IP access settings resource. A tag is a key-value pair.</p>
            customer_managed_key: <p>The custom managed key of the IP access settings.</p>
            additional_encryption_context: <p>Additional encryption context of the IP access settings.</p>
            ip_rules: <p>The IP rules of the IP access settings.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.create_ip_access_settings_request.CreateIpAccessSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.create_ip_access_settings_response.CreateIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_ip_access_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_ip_access_settings.create_ip_access_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.create_ip_access_settings_request.CreateIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        if display_name is not None:
            input_["display_name"] = display_name
        if description is not None:
            input_["description"] = description
        if tags is not None:
            input_["tags"] = tags
        if customer_managed_key is not None:
            input_["customer_managed_key"] = customer_managed_key
        if additional_encryption_context is not None:
            input_["additional_encryption_context"] = additional_encryption_context
        input_["ip_rules"] = ip_rules
        if client_token is not None:
            input_["client_token"] = client_token

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def read(
        self,
        ip_access_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_ip_access_settings_response.GetIpAccessSettingsResponse":
        """<p>Gets the IP access settings.</p>

        Args:
            ip_access_settings_arn: <p>The ARN of the IP access settings.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.get_ip_access_settings_request.GetIpAccessSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.get_ip_access_settings_response.GetIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_ip_access_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_ip_access_settings.get_ip_access_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_ip_access_settings_request.GetIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["ip_access_settings_arn"] = ip_access_settings_arn

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def update(
        self,
        ip_access_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        display_name: Optional[
            "aws_sdk_workspaces_web.types.display_name.DisplayName"
        ] = None,
        description: Optional[
            "aws_sdk_workspaces_web.types.description.Description"
        ] = None,
        ip_rules: Optional[
            "aws_sdk_workspaces_web.types.ip_rule_list.IpRuleList"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.update_ip_access_settings_response.UpdateIpAccessSettingsResponse":
        """<p>Updates IP access settings.</p>

        Args:
            ip_access_settings_arn: <p>The ARN of the IP access settings.</p>
            display_name: <p>The display name of the IP access settings.</p>
            description: <p>The description of the IP access settings.</p>
            ip_rules: <p>The updated IP rules of the IP access settings.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.update_ip_access_settings_request.UpdateIpAccessSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.update_ip_access_settings_response.UpdateIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_ip_access_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_ip_access_settings.update_ip_access_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.update_ip_access_settings_request.UpdateIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["ip_access_settings_arn"] = ip_access_settings_arn
        if display_name is not None:
            input_["display_name"] = display_name
        if description is not None:
            input_["description"] = description
        if ip_rules is not None:
            input_["ip_rules"] = ip_rules
        if client_token is not None:
            input_["client_token"] = client_token

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def delete(
        self,
        ip_access_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.delete_ip_access_settings_response.DeleteIpAccessSettingsResponse":
        """<p>Deletes IP access settings.</p>

        Args:
            ip_access_settings_arn: <p>The ARN of the IP access settings.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.delete_ip_access_settings_request.DeleteIpAccessSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.delete_ip_access_settings_response.DeleteIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_ip_access_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_ip_access_settings.delete_ip_access_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.delete_ip_access_settings_request.DeleteIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["ip_access_settings_arn"] = ip_access_settings_arn

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def list(
        self,
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_ip_access_settings_response.ListIpAccessSettingsResponse":
        """<p>Retrieves a list of IP access settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.list_ip_access_settings_request.ListIpAccessSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.list_ip_access_settings_response.ListIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_ip_access_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_ip_access_settings.list_ip_access_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_ip_access_settings_request.ListIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output


class AsyncIpAccessSettingsResource:
    def __init__(self, service: AsyncWorkSpacesWebClient) -> None:
        self._service = service

    async def create(
        self,
        ip_rules: "aws_sdk_workspaces_web.types.ip_rule_list.IpRuleList",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        display_name: Optional[
            "aws_sdk_workspaces_web.types.display_name.DisplayName"
        ] = None,
        description: Optional[
            "aws_sdk_workspaces_web.types.description.Description"
        ] = None,
        tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None,
        customer_managed_key: Optional[
            "aws_sdk_workspaces_web.types.key_arn.keyArn"
        ] = None,
        additional_encryption_context: Optional[
            "aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.create_ip_access_settings_response.CreateIpAccessSettingsResponse":
        """<p>Creates an IP access settings resource that can be associated with a web portal.</p>

        Args:
            display_name: <p>The display name of the IP access settings.</p>
            description: <p>The description of the IP access settings.</p>
            tags: <p>The tags to add to the IP access settings resource. A tag is a key-value pair.</p>
            customer_managed_key: <p>The custom managed key of the IP access settings.</p>
            additional_encryption_context: <p>Additional encryption context of the IP access settings.</p>
            ip_rules: <p>The IP rules of the IP access settings.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.create_ip_access_settings_request.CreateIpAccessSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.create_ip_access_settings_response.CreateIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_ip_access_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_ip_access_settings.async_create_ip_access_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.create_ip_access_settings_request.CreateIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        if display_name is not None:
            input_["display_name"] = display_name
        if description is not None:
            input_["description"] = description
        if tags is not None:
            input_["tags"] = tags
        if customer_managed_key is not None:
            input_["customer_managed_key"] = customer_managed_key
        if additional_encryption_context is not None:
            input_["additional_encryption_context"] = additional_encryption_context
        input_["ip_rules"] = ip_rules
        if client_token is not None:
            input_["client_token"] = client_token

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def read(
        self,
        ip_access_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_ip_access_settings_response.GetIpAccessSettingsResponse":
        """<p>Gets the IP access settings.</p>

        Args:
            ip_access_settings_arn: <p>The ARN of the IP access settings.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.get_ip_access_settings_request.GetIpAccessSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.get_ip_access_settings_response.GetIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_ip_access_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_ip_access_settings.async_get_ip_access_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_ip_access_settings_request.GetIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["ip_access_settings_arn"] = ip_access_settings_arn

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def update(
        self,
        ip_access_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        display_name: Optional[
            "aws_sdk_workspaces_web.types.display_name.DisplayName"
        ] = None,
        description: Optional[
            "aws_sdk_workspaces_web.types.description.Description"
        ] = None,
        ip_rules: Optional[
            "aws_sdk_workspaces_web.types.ip_rule_list.IpRuleList"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.update_ip_access_settings_response.UpdateIpAccessSettingsResponse":
        """<p>Updates IP access settings.</p>

        Args:
            ip_access_settings_arn: <p>The ARN of the IP access settings.</p>
            display_name: <p>The display name of the IP access settings.</p>
            description: <p>The description of the IP access settings.</p>
            ip_rules: <p>The updated IP rules of the IP access settings.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.update_ip_access_settings_request.UpdateIpAccessSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.update_ip_access_settings_response.UpdateIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_ip_access_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_ip_access_settings.async_update_ip_access_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.update_ip_access_settings_request.UpdateIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["ip_access_settings_arn"] = ip_access_settings_arn
        if display_name is not None:
            input_["display_name"] = display_name
        if description is not None:
            input_["description"] = description
        if ip_rules is not None:
            input_["ip_rules"] = ip_rules
        if client_token is not None:
            input_["client_token"] = client_token

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def delete(
        self,
        ip_access_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.delete_ip_access_settings_response.DeleteIpAccessSettingsResponse":
        """<p>Deletes IP access settings.</p>

        Args:
            ip_access_settings_arn: <p>The ARN of the IP access settings.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.delete_ip_access_settings_request.DeleteIpAccessSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.delete_ip_access_settings_response.DeleteIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_ip_access_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_ip_access_settings.async_delete_ip_access_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.delete_ip_access_settings_request.DeleteIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["ip_access_settings_arn"] = ip_access_settings_arn

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def list(
        self,
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_ip_access_settings_response.ListIpAccessSettingsResponse":
        """<p>Retrieves a list of IP access settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.list_ip_access_settings_request.ListIpAccessSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.list_ip_access_settings_response.ListIpAccessSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_ip_access_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_ip_access_settings.async_list_ip_access_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_ip_access_settings_request.ListIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output
