from typing import Optional, TYPE_CHECKING
from aws_sdk_workspaces_web._services.async_work_spaces_web import ensure_async_iterator
from aws_sdk_workspaces_web._services.work_spaces_web import ensure_sync_iterator
from aws_sdk_workspaces_web._services._pipeline import OperationRequest, OperationResponse, execute_pipeline, AsyncOperationRequest, AsyncOperationResponse, aexecute_pipeline
import aws_sdk_workspaces_web._auth._signers
import aws_sdk_workspaces_web._auth._sigv4
if TYPE_CHECKING:
    from aws_sdk_workspaces_web._services.work_spaces_web import WorkSpacesWebClient, WorkSpacesWebClientConfig
    from aws_sdk_workspaces_web._services.async_work_spaces_web import AsyncWorkSpacesWebClient, AsyncWorkSpacesWebClientConfig
    import aws_sdk_workspaces_web.types.arn
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.create_network_settings_request
    import aws_sdk_workspaces_web.types.create_network_settings_response
    import aws_sdk_workspaces_web.types.delete_network_settings_request
    import aws_sdk_workspaces_web.types.delete_network_settings_response
    import aws_sdk_workspaces_web.types.get_network_settings_request
    import aws_sdk_workspaces_web.types.get_network_settings_response
    import aws_sdk_workspaces_web.types.list_network_settings_request
    import aws_sdk_workspaces_web.types.list_network_settings_response
    import aws_sdk_workspaces_web.types.max_results
    import aws_sdk_workspaces_web.types.pagination_token
    import aws_sdk_workspaces_web.types.security_group_id_list
    import aws_sdk_workspaces_web.types.subnet_id_list
    import aws_sdk_workspaces_web.types.tag_list
    import aws_sdk_workspaces_web.types.update_network_settings_request
    import aws_sdk_workspaces_web.types.update_network_settings_response
    import aws_sdk_workspaces_web.types.vpc_id

class NetworkSettingsResource:
    def __init__(self, service: WorkSpacesWebClient) -> None:
        self._service = service
    def create(self, vpc_id: "aws_sdk_workspaces_web.types.vpc_id.VpcId", subnet_ids: "aws_sdk_workspaces_web.types.subnet_id_list.SubnetIdList", security_group_ids: "aws_sdk_workspaces_web.types.security_group_id_list.SecurityGroupIdList", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.create_network_settings_response.CreateNetworkSettingsResponse":
        """<p>Creates a network settings resource that can be associated with a web portal. Once associated with a web portal, network settings define how streaming instances will connect with your specified VPC. </p>

        Args:
            vpc_id: <p>The VPC that streaming instances will connect to.</p>
            subnet_ids: <p>The subnets in which network interfaces are created to connect streaming instances to your VPC. At least two of these subnets must be in different availability zones.</p>
            security_group_ids: <p>One or more security groups used to control access from streaming instances to your VPC.</p>
            tags: <p>The tags to add to the network settings resource. A tag is a key-value pair.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.create_network_settings_request.CreateNetworkSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.create_network_settings_response.CreateNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_network_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_network_settings.create_network_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.create_network_settings_request.CreateNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        input["vpc_id"] = vpc_id
        input["subnet_ids"] = subnet_ids
        input["security_group_ids"] = security_group_ids
        if tags is not None:
            input["tags"] = tags
        if client_token is not None:
            input["client_token"] = client_token

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def read(self, network_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.get_network_settings_response.GetNetworkSettingsResponse":
        """<p>Gets the network settings.</p>

        Args:
            network_settings_arn: <p>The ARN of the network settings.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.get_network_settings_request.GetNetworkSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.get_network_settings_response.GetNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_network_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_network_settings.get_network_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.get_network_settings_request.GetNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        input["network_settings_arn"] = network_settings_arn

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def update(self, network_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, vpc_id: Optional["aws_sdk_workspaces_web.types.vpc_id.VpcId"] = None, subnet_ids: Optional["aws_sdk_workspaces_web.types.subnet_id_list.SubnetIdList"] = None, security_group_ids: Optional["aws_sdk_workspaces_web.types.security_group_id_list.SecurityGroupIdList"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.update_network_settings_response.UpdateNetworkSettingsResponse":
        """<p>Updates network settings.</p>

        Args:
            network_settings_arn: <p>The ARN of the network settings.</p>
            vpc_id: <p>The VPC that streaming instances will connect to.</p>
            subnet_ids: <p>The subnets in which network interfaces are created to connect streaming instances to your VPC. At least two of these subnets must be in different availability zones.</p>
            security_group_ids: <p>One or more security groups used to control access from streaming instances to your VPC.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.update_network_settings_request.UpdateNetworkSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.update_network_settings_response.UpdateNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_network_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_network_settings.update_network_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.update_network_settings_request.UpdateNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        input["network_settings_arn"] = network_settings_arn
        if vpc_id is not None:
            input["vpc_id"] = vpc_id
        if subnet_ids is not None:
            input["subnet_ids"] = subnet_ids
        if security_group_ids is not None:
            input["security_group_ids"] = security_group_ids
        if client_token is not None:
            input["client_token"] = client_token

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def delete(self, network_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.delete_network_settings_response.DeleteNetworkSettingsResponse":
        """<p>Deletes network settings.</p>

        Args:
            network_settings_arn: <p>The ARN of the network settings.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.delete_network_settings_request.DeleteNetworkSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.delete_network_settings_response.DeleteNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_network_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_network_settings.delete_network_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.delete_network_settings_request.DeleteNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        input["network_settings_arn"] = network_settings_arn

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def list(self, *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, next_token: Optional["aws_sdk_workspaces_web.types.pagination_token.PaginationToken"] = None, max_results: Optional["aws_sdk_workspaces_web.types.max_results.MaxResults"] = None) -> "aws_sdk_workspaces_web.types.list_network_settings_response.ListNetworkSettingsResponse":
        """<p>Retrieves a list of network settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.list_network_settings_request.ListNetworkSettingsRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.list_network_settings_response.ListNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_network_settings
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_network_settings.list_network_settings(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.list_network_settings_request.ListNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input["next_token"] = next_token
        if max_results is not None:
            input["max_results"] = max_results

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output

class AsyncNetworkSettingsResource:
    def __init__(self, service: AsyncWorkSpacesWebClient) -> None:
        self._service = service
    async def create(self, vpc_id: "aws_sdk_workspaces_web.types.vpc_id.VpcId", subnet_ids: "aws_sdk_workspaces_web.types.subnet_id_list.SubnetIdList", security_group_ids: "aws_sdk_workspaces_web.types.security_group_id_list.SecurityGroupIdList", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.create_network_settings_response.CreateNetworkSettingsResponse":
        """<p>Creates a network settings resource that can be associated with a web portal. Once associated with a web portal, network settings define how streaming instances will connect with your specified VPC. </p>

        Args:
            vpc_id: <p>The VPC that streaming instances will connect to.</p>
            subnet_ids: <p>The subnets in which network interfaces are created to connect streaming instances to your VPC. At least two of these subnets must be in different availability zones.</p>
            security_group_ids: <p>One or more security groups used to control access from streaming instances to your VPC.</p>
            tags: <p>The tags to add to the network settings resource. A tag is a key-value pair.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.create_network_settings_request.CreateNetworkSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.create_network_settings_response.CreateNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_network_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_network_settings.async_create_network_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.create_network_settings_request.CreateNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        input["vpc_id"] = vpc_id
        input["subnet_ids"] = subnet_ids
        input["security_group_ids"] = security_group_ids
        if tags is not None:
            input["tags"] = tags
        if client_token is not None:
            input["client_token"] = client_token

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def read(self, network_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.get_network_settings_response.GetNetworkSettingsResponse":
        """<p>Gets the network settings.</p>

        Args:
            network_settings_arn: <p>The ARN of the network settings.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.get_network_settings_request.GetNetworkSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.get_network_settings_response.GetNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_network_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_network_settings.async_get_network_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.get_network_settings_request.GetNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        input["network_settings_arn"] = network_settings_arn

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def update(self, network_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, vpc_id: Optional["aws_sdk_workspaces_web.types.vpc_id.VpcId"] = None, subnet_ids: Optional["aws_sdk_workspaces_web.types.subnet_id_list.SubnetIdList"] = None, security_group_ids: Optional["aws_sdk_workspaces_web.types.security_group_id_list.SecurityGroupIdList"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.update_network_settings_response.UpdateNetworkSettingsResponse":
        """<p>Updates network settings.</p>

        Args:
            network_settings_arn: <p>The ARN of the network settings.</p>
            vpc_id: <p>The VPC that streaming instances will connect to.</p>
            subnet_ids: <p>The subnets in which network interfaces are created to connect streaming instances to your VPC. At least two of these subnets must be in different availability zones.</p>
            security_group_ids: <p>One or more security groups used to control access from streaming instances to your VPC.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.update_network_settings_request.UpdateNetworkSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.update_network_settings_response.UpdateNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_network_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_network_settings.async_update_network_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.update_network_settings_request.UpdateNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        input["network_settings_arn"] = network_settings_arn
        if vpc_id is not None:
            input["vpc_id"] = vpc_id
        if subnet_ids is not None:
            input["subnet_ids"] = subnet_ids
        if security_group_ids is not None:
            input["security_group_ids"] = security_group_ids
        if client_token is not None:
            input["client_token"] = client_token

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def delete(self, network_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.delete_network_settings_response.DeleteNetworkSettingsResponse":
        """<p>Deletes network settings.</p>

        Args:
            network_settings_arn: <p>The ARN of the network settings.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.delete_network_settings_request.DeleteNetworkSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.delete_network_settings_response.DeleteNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_network_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_network_settings.async_delete_network_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.delete_network_settings_request.DeleteNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        input["network_settings_arn"] = network_settings_arn

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def list(self, *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, next_token: Optional["aws_sdk_workspaces_web.types.pagination_token.PaginationToken"] = None, max_results: Optional["aws_sdk_workspaces_web.types.max_results.MaxResults"] = None) -> "aws_sdk_workspaces_web.types.list_network_settings_response.ListNetworkSettingsResponse":
        """<p>Retrieves a list of network settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.list_network_settings_request.ListNetworkSettingsRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.list_network_settings_response.ListNetworkSettingsResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_network_settings
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_network_settings.async_list_network_settings(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.list_network_settings_request.ListNetworkSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input["next_token"] = next_token
        if max_results is not None:
            input["max_results"] = max_results

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output