from typing import Optional, TYPE_CHECKING
from aws_sdk_workspaces_web._services.async_work_spaces_web import ensure_async_iterator
from aws_sdk_workspaces_web._services.work_spaces_web import ensure_sync_iterator
from aws_sdk_workspaces_web._services._pipeline import OperationRequest, OperationResponse, execute_pipeline, AsyncOperationRequest, AsyncOperationResponse, aexecute_pipeline
import aws_sdk_workspaces_web._auth._signers
import aws_sdk_workspaces_web._auth._sigv4
if TYPE_CHECKING:
    from aws_sdk_workspaces_web._services.work_spaces_web import WorkSpacesWebClient, WorkSpacesWebClientConfig
    from aws_sdk_workspaces_web._services.async_work_spaces_web import AsyncWorkSpacesWebClient, AsyncWorkSpacesWebClientConfig
    import aws_sdk_workspaces_web.types.arn
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.create_session_logger_request
    import aws_sdk_workspaces_web.types.create_session_logger_response
    import aws_sdk_workspaces_web.types.delete_session_logger_request
    import aws_sdk_workspaces_web.types.delete_session_logger_response
    import aws_sdk_workspaces_web.types.display_name_safe
    import aws_sdk_workspaces_web.types.encryption_context_map
    import aws_sdk_workspaces_web.types.event_filter
    import aws_sdk_workspaces_web.types.get_session_logger_request
    import aws_sdk_workspaces_web.types.get_session_logger_response
    import aws_sdk_workspaces_web.types.key_arn
    import aws_sdk_workspaces_web.types.list_session_loggers_request
    import aws_sdk_workspaces_web.types.list_session_loggers_response
    import aws_sdk_workspaces_web.types.log_configuration
    import aws_sdk_workspaces_web.types.max_results
    import aws_sdk_workspaces_web.types.pagination_token
    import aws_sdk_workspaces_web.types.session_logger_summary
    import aws_sdk_workspaces_web.types.tag_list
    import aws_sdk_workspaces_web.types.update_session_logger_request
    import aws_sdk_workspaces_web.types.update_session_logger_response

class SessionLoggerResource:
    def __init__(self, service: WorkSpacesWebClient) -> None:
        self._service = service
    def create(self, event_filter: "aws_sdk_workspaces_web.types.event_filter.EventFilter", log_configuration: "aws_sdk_workspaces_web.types.log_configuration.LogConfiguration", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, display_name: Optional["aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"] = None, customer_managed_key: Optional["aws_sdk_workspaces_web.types.key_arn.keyArn"] = None, additional_encryption_context: Optional["aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"] = None, tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.create_session_logger_response.CreateSessionLoggerResponse":
        """<p>Creates a session logger.</p>

        Args:
            event_filter: <p>The filter that specifies the events to monitor.</p>
            log_configuration: <p>The configuration that specifies where logs are delivered.</p>
            display_name: <p>The human-readable display name for the session logger resource.</p>
            customer_managed_key: <p>The custom managed key of the session logger.</p>
            additional_encryption_context: <p>The additional encryption context of the session logger.</p>
            tags: <p>The tags to add to the session logger.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. If you do not specify a client token, one is automatically generated by the AWS SDK.</p>

        Examples:
            Create Session Logger with All Events
            Creates a session logger that captures all events and stores them in S3 with JSON format and flat folder structure

            >>> client.create(event_filter={'all': {}}, log_configuration={'s3': {'bucket': 'my-session-logs-bucket', 'keyPrefix': 'session-logs/all/events', 'bucketOwner': '123456789012', 'logFileFormat': 'Json', 'folderStructure': 'Flat'}}, display_name='Session Logger with All Events')
            Create Session Logger with Specific Events
            Creates a session logger that captures only specific events with JSONLines format and nested folder structure

            >>> client.create(event_filter={'include': ['SessionStart', 'SessionEnd', 'UrlLoad', 'WebsiteInteract']}, log_configuration={'s3': {'bucket': 'my-session-logs-bucket', 'keyPrefix': 'session-logs/each/event', 'bucketOwner': '123456789012', 'logFileFormat': 'JSONLines', 'folderStructure': 'NestedByDate'}}, display_name='Session Logger with Each Events', customer_managed_key='arn:aws:kms:us-west-2:123456789012:key/12345678-1234-1234-1234-123456789012', additional_encryption_context={'EncryptionContextKey': 'EncryptionContextValue'}, tags=[{'Key': 'KEY-1', 'Value': 'VALUE-1'}, {'Key': 'KEY-2', 'Value': 'VALUE-2'}])
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.create_session_logger_request.CreateSessionLoggerRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.create_session_logger_response.CreateSessionLoggerResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_session_logger
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_session_logger.create_session_logger(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.create_session_logger_request.CreateSessionLoggerRequest = {}  # type: ignore[typeddict-item]
        input["event_filter"] = event_filter
        input["log_configuration"] = log_configuration
        if display_name is not None:
            input["display_name"] = display_name
        if customer_managed_key is not None:
            input["customer_managed_key"] = customer_managed_key
        if additional_encryption_context is not None:
            input["additional_encryption_context"] = additional_encryption_context
        if tags is not None:
            input["tags"] = tags
        if client_token is not None:
            input["client_token"] = client_token

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def read(self, session_logger_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.get_session_logger_response.GetSessionLoggerResponse":
        """<p>Gets details about a specific session logger resource.</p>

        Args:
            session_logger_arn: <p>The ARN of the session logger.</p>

        Examples:
            Get Session Logger with All Events
            Retrieves a session logger configured for all events

            >>> client.read(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/12345678-1234-1234-1234-123456789012')
            Get Session Logger with Specific Events
            Retrieves a session logger configured for specific events

            >>> client.read(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/87654321-4321-4321-4321-210987654321')
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.get_session_logger_request.GetSessionLoggerRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.get_session_logger_response.GetSessionLoggerResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_session_logger
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_session_logger.get_session_logger(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.get_session_logger_request.GetSessionLoggerRequest = {}  # type: ignore[typeddict-item]
        input["session_logger_arn"] = session_logger_arn

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def update(self, session_logger_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, event_filter: Optional["aws_sdk_workspaces_web.types.event_filter.EventFilter"] = None, log_configuration: Optional["aws_sdk_workspaces_web.types.log_configuration.LogConfiguration"] = None, display_name: Optional["aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"] = None) -> "aws_sdk_workspaces_web.types.update_session_logger_response.UpdateSessionLoggerResponse":
        """<p>Updates the details of a session logger.</p>

        Args:
            session_logger_arn: <p>The ARN of the session logger to update.</p>
            event_filter: <p>The updated eventFilter.</p>
            log_configuration: <p>The updated logConfiguration.</p>
            display_name: <p>The updated display name.</p>

        Examples:
            Update Session Logger Event Filter
            Updates a session logger to capture specific events instead of all events

            >>> client.update(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/12345678-1234-1234-1234-123456789012', event_filter={'include': ['SessionStart', 'SessionEnd', 'UrlLoad', 'WebsiteInteract']})
            Update Session Logger Configuration
            Updates the log configuration of a session logger

            >>> client.update(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/87654321-4321-4321-4321-210987654321', log_configuration={'s3': {'bucket': 'updated-my-session-logs-bucket-2', 'keyPrefix': 'updated/key/prefix', 'bucketOwner': '123456789012', 'logFileFormat': 'Json', 'folderStructure': 'Flat'}})
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.update_session_logger_request.UpdateSessionLoggerRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.update_session_logger_response.UpdateSessionLoggerResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_session_logger
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_session_logger.update_session_logger(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.update_session_logger_request.UpdateSessionLoggerRequest = {}  # type: ignore[typeddict-item]
        input["session_logger_arn"] = session_logger_arn
        if event_filter is not None:
            input["event_filter"] = event_filter
        if log_configuration is not None:
            input["log_configuration"] = log_configuration
        if display_name is not None:
            input["display_name"] = display_name

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def delete(self, session_logger_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[WorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.delete_session_logger_response.DeleteSessionLoggerResponse":
        """<p>Deletes a session logger resource.</p>

        Args:
            session_logger_arn: <p>The ARN of the session logger.</p>

        Examples:
            Delete Session Logger
            Deletes a session logger resource

            >>> client.delete(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/12345678-1234-1234-1234-123456789012')
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.delete_session_logger_request.DeleteSessionLoggerRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.delete_session_logger_response.DeleteSessionLoggerResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_session_logger
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_session_logger.delete_session_logger(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.delete_session_logger_request.DeleteSessionLoggerRequest = {}  # type: ignore[typeddict-item]
        input["session_logger_arn"] = session_logger_arn

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    def list(self, *, config_overrides: Optional[WorkSpacesWebClientConfig] = None, next_token: Optional["aws_sdk_workspaces_web.types.pagination_token.PaginationToken"] = None, max_results: Optional["aws_sdk_workspaces_web.types.max_results.MaxResults"] = None) -> "aws_sdk_workspaces_web.types.list_session_loggers_response.ListSessionLoggersResponse":
        """<p>Lists all available session logger resources.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>

        Examples:
            List All Session Loggers
            Lists all session loggers in the account without pagination

            >>> client.list()
            List Session Loggers with Pagination
            Lists session loggers with pagination parameters

            >>> client.list(max_results=1, next_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9')
        """
        def _handler(req: 'OperationRequest[aws_sdk_workspaces_web.types.list_session_loggers_request.ListSessionLoggersRequest]') -> OperationResponse["aws_sdk_workspaces_web.types.list_session_loggers_response.ListSessionLoggersResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_session_loggers
            output, http_response = aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_session_loggers.list_session_loggers(req.options, req.input)
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.list_session_loggers_request.ListSessionLoggersRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input["next_token"] = next_token
        if max_results is not None:
            input["max_results"] = max_results

        response = execute_pipeline(OperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output

class AsyncSessionLoggerResource:
    def __init__(self, service: AsyncWorkSpacesWebClient) -> None:
        self._service = service
    async def create(self, event_filter: "aws_sdk_workspaces_web.types.event_filter.EventFilter", log_configuration: "aws_sdk_workspaces_web.types.log_configuration.LogConfiguration", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, display_name: Optional["aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"] = None, customer_managed_key: Optional["aws_sdk_workspaces_web.types.key_arn.keyArn"] = None, additional_encryption_context: Optional["aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"] = None, tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None, client_token: Optional["aws_sdk_workspaces_web.types.client_token.ClientToken"] = None) -> "aws_sdk_workspaces_web.types.create_session_logger_response.CreateSessionLoggerResponse":
        """<p>Creates a session logger.</p>

        Args:
            event_filter: <p>The filter that specifies the events to monitor.</p>
            log_configuration: <p>The configuration that specifies where logs are delivered.</p>
            display_name: <p>The human-readable display name for the session logger resource.</p>
            customer_managed_key: <p>The custom managed key of the session logger.</p>
            additional_encryption_context: <p>The additional encryption context of the session logger.</p>
            tags: <p>The tags to add to the session logger.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. If you do not specify a client token, one is automatically generated by the AWS SDK.</p>

        Examples:
            Create Session Logger with All Events
            Creates a session logger that captures all events and stores them in S3 with JSON format and flat folder structure

            >>> await client.create(event_filter={'all': {}}, log_configuration={'s3': {'bucket': 'my-session-logs-bucket', 'keyPrefix': 'session-logs/all/events', 'bucketOwner': '123456789012', 'logFileFormat': 'Json', 'folderStructure': 'Flat'}}, display_name='Session Logger with All Events')
            Create Session Logger with Specific Events
            Creates a session logger that captures only specific events with JSONLines format and nested folder structure

            >>> await client.create(event_filter={'include': ['SessionStart', 'SessionEnd', 'UrlLoad', 'WebsiteInteract']}, log_configuration={'s3': {'bucket': 'my-session-logs-bucket', 'keyPrefix': 'session-logs/each/event', 'bucketOwner': '123456789012', 'logFileFormat': 'JSONLines', 'folderStructure': 'NestedByDate'}}, display_name='Session Logger with Each Events', customer_managed_key='arn:aws:kms:us-west-2:123456789012:key/12345678-1234-1234-1234-123456789012', additional_encryption_context={'EncryptionContextKey': 'EncryptionContextValue'}, tags=[{'Key': 'KEY-1', 'Value': 'VALUE-1'}, {'Key': 'KEY-2', 'Value': 'VALUE-2'}])
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.create_session_logger_request.CreateSessionLoggerRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.create_session_logger_response.CreateSessionLoggerResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_session_logger
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_session_logger.async_create_session_logger(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.create_session_logger_request.CreateSessionLoggerRequest = {}  # type: ignore[typeddict-item]
        input["event_filter"] = event_filter
        input["log_configuration"] = log_configuration
        if display_name is not None:
            input["display_name"] = display_name
        if customer_managed_key is not None:
            input["customer_managed_key"] = customer_managed_key
        if additional_encryption_context is not None:
            input["additional_encryption_context"] = additional_encryption_context
        if tags is not None:
            input["tags"] = tags
        if client_token is not None:
            input["client_token"] = client_token

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def read(self, session_logger_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.get_session_logger_response.GetSessionLoggerResponse":
        """<p>Gets details about a specific session logger resource.</p>

        Args:
            session_logger_arn: <p>The ARN of the session logger.</p>

        Examples:
            Get Session Logger with All Events
            Retrieves a session logger configured for all events

            >>> await client.read(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/12345678-1234-1234-1234-123456789012')
            Get Session Logger with Specific Events
            Retrieves a session logger configured for specific events

            >>> await client.read(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/87654321-4321-4321-4321-210987654321')
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.get_session_logger_request.GetSessionLoggerRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.get_session_logger_response.GetSessionLoggerResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_session_logger
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_session_logger.async_get_session_logger(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.get_session_logger_request.GetSessionLoggerRequest = {}  # type: ignore[typeddict-item]
        input["session_logger_arn"] = session_logger_arn

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def update(self, session_logger_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, event_filter: Optional["aws_sdk_workspaces_web.types.event_filter.EventFilter"] = None, log_configuration: Optional["aws_sdk_workspaces_web.types.log_configuration.LogConfiguration"] = None, display_name: Optional["aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"] = None) -> "aws_sdk_workspaces_web.types.update_session_logger_response.UpdateSessionLoggerResponse":
        """<p>Updates the details of a session logger.</p>

        Args:
            session_logger_arn: <p>The ARN of the session logger to update.</p>
            event_filter: <p>The updated eventFilter.</p>
            log_configuration: <p>The updated logConfiguration.</p>
            display_name: <p>The updated display name.</p>

        Examples:
            Update Session Logger Event Filter
            Updates a session logger to capture specific events instead of all events

            >>> await client.update(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/12345678-1234-1234-1234-123456789012', event_filter={'include': ['SessionStart', 'SessionEnd', 'UrlLoad', 'WebsiteInteract']})
            Update Session Logger Configuration
            Updates the log configuration of a session logger

            >>> await client.update(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/87654321-4321-4321-4321-210987654321', log_configuration={'s3': {'bucket': 'updated-my-session-logs-bucket-2', 'keyPrefix': 'updated/key/prefix', 'bucketOwner': '123456789012', 'logFileFormat': 'Json', 'folderStructure': 'Flat'}})
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.update_session_logger_request.UpdateSessionLoggerRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.update_session_logger_response.UpdateSessionLoggerResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_session_logger
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_session_logger.async_update_session_logger(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.update_session_logger_request.UpdateSessionLoggerRequest = {}  # type: ignore[typeddict-item]
        input["session_logger_arn"] = session_logger_arn
        if event_filter is not None:
            input["event_filter"] = event_filter
        if log_configuration is not None:
            input["log_configuration"] = log_configuration
        if display_name is not None:
            input["display_name"] = display_name

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def delete(self, session_logger_arn: "aws_sdk_workspaces_web.types.arn.ARN", *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None) -> "aws_sdk_workspaces_web.types.delete_session_logger_response.DeleteSessionLoggerResponse":
        """<p>Deletes a session logger resource.</p>

        Args:
            session_logger_arn: <p>The ARN of the session logger.</p>

        Examples:
            Delete Session Logger
            Deletes a session logger resource

            >>> await client.delete(session_logger_arn='arn:aws:workspaces-web:us-west-2:123456789012:sessionLogger/12345678-1234-1234-1234-123456789012')
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.delete_session_logger_request.DeleteSessionLoggerRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.delete_session_logger_response.DeleteSessionLoggerResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_session_logger
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_session_logger.async_delete_session_logger(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.delete_session_logger_request.DeleteSessionLoggerRequest = {}  # type: ignore[typeddict-item]
        input["session_logger_arn"] = session_logger_arn

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output
    async def list(self, *, config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None, next_token: Optional["aws_sdk_workspaces_web.types.pagination_token.PaginationToken"] = None, max_results: Optional["aws_sdk_workspaces_web.types.max_results.MaxResults"] = None) -> "aws_sdk_workspaces_web.types.list_session_loggers_response.ListSessionLoggersResponse":
        """<p>Lists all available session logger resources.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>

        Examples:
            List All Session Loggers
            Lists all session loggers in the account without pagination

            >>> await client.list()
            List Session Loggers with Pagination
            Lists session loggers with pagination parameters

            >>> await client.list(max_results=1, next_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9')
        """
        async def _handler(req: 'AsyncOperationRequest[aws_sdk_workspaces_web.types.list_session_loggers_request.ListSessionLoggersRequest]') -> AsyncOperationResponse["aws_sdk_workspaces_web.types.list_session_loggers_response.ListSessionLoggersResponse"]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_session_loggers
            output, http_response = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_session_loggers.async_list_session_loggers(req.options, req.input)
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input: aws_sdk_workspaces_web.types.list_session_loggers_request.ListSessionLoggersRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input["next_token"] = next_token
        if max_results is not None:
            input["max_results"] = max_results

        response = await aexecute_pipeline(AsyncOperationRequest(input=input, options=options_), handler=_handler, interceptors=list(interceptors_))
        return response.output