from typing import TYPE_CHECKING, Optional

import aws_sdk_workspaces_web._auth._signers
import aws_sdk_workspaces_web._auth._sigv4
from aws_sdk_workspaces_web._services._pipeline import (
    AsyncOperationRequest,
    AsyncOperationResponse,
    OperationRequest,
    OperationResponse,
    aexecute_pipeline,
    execute_pipeline,
)

if TYPE_CHECKING:
    import aws_sdk_workspaces_web.types.arn
    import aws_sdk_workspaces_web.types.certificate_list
    import aws_sdk_workspaces_web.types.certificate_thumbprint
    import aws_sdk_workspaces_web.types.certificate_thumbprint_list
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.create_trust_store_request
    import aws_sdk_workspaces_web.types.create_trust_store_response
    import aws_sdk_workspaces_web.types.delete_trust_store_request
    import aws_sdk_workspaces_web.types.delete_trust_store_response
    import aws_sdk_workspaces_web.types.get_trust_store_certificate_request
    import aws_sdk_workspaces_web.types.get_trust_store_certificate_response
    import aws_sdk_workspaces_web.types.get_trust_store_request
    import aws_sdk_workspaces_web.types.get_trust_store_response
    import aws_sdk_workspaces_web.types.list_trust_store_certificates_request
    import aws_sdk_workspaces_web.types.list_trust_store_certificates_response
    import aws_sdk_workspaces_web.types.list_trust_stores_request
    import aws_sdk_workspaces_web.types.list_trust_stores_response
    import aws_sdk_workspaces_web.types.max_results
    import aws_sdk_workspaces_web.types.pagination_token
    import aws_sdk_workspaces_web.types.tag_list
    import aws_sdk_workspaces_web.types.update_trust_store_request
    import aws_sdk_workspaces_web.types.update_trust_store_response
    from aws_sdk_workspaces_web._services.async_work_spaces_web import (
        AsyncWorkSpacesWebClient,
        AsyncWorkSpacesWebClientConfig,
    )
    from aws_sdk_workspaces_web._services.work_spaces_web import (
        WorkSpacesWebClient,
        WorkSpacesWebClientConfig,
    )


class TrustStoreResource:
    def __init__(self, service: WorkSpacesWebClient) -> None:
        self._service = service

    def create(
        self,
        certificate_list: "aws_sdk_workspaces_web.types.certificate_list.CertificateList",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.create_trust_store_response.CreateTrustStoreResponse":
        """<p>Creates a trust store that can be associated with a web portal. A trust store contains certificate authority (CA) certificates. Once associated with a web portal, the browser in a streaming session will recognize certificates that have been issued using any of the CAs in the trust store. If your organization has internal websites that use certificates issued by private CAs, you should add the private CA certificate to the trust store. </p>

        Args:
            certificate_list: <p>A list of CA certificates to be added to the trust store.</p>
            tags: <p>The tags to add to the trust store. A tag is a key-value pair.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.create_trust_store_request.CreateTrustStoreRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.create_trust_store_response.CreateTrustStoreResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_trust_store

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_trust_store.create_trust_store(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.create_trust_store_request.CreateTrustStoreRequest = {}  # type: ignore[typeddict-item]
        input_["certificate_list"] = certificate_list
        if tags is not None:
            input_["tags"] = tags
        if client_token is not None:
            input_["client_token"] = client_token

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def read(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_trust_store_response.GetTrustStoreResponse":
        """<p>Gets the trust store.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.get_trust_store_request.GetTrustStoreRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.get_trust_store_response.GetTrustStoreResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_trust_store

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_trust_store.get_trust_store(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_trust_store_request.GetTrustStoreRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def update(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        certificates_to_add: Optional[
            "aws_sdk_workspaces_web.types.certificate_list.CertificateList"
        ] = None,
        certificates_to_delete: Optional[
            "aws_sdk_workspaces_web.types.certificate_thumbprint_list.CertificateThumbprintList"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.update_trust_store_response.UpdateTrustStoreResponse":
        """<p>Updates the trust store.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store.</p>
            certificates_to_add: <p>A list of CA certificates to add to the trust store.</p>
            certificates_to_delete: <p>A list of CA certificates to delete from a trust store.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.update_trust_store_request.UpdateTrustStoreRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.update_trust_store_response.UpdateTrustStoreResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_trust_store

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_trust_store.update_trust_store(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.update_trust_store_request.UpdateTrustStoreRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn
        if certificates_to_add is not None:
            input_["certificates_to_add"] = certificates_to_add
        if certificates_to_delete is not None:
            input_["certificates_to_delete"] = certificates_to_delete
        if client_token is not None:
            input_["client_token"] = client_token

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def delete(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.delete_trust_store_response.DeleteTrustStoreResponse":
        """<p>Deletes the trust store.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.delete_trust_store_request.DeleteTrustStoreRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.delete_trust_store_response.DeleteTrustStoreResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_trust_store

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_trust_store.delete_trust_store(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.delete_trust_store_request.DeleteTrustStoreRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def list(
        self,
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_trust_stores_response.ListTrustStoresResponse":
        """<p>Retrieves a list of trust stores.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.list_trust_stores_request.ListTrustStoresRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.list_trust_stores_response.ListTrustStoresResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_trust_stores

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_trust_stores.list_trust_stores(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_trust_stores_request.ListTrustStoresRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def get_trust_store_certificate(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        thumbprint: "aws_sdk_workspaces_web.types.certificate_thumbprint.CertificateThumbprint",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_trust_store_certificate_response.GetTrustStoreCertificateResponse":
        """<p>Gets the trust store certificate.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store certificate.</p>
            thumbprint: <p>The thumbprint of the trust store certificate.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.get_trust_store_certificate_request.GetTrustStoreCertificateRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.get_trust_store_certificate_response.GetTrustStoreCertificateResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_trust_store_certificate

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_trust_store_certificate.get_trust_store_certificate(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_trust_store_certificate_request.GetTrustStoreCertificateRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn
        input_["thumbprint"] = thumbprint

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def list_trust_store_certificates(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_trust_store_certificates_response.ListTrustStoreCertificatesResponse":
        """<p>Retrieves a list of trust store certificates.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store</p>
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.list_trust_store_certificates_request.ListTrustStoreCertificatesRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.list_trust_store_certificates_response.ListTrustStoreCertificatesResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_trust_store_certificates

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_trust_store_certificates.list_trust_store_certificates(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_trust_store_certificates_request.ListTrustStoreCertificatesRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output


class AsyncTrustStoreResource:
    def __init__(self, service: AsyncWorkSpacesWebClient) -> None:
        self._service = service

    async def create(
        self,
        certificate_list: "aws_sdk_workspaces_web.types.certificate_list.CertificateList",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.create_trust_store_response.CreateTrustStoreResponse":
        """<p>Creates a trust store that can be associated with a web portal. A trust store contains certificate authority (CA) certificates. Once associated with a web portal, the browser in a streaming session will recognize certificates that have been issued using any of the CAs in the trust store. If your organization has internal websites that use certificates issued by private CAs, you should add the private CA certificate to the trust store. </p>

        Args:
            certificate_list: <p>A list of CA certificates to be added to the trust store.</p>
            tags: <p>The tags to add to the trust store. A tag is a key-value pair.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.create_trust_store_request.CreateTrustStoreRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.create_trust_store_response.CreateTrustStoreResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_trust_store

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_trust_store.async_create_trust_store(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.create_trust_store_request.CreateTrustStoreRequest = {}  # type: ignore[typeddict-item]
        input_["certificate_list"] = certificate_list
        if tags is not None:
            input_["tags"] = tags
        if client_token is not None:
            input_["client_token"] = client_token

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def read(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_trust_store_response.GetTrustStoreResponse":
        """<p>Gets the trust store.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.get_trust_store_request.GetTrustStoreRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.get_trust_store_response.GetTrustStoreResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_trust_store

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_trust_store.async_get_trust_store(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_trust_store_request.GetTrustStoreRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def update(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        certificates_to_add: Optional[
            "aws_sdk_workspaces_web.types.certificate_list.CertificateList"
        ] = None,
        certificates_to_delete: Optional[
            "aws_sdk_workspaces_web.types.certificate_thumbprint_list.CertificateThumbprintList"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.update_trust_store_response.UpdateTrustStoreResponse":
        """<p>Updates the trust store.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store.</p>
            certificates_to_add: <p>A list of CA certificates to add to the trust store.</p>
            certificates_to_delete: <p>A list of CA certificates to delete from a trust store.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.update_trust_store_request.UpdateTrustStoreRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.update_trust_store_response.UpdateTrustStoreResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_trust_store

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_trust_store.async_update_trust_store(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.update_trust_store_request.UpdateTrustStoreRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn
        if certificates_to_add is not None:
            input_["certificates_to_add"] = certificates_to_add
        if certificates_to_delete is not None:
            input_["certificates_to_delete"] = certificates_to_delete
        if client_token is not None:
            input_["client_token"] = client_token

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def delete(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.delete_trust_store_response.DeleteTrustStoreResponse":
        """<p>Deletes the trust store.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.delete_trust_store_request.DeleteTrustStoreRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.delete_trust_store_response.DeleteTrustStoreResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_trust_store

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_trust_store.async_delete_trust_store(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.delete_trust_store_request.DeleteTrustStoreRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def list(
        self,
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_trust_stores_response.ListTrustStoresResponse":
        """<p>Retrieves a list of trust stores.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.list_trust_stores_request.ListTrustStoresRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.list_trust_stores_response.ListTrustStoresResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_trust_stores

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_trust_stores.async_list_trust_stores(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_trust_stores_request.ListTrustStoresRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def get_trust_store_certificate(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        thumbprint: "aws_sdk_workspaces_web.types.certificate_thumbprint.CertificateThumbprint",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_trust_store_certificate_response.GetTrustStoreCertificateResponse":
        """<p>Gets the trust store certificate.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store certificate.</p>
            thumbprint: <p>The thumbprint of the trust store certificate.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.get_trust_store_certificate_request.GetTrustStoreCertificateRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.get_trust_store_certificate_response.GetTrustStoreCertificateResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_trust_store_certificate

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_trust_store_certificate.async_get_trust_store_certificate(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_trust_store_certificate_request.GetTrustStoreCertificateRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn
        input_["thumbprint"] = thumbprint

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def list_trust_store_certificates(
        self,
        trust_store_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_trust_store_certificates_response.ListTrustStoreCertificatesResponse":
        """<p>Retrieves a list of trust store certificates.</p>

        Args:
            trust_store_arn: <p>The ARN of the trust store</p>
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.list_trust_store_certificates_request.ListTrustStoreCertificatesRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.list_trust_store_certificates_response.ListTrustStoreCertificatesResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_trust_store_certificates

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_trust_store_certificates.async_list_trust_store_certificates(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_trust_store_certificates_request.ListTrustStoreCertificatesRequest = {}  # type: ignore[typeddict-item]
        input_["trust_store_arn"] = trust_store_arn
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output
