from __future__ import annotations

from typing import TYPE_CHECKING, Optional

import aws_sdk_workspaces_web._auth._signers
import aws_sdk_workspaces_web._auth._sigv4
from aws_sdk_workspaces_web._services._pipeline import (
    AsyncOperationRequest,
    AsyncOperationResponse,
    OperationRequest,
    OperationResponse,
    aexecute_pipeline,
    execute_pipeline,
)

if TYPE_CHECKING:
    import aws_sdk_workspaces_web.types.arn
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.create_user_access_logging_settings_request
    import aws_sdk_workspaces_web.types.create_user_access_logging_settings_response
    import aws_sdk_workspaces_web.types.delete_user_access_logging_settings_request
    import aws_sdk_workspaces_web.types.delete_user_access_logging_settings_response
    import aws_sdk_workspaces_web.types.get_user_access_logging_settings_request
    import aws_sdk_workspaces_web.types.get_user_access_logging_settings_response
    import aws_sdk_workspaces_web.types.kinesis_stream_arn
    import aws_sdk_workspaces_web.types.list_user_access_logging_settings_request
    import aws_sdk_workspaces_web.types.list_user_access_logging_settings_response
    import aws_sdk_workspaces_web.types.max_results
    import aws_sdk_workspaces_web.types.pagination_token
    import aws_sdk_workspaces_web.types.tag_list
    import aws_sdk_workspaces_web.types.update_user_access_logging_settings_request
    import aws_sdk_workspaces_web.types.update_user_access_logging_settings_response
    from aws_sdk_workspaces_web._services.async_work_spaces_web import (
        AsyncWorkSpacesWebClient,
        AsyncWorkSpacesWebClientConfig,
    )
    from aws_sdk_workspaces_web._services.work_spaces_web import (
        WorkSpacesWebClient,
        WorkSpacesWebClientConfig,
    )


class UserAccessLoggingSettingsResource:
    def __init__(self, service: WorkSpacesWebClient) -> None:
        self._service = service

    def create(
        self,
        kinesis_stream_arn: "aws_sdk_workspaces_web.types.kinesis_stream_arn.KinesisStreamArn",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.create_user_access_logging_settings_response.CreateUserAccessLoggingSettingsResponse":
        """<p>Creates a user access logging settings resource that can be associated with a web portal.</p>

        Args:
            kinesis_stream_arn: <p>The ARN of the Kinesis stream.</p>
            tags: <p>The tags to add to the user settings resource. A tag is a key-value pair.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.conflict_exception.ConflictException: <p>There is a conflict.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.service_quota_exceeded_exception.ServiceQuotaExceededException: <p>The service quota has been exceeded.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.create_user_access_logging_settings_request.CreateUserAccessLoggingSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.create_user_access_logging_settings_response.CreateUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_user_access_logging_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_user_access_logging_settings.create_user_access_logging_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.create_user_access_logging_settings_request.CreateUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["kinesis_stream_arn"] = kinesis_stream_arn
        if tags is not None:
            input_["tags"] = tags
        if client_token is not None:
            input_["client_token"] = client_token

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def read(
        self,
        user_access_logging_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_user_access_logging_settings_response.GetUserAccessLoggingSettingsResponse":
        """<p>Gets user access logging settings.</p>

        Args:
            user_access_logging_settings_arn: <p>The ARN of the user access logging settings.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.get_user_access_logging_settings_request.GetUserAccessLoggingSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.get_user_access_logging_settings_response.GetUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_user_access_logging_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_user_access_logging_settings.get_user_access_logging_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_user_access_logging_settings_request.GetUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["user_access_logging_settings_arn"] = user_access_logging_settings_arn

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def update(
        self,
        user_access_logging_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        kinesis_stream_arn: Optional[
            "aws_sdk_workspaces_web.types.kinesis_stream_arn.KinesisStreamArn"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.update_user_access_logging_settings_response.UpdateUserAccessLoggingSettingsResponse":
        """<p>Updates the user access logging settings.</p>

        Args:
            user_access_logging_settings_arn: <p>The ARN of the user access logging settings.</p>
            kinesis_stream_arn: <p>The ARN of the Kinesis stream.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.update_user_access_logging_settings_request.UpdateUserAccessLoggingSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.update_user_access_logging_settings_response.UpdateUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_user_access_logging_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_user_access_logging_settings.update_user_access_logging_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.update_user_access_logging_settings_request.UpdateUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["user_access_logging_settings_arn"] = user_access_logging_settings_arn
        if kinesis_stream_arn is not None:
            input_["kinesis_stream_arn"] = kinesis_stream_arn
        if client_token is not None:
            input_["client_token"] = client_token

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def delete(
        self,
        user_access_logging_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.delete_user_access_logging_settings_response.DeleteUserAccessLoggingSettingsResponse":
        """<p>Deletes user access logging settings.</p>

        Args:
            user_access_logging_settings_arn: <p>The ARN of the user access logging settings.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.conflict_exception.ConflictException: <p>There is a conflict.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.delete_user_access_logging_settings_request.DeleteUserAccessLoggingSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.delete_user_access_logging_settings_response.DeleteUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_user_access_logging_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_user_access_logging_settings.delete_user_access_logging_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.delete_user_access_logging_settings_request.DeleteUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["user_access_logging_settings_arn"] = user_access_logging_settings_arn

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def list(
        self,
        *,
        config_overrides: Optional[WorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_user_access_logging_settings_response.ListUserAccessLoggingSettingsResponse":
        """<p>Retrieves a list of user access logging settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        def _handler(
            req: "OperationRequest[aws_sdk_workspaces_web.types.list_user_access_logging_settings_request.ListUserAccessLoggingSettingsRequest]",
        ) -> OperationResponse[
            "aws_sdk_workspaces_web.types.list_user_access_logging_settings_response.ListUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_user_access_logging_settings

            output, http_response = (
                aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_user_access_logging_settings.list_user_access_logging_settings(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_user_access_logging_settings_request.ListUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output


class AsyncUserAccessLoggingSettingsResource:
    def __init__(self, service: AsyncWorkSpacesWebClient) -> None:
        self._service = service

    async def create(
        self,
        kinesis_stream_arn: "aws_sdk_workspaces_web.types.kinesis_stream_arn.KinesisStreamArn",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        tags: Optional["aws_sdk_workspaces_web.types.tag_list.TagList"] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.create_user_access_logging_settings_response.CreateUserAccessLoggingSettingsResponse":
        """<p>Creates a user access logging settings resource that can be associated with a web portal.</p>

        Args:
            kinesis_stream_arn: <p>The ARN of the Kinesis stream.</p>
            tags: <p>The tags to add to the user settings resource. A tag is a key-value pair.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.conflict_exception.ConflictException: <p>There is a conflict.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.service_quota_exceeded_exception.ServiceQuotaExceededException: <p>The service quota has been exceeded.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.create_user_access_logging_settings_request.CreateUserAccessLoggingSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.create_user_access_logging_settings_response.CreateUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_user_access_logging_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.create_user_access_logging_settings.async_create_user_access_logging_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.create_user_access_logging_settings_request.CreateUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["kinesis_stream_arn"] = kinesis_stream_arn
        if tags is not None:
            input_["tags"] = tags
        if client_token is not None:
            input_["client_token"] = client_token

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def read(
        self,
        user_access_logging_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.get_user_access_logging_settings_response.GetUserAccessLoggingSettingsResponse":
        """<p>Gets user access logging settings.</p>

        Args:
            user_access_logging_settings_arn: <p>The ARN of the user access logging settings.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.get_user_access_logging_settings_request.GetUserAccessLoggingSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.get_user_access_logging_settings_response.GetUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_user_access_logging_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.get_user_access_logging_settings.async_get_user_access_logging_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.get_user_access_logging_settings_request.GetUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["user_access_logging_settings_arn"] = user_access_logging_settings_arn

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def update(
        self,
        user_access_logging_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        kinesis_stream_arn: Optional[
            "aws_sdk_workspaces_web.types.kinesis_stream_arn.KinesisStreamArn"
        ] = None,
        client_token: Optional[
            "aws_sdk_workspaces_web.types.client_token.ClientToken"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.update_user_access_logging_settings_response.UpdateUserAccessLoggingSettingsResponse":
        """<p>Updates the user access logging settings.</p>

        Args:
            user_access_logging_settings_arn: <p>The ARN of the user access logging settings.</p>
            kinesis_stream_arn: <p>The ARN of the Kinesis stream.</p>
            client_token: <p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.resource_not_found_exception.ResourceNotFoundException: <p>The resource cannot be found.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.update_user_access_logging_settings_request.UpdateUserAccessLoggingSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.update_user_access_logging_settings_response.UpdateUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_user_access_logging_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.update_user_access_logging_settings.async_update_user_access_logging_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.update_user_access_logging_settings_request.UpdateUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["user_access_logging_settings_arn"] = user_access_logging_settings_arn
        if kinesis_stream_arn is not None:
            input_["kinesis_stream_arn"] = kinesis_stream_arn
        if client_token is not None:
            input_["client_token"] = client_token

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def delete(
        self,
        user_access_logging_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN",
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
    ) -> "aws_sdk_workspaces_web.types.delete_user_access_logging_settings_response.DeleteUserAccessLoggingSettingsResponse":
        """<p>Deletes user access logging settings.</p>

        Args:
            user_access_logging_settings_arn: <p>The ARN of the user access logging settings.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.conflict_exception.ConflictException: <p>There is a conflict.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.delete_user_access_logging_settings_request.DeleteUserAccessLoggingSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.delete_user_access_logging_settings_response.DeleteUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_user_access_logging_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.delete_user_access_logging_settings.async_delete_user_access_logging_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.delete_user_access_logging_settings_request.DeleteUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        input_["user_access_logging_settings_arn"] = user_access_logging_settings_arn

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def list(
        self,
        *,
        config_overrides: Optional[AsyncWorkSpacesWebClientConfig] = None,
        next_token: Optional[
            "aws_sdk_workspaces_web.types.pagination_token.PaginationToken"
        ] = None,
        max_results: Optional[
            "aws_sdk_workspaces_web.types.max_results.MaxResults"
        ] = None,
    ) -> "aws_sdk_workspaces_web.types.list_user_access_logging_settings_response.ListUserAccessLoggingSettingsResponse":
        """<p>Retrieves a list of user access logging settings.</p>

        Args:
            next_token: <p>The pagination token used to retrieve the next page of results for this operation.</p>
            max_results: <p>The maximum number of results to be included in the next page.</p>

        Raises:
            aws_sdk_workspaces_web.errors.access_denied_exception.AccessDeniedException: <p>Access is denied.</p>
            aws_sdk_workspaces_web.errors.internal_server_exception.InternalServerException: <p>There is an internal server error.</p>
            aws_sdk_workspaces_web.errors.throttling_exception.ThrottlingException: <p>There is a throttling error.</p>
            aws_sdk_workspaces_web.errors.validation_exception.ValidationException: <p>There is a validation error.</p>
            aws_sdk_workspaces_web.errors.UnknownServiceError: The service returned an error code this client does not model.
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_workspaces_web.types.list_user_access_logging_settings_request.ListUserAccessLoggingSettingsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_workspaces_web.types.list_user_access_logging_settings_response.ListUserAccessLoggingSettingsResponse"
        ]:
            import aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_user_access_logging_settings

            (
                output,
                http_response,
            ) = await aws_sdk_workspaces_web._operations.aws_ermine_control_plane_service.list_user_access_logging_settings.async_list_user_access_logging_settings(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_workspaces_web.types.list_user_access_logging_settings_request.ListUserAccessLoggingSettingsRequest = {}  # type: ignore[typeddict-item]
        if next_token is not None:
            input_["next_token"] = next_token
        if max_results is not None:
            input_["max_results"] = max_results

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output
