"""Generated from Smithy shape ``com.amazonaws.mediaconnect#ListedGatewayInstance``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import aws_sdk_mediaconnect.types.instance_state


class ListedGatewayInstance(TypedDict, closed=True):
    gateway_arn: NotRequired["str"]
    """<p> The Amazon Resource Name (ARN) of the gateway.</p>"""
    gateway_instance_arn: NotRequired["str"]
    """<p> The Amazon Resource Name (ARN) of the instance.</p>"""
    instance_id: NotRequired["str"]
    r"""<p> The managed instance ID generated by the SSM install. This will begin with \"mi-\".</p>"""
    instance_state: NotRequired[
        "aws_sdk_mediaconnect.types.instance_state.InstanceState"
    ]
    """<p> The status of the instance.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ListedGatewayInstance) -> dict:
    out: dict = {}
    if "gateway_arn" in value:
        out["gatewayArn"] = value["gateway_arn"]
    if "gateway_instance_arn" in value:
        out["gatewayInstanceArn"] = value["gateway_instance_arn"]
    if "instance_id" in value:
        out["instanceId"] = value["instance_id"]
    if "instance_state" in value:
        import aws_sdk_mediaconnect.types.instance_state

        out["instanceState"] = aws_sdk_mediaconnect.types.instance_state.serialize_json(
            value["instance_state"]
        )
    return out


def deserialize_json(data: dict) -> ListedGatewayInstance:
    out: ListedGatewayInstance = {}  # type: ignore[typeddict-item]
    if "gatewayArn" in data:
        out["gateway_arn"] = data["gatewayArn"]
    if "gatewayInstanceArn" in data:
        out["gateway_instance_arn"] = data["gatewayInstanceArn"]
    if "instanceId" in data:
        out["instance_id"] = data["instanceId"]
    if "instanceState" in data:
        import aws_sdk_mediaconnect.types.instance_state

        out["instance_state"] = (
            aws_sdk_mediaconnect.types.instance_state.deserialize_json(
                data["instanceState"]
            )
        )
    return out
