from __future__ import annotations

from typing import TYPE_CHECKING, Optional

import aws_sdk_omics._auth._signers
import aws_sdk_omics._auth._sigv4
from aws_sdk_omics._services._pipeline import (
    AsyncOperationRequest,
    AsyncOperationResponse,
    OperationRequest,
    OperationResponse,
    aexecute_pipeline,
    execute_pipeline,
)

if TYPE_CHECKING:
    import aws_sdk_omics.types.annotation_field_map
    import aws_sdk_omics.types.annotation_import_item_sources
    import aws_sdk_omics.types.annotation_import_job_item
    import aws_sdk_omics.types.arn
    import aws_sdk_omics.types.cancel_annotation_import_request
    import aws_sdk_omics.types.cancel_annotation_import_response
    import aws_sdk_omics.types.format_options
    import aws_sdk_omics.types.get_annotation_import_request
    import aws_sdk_omics.types.get_annotation_import_response
    import aws_sdk_omics.types.id_list
    import aws_sdk_omics.types.list_annotation_import_jobs_filter
    import aws_sdk_omics.types.list_annotation_import_jobs_request
    import aws_sdk_omics.types.list_annotation_import_jobs_response
    import aws_sdk_omics.types.resource_id
    import aws_sdk_omics.types.run_left_normalization
    import aws_sdk_omics.types.start_annotation_import_request
    import aws_sdk_omics.types.start_annotation_import_response
    import aws_sdk_omics.types.store_name
    import aws_sdk_omics.types.version_name
    from aws_sdk_omics._services.async_omics import (
        AsyncOmicsClient,
        AsyncOmicsClientConfig,
    )
    from aws_sdk_omics._services.omics import OmicsClient, OmicsClientConfig


class AnnotationImportJob:
    def __init__(self, service: OmicsClient) -> None:
        self._service = service

    def create(
        self,
        destination_name: "aws_sdk_omics.types.store_name.StoreName",
        role_arn: "aws_sdk_omics.types.arn.Arn",
        items: "aws_sdk_omics.types.annotation_import_item_sources.AnnotationImportItemSources",
        *,
        config_overrides: Optional[OmicsClientConfig] = None,
        version_name: Optional["aws_sdk_omics.types.version_name.VersionName"] = None,
        format_options: Optional[
            "aws_sdk_omics.types.format_options.FormatOptions"
        ] = None,
        run_left_normalization: Optional[
            "aws_sdk_omics.types.run_left_normalization.RunLeftNormalization"
        ] = None,
        annotation_fields: Optional[
            "aws_sdk_omics.types.annotation_field_map.AnnotationFieldMap"
        ] = None,
    ) -> "aws_sdk_omics.types.start_annotation_import_response.StartAnnotationImportResponse":
        r"""<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Starts an annotation import job.</p>

        Args:
            destination_name: <p>A destination annotation store for the job.</p>
            role_arn: <p>A service role for the job.</p>
            items: <p>Items to import.</p>
            version_name: <p> The name of the annotation store version. </p>
            format_options: <p>Formatting options for the annotation file.</p>
            run_left_normalization: <p>The job's left normalization setting.</p>
            annotation_fields: <p>The annotation schema generated by the parsed annotation data.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_omics.types.start_annotation_import_request.StartAnnotationImportRequest]",
        ) -> OperationResponse[
            "aws_sdk_omics.types.start_annotation_import_response.StartAnnotationImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.start_annotation_import_job

            output, http_response = (
                aws_sdk_omics._operations.omics.start_annotation_import_job.start_annotation_import_job(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.start_annotation_import_request.StartAnnotationImportRequest = {}  # type: ignore[typeddict-item]
        input_["destination_name"] = destination_name
        input_["role_arn"] = role_arn
        input_["items"] = items
        if version_name is not None:
            input_["version_name"] = version_name
        if format_options is not None:
            input_["format_options"] = format_options
        if run_left_normalization is not None:
            input_["run_left_normalization"] = run_left_normalization
        if annotation_fields is not None:
            input_["annotation_fields"] = annotation_fields

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def read(
        self,
        job_id: "aws_sdk_omics.types.resource_id.ResourceId",
        *,
        config_overrides: Optional[OmicsClientConfig] = None,
    ) -> (
        "aws_sdk_omics.types.get_annotation_import_response.GetAnnotationImportResponse"
    ):
        r"""<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Gets information about an annotation import job.</p>

        Args:
            job_id: <p>The job's ID.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_omics.types.get_annotation_import_request.GetAnnotationImportRequest]",
        ) -> OperationResponse[
            "aws_sdk_omics.types.get_annotation_import_response.GetAnnotationImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.get_annotation_import_job

            output, http_response = (
                aws_sdk_omics._operations.omics.get_annotation_import_job.get_annotation_import_job(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.get_annotation_import_request.GetAnnotationImportRequest = {}  # type: ignore[typeddict-item]
        input_["job_id"] = job_id

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def delete(
        self,
        job_id: "aws_sdk_omics.types.resource_id.ResourceId",
        *,
        config_overrides: Optional[OmicsClientConfig] = None,
    ) -> "aws_sdk_omics.types.cancel_annotation_import_response.CancelAnnotationImportResponse":
        r"""<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Cancels an annotation import job.</p>

        Args:
            job_id: <p>The job's ID.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_omics.types.cancel_annotation_import_request.CancelAnnotationImportRequest]",
        ) -> OperationResponse[
            "aws_sdk_omics.types.cancel_annotation_import_response.CancelAnnotationImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.cancel_annotation_import_job

            output, http_response = (
                aws_sdk_omics._operations.omics.cancel_annotation_import_job.cancel_annotation_import_job(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.cancel_annotation_import_request.CancelAnnotationImportRequest = {}  # type: ignore[typeddict-item]
        input_["job_id"] = job_id

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def list(
        self,
        *,
        config_overrides: Optional[OmicsClientConfig] = None,
        max_results: Optional[int] = None,
        ids: Optional["aws_sdk_omics.types.id_list.IdList"] = None,
        next_token: Optional[str] = None,
        filter: Optional[
            "aws_sdk_omics.types.list_annotation_import_jobs_filter.ListAnnotationImportJobsFilter"
        ] = None,
    ) -> "aws_sdk_omics.types.list_annotation_import_jobs_response.ListAnnotationImportJobsResponse":
        r"""<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Retrieves a list of annotation import jobs.</p>

        Args:
            max_results: <p>The maximum number of jobs to return in one page of results.</p>
            ids: <p>IDs of annotation import jobs to retrieve.</p>
            next_token: <p>Specifies the pagination token from a previous request to retrieve the next page of results.</p>
            filter: <p>A filter to apply to the list.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_omics.types.list_annotation_import_jobs_request.ListAnnotationImportJobsRequest]",
        ) -> OperationResponse[
            "aws_sdk_omics.types.list_annotation_import_jobs_response.ListAnnotationImportJobsResponse"
        ]:
            import aws_sdk_omics._operations.omics.list_annotation_import_jobs

            output, http_response = (
                aws_sdk_omics._operations.omics.list_annotation_import_jobs.list_annotation_import_jobs(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.list_annotation_import_jobs_request.ListAnnotationImportJobsRequest = {}  # type: ignore[typeddict-item]
        if max_results is not None:
            input_["max_results"] = max_results
        if ids is not None:
            input_["ids"] = ids
        if next_token is not None:
            input_["next_token"] = next_token
        if filter is not None:
            input_["filter"] = filter

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output


class AsyncAnnotationImportJob:
    def __init__(self, service: AsyncOmicsClient) -> None:
        self._service = service

    async def create(
        self,
        destination_name: "aws_sdk_omics.types.store_name.StoreName",
        role_arn: "aws_sdk_omics.types.arn.Arn",
        items: "aws_sdk_omics.types.annotation_import_item_sources.AnnotationImportItemSources",
        *,
        config_overrides: Optional[AsyncOmicsClientConfig] = None,
        version_name: Optional["aws_sdk_omics.types.version_name.VersionName"] = None,
        format_options: Optional[
            "aws_sdk_omics.types.format_options.FormatOptions"
        ] = None,
        run_left_normalization: Optional[
            "aws_sdk_omics.types.run_left_normalization.RunLeftNormalization"
        ] = None,
        annotation_fields: Optional[
            "aws_sdk_omics.types.annotation_field_map.AnnotationFieldMap"
        ] = None,
    ) -> "aws_sdk_omics.types.start_annotation_import_response.StartAnnotationImportResponse":
        r"""<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Starts an annotation import job.</p>

        Args:
            destination_name: <p>A destination annotation store for the job.</p>
            role_arn: <p>A service role for the job.</p>
            items: <p>Items to import.</p>
            version_name: <p> The name of the annotation store version. </p>
            format_options: <p>Formatting options for the annotation file.</p>
            run_left_normalization: <p>The job's left normalization setting.</p>
            annotation_fields: <p>The annotation schema generated by the parsed annotation data.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_omics.types.start_annotation_import_request.StartAnnotationImportRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_omics.types.start_annotation_import_response.StartAnnotationImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.start_annotation_import_job

            (
                output,
                http_response,
            ) = await aws_sdk_omics._operations.omics.start_annotation_import_job.async_start_annotation_import_job(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.start_annotation_import_request.StartAnnotationImportRequest = {}  # type: ignore[typeddict-item]
        input_["destination_name"] = destination_name
        input_["role_arn"] = role_arn
        input_["items"] = items
        if version_name is not None:
            input_["version_name"] = version_name
        if format_options is not None:
            input_["format_options"] = format_options
        if run_left_normalization is not None:
            input_["run_left_normalization"] = run_left_normalization
        if annotation_fields is not None:
            input_["annotation_fields"] = annotation_fields

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def read(
        self,
        job_id: "aws_sdk_omics.types.resource_id.ResourceId",
        *,
        config_overrides: Optional[AsyncOmicsClientConfig] = None,
    ) -> (
        "aws_sdk_omics.types.get_annotation_import_response.GetAnnotationImportResponse"
    ):
        r"""<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Gets information about an annotation import job.</p>

        Args:
            job_id: <p>The job's ID.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_omics.types.get_annotation_import_request.GetAnnotationImportRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_omics.types.get_annotation_import_response.GetAnnotationImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.get_annotation_import_job

            (
                output,
                http_response,
            ) = await aws_sdk_omics._operations.omics.get_annotation_import_job.async_get_annotation_import_job(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.get_annotation_import_request.GetAnnotationImportRequest = {}  # type: ignore[typeddict-item]
        input_["job_id"] = job_id

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def delete(
        self,
        job_id: "aws_sdk_omics.types.resource_id.ResourceId",
        *,
        config_overrides: Optional[AsyncOmicsClientConfig] = None,
    ) -> "aws_sdk_omics.types.cancel_annotation_import_response.CancelAnnotationImportResponse":
        r"""<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Cancels an annotation import job.</p>

        Args:
            job_id: <p>The job's ID.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_omics.types.cancel_annotation_import_request.CancelAnnotationImportRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_omics.types.cancel_annotation_import_response.CancelAnnotationImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.cancel_annotation_import_job

            (
                output,
                http_response,
            ) = await aws_sdk_omics._operations.omics.cancel_annotation_import_job.async_cancel_annotation_import_job(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.cancel_annotation_import_request.CancelAnnotationImportRequest = {}  # type: ignore[typeddict-item]
        input_["job_id"] = job_id

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def list(
        self,
        *,
        config_overrides: Optional[AsyncOmicsClientConfig] = None,
        max_results: Optional[int] = None,
        ids: Optional["aws_sdk_omics.types.id_list.IdList"] = None,
        next_token: Optional[str] = None,
        filter: Optional[
            "aws_sdk_omics.types.list_annotation_import_jobs_filter.ListAnnotationImportJobsFilter"
        ] = None,
    ) -> "aws_sdk_omics.types.list_annotation_import_jobs_response.ListAnnotationImportJobsResponse":
        r"""<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Retrieves a list of annotation import jobs.</p>

        Args:
            max_results: <p>The maximum number of jobs to return in one page of results.</p>
            ids: <p>IDs of annotation import jobs to retrieve.</p>
            next_token: <p>Specifies the pagination token from a previous request to retrieve the next page of results.</p>
            filter: <p>A filter to apply to the list.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_omics.types.list_annotation_import_jobs_request.ListAnnotationImportJobsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_omics.types.list_annotation_import_jobs_response.ListAnnotationImportJobsResponse"
        ]:
            import aws_sdk_omics._operations.omics.list_annotation_import_jobs

            (
                output,
                http_response,
            ) = await aws_sdk_omics._operations.omics.list_annotation_import_jobs.async_list_annotation_import_jobs(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.list_annotation_import_jobs_request.ListAnnotationImportJobsRequest = {}  # type: ignore[typeddict-item]
        if max_results is not None:
            input_["max_results"] = max_results
        if ids is not None:
            input_["ids"] = ids
        if next_token is not None:
            input_["next_token"] = next_token
        if filter is not None:
            input_["filter"] = filter

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output
