from typing import TYPE_CHECKING, Optional

import aws_sdk_omics._auth._signers
import aws_sdk_omics._auth._sigv4
from aws_sdk_omics._services._pipeline import (
    AsyncOperationRequest,
    AsyncOperationResponse,
    OperationRequest,
    OperationResponse,
    aexecute_pipeline,
    execute_pipeline,
)

if TYPE_CHECKING:
    import aws_sdk_omics.types.annotation_field_map
    import aws_sdk_omics.types.arn
    import aws_sdk_omics.types.cancel_variant_import_request
    import aws_sdk_omics.types.cancel_variant_import_response
    import aws_sdk_omics.types.get_variant_import_request
    import aws_sdk_omics.types.get_variant_import_response
    import aws_sdk_omics.types.id_list
    import aws_sdk_omics.types.list_variant_import_jobs_filter
    import aws_sdk_omics.types.list_variant_import_jobs_request
    import aws_sdk_omics.types.list_variant_import_jobs_response
    import aws_sdk_omics.types.resource_id
    import aws_sdk_omics.types.run_left_normalization
    import aws_sdk_omics.types.start_variant_import_request
    import aws_sdk_omics.types.start_variant_import_response
    import aws_sdk_omics.types.store_name
    import aws_sdk_omics.types.variant_import_item_sources
    import aws_sdk_omics.types.variant_import_job_item
    from aws_sdk_omics._services.async_omics import (
        AsyncOmicsClient,
        AsyncOmicsClientConfig,
    )
    from aws_sdk_omics._services.omics import OmicsClient, OmicsClientConfig


class VariantImportJob:
    def __init__(self, service: OmicsClient) -> None:
        self._service = service

    def create(
        self,
        destination_name: "aws_sdk_omics.types.store_name.StoreName",
        role_arn: "aws_sdk_omics.types.arn.Arn",
        items: "aws_sdk_omics.types.variant_import_item_sources.VariantImportItemSources",
        *,
        config_overrides: Optional[OmicsClientConfig] = None,
        run_left_normalization: Optional[
            "aws_sdk_omics.types.run_left_normalization.RunLeftNormalization"
        ] = None,
        annotation_fields: Optional[
            "aws_sdk_omics.types.annotation_field_map.AnnotationFieldMap"
        ] = None,
    ) -> "aws_sdk_omics.types.start_variant_import_response.StartVariantImportResponse":
        """<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Starts a variant import job.</p>

        Args:
            destination_name: <p>The destination variant store for the job.</p>
            role_arn: <p>A service role for the job.</p>
            items: <p>Items to import.</p>
            run_left_normalization: <p>The job's left normalization setting.</p>
            annotation_fields: <p>The annotation schema generated by the parsed annotation data.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_omics.types.start_variant_import_request.StartVariantImportRequest]",
        ) -> OperationResponse[
            "aws_sdk_omics.types.start_variant_import_response.StartVariantImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.start_variant_import_job

            output, http_response = (
                aws_sdk_omics._operations.omics.start_variant_import_job.start_variant_import_job(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.start_variant_import_request.StartVariantImportRequest = {}  # type: ignore[typeddict-item]
        input_["destination_name"] = destination_name
        input_["role_arn"] = role_arn
        input_["items"] = items
        if run_left_normalization is not None:
            input_["run_left_normalization"] = run_left_normalization
        if annotation_fields is not None:
            input_["annotation_fields"] = annotation_fields

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def read(
        self,
        job_id: "aws_sdk_omics.types.resource_id.ResourceId",
        *,
        config_overrides: Optional[OmicsClientConfig] = None,
    ) -> "aws_sdk_omics.types.get_variant_import_response.GetVariantImportResponse":
        """<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Gets information about a variant import job.</p>

        Args:
            job_id: <p>The job's ID.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_omics.types.get_variant_import_request.GetVariantImportRequest]",
        ) -> OperationResponse[
            "aws_sdk_omics.types.get_variant_import_response.GetVariantImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.get_variant_import_job

            output, http_response = (
                aws_sdk_omics._operations.omics.get_variant_import_job.get_variant_import_job(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.get_variant_import_request.GetVariantImportRequest = {}  # type: ignore[typeddict-item]
        input_["job_id"] = job_id

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def delete(
        self,
        job_id: "aws_sdk_omics.types.resource_id.ResourceId",
        *,
        config_overrides: Optional[OmicsClientConfig] = None,
    ) -> (
        "aws_sdk_omics.types.cancel_variant_import_response.CancelVariantImportResponse"
    ):
        """<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Cancels a variant import job.</p>

        Args:
            job_id: <p>The job's ID.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_omics.types.cancel_variant_import_request.CancelVariantImportRequest]",
        ) -> OperationResponse[
            "aws_sdk_omics.types.cancel_variant_import_response.CancelVariantImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.cancel_variant_import_job

            output, http_response = (
                aws_sdk_omics._operations.omics.cancel_variant_import_job.cancel_variant_import_job(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.cancel_variant_import_request.CancelVariantImportRequest = {}  # type: ignore[typeddict-item]
        input_["job_id"] = job_id

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    def list(
        self,
        *,
        config_overrides: Optional[OmicsClientConfig] = None,
        max_results: Optional[int] = None,
        ids: Optional["aws_sdk_omics.types.id_list.IdList"] = None,
        next_token: Optional[str] = None,
        filter: Optional[
            "aws_sdk_omics.types.list_variant_import_jobs_filter.ListVariantImportJobsFilter"
        ] = None,
    ) -> "aws_sdk_omics.types.list_variant_import_jobs_response.ListVariantImportJobsResponse":
        """<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Retrieves a list of variant import jobs.</p>

        Args:
            max_results: <p>The maximum number of import jobs to return in one page of results.</p>
            ids: <p>A list of job IDs.</p>
            next_token: <p>Specify the pagination token from a previous request to retrieve the next page of results.</p>
            filter: <p>A filter to apply to the list.</p>
        """

        def _handler(
            req: "OperationRequest[aws_sdk_omics.types.list_variant_import_jobs_request.ListVariantImportJobsRequest]",
        ) -> OperationResponse[
            "aws_sdk_omics.types.list_variant_import_jobs_response.ListVariantImportJobsResponse"
        ]:
            import aws_sdk_omics._operations.omics.list_variant_import_jobs

            output, http_response = (
                aws_sdk_omics._operations.omics.list_variant_import_jobs.list_variant_import_jobs(
                    req.options, req.input
                )
            )
            return OperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.list_variant_import_jobs_request.ListVariantImportJobsRequest = {}  # type: ignore[typeddict-item]
        if max_results is not None:
            input_["max_results"] = max_results
        if ids is not None:
            input_["ids"] = ids
        if next_token is not None:
            input_["next_token"] = next_token
        if filter is not None:
            input_["filter"] = filter

        response = execute_pipeline(
            OperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output


class AsyncVariantImportJob:
    def __init__(self, service: AsyncOmicsClient) -> None:
        self._service = service

    async def create(
        self,
        destination_name: "aws_sdk_omics.types.store_name.StoreName",
        role_arn: "aws_sdk_omics.types.arn.Arn",
        items: "aws_sdk_omics.types.variant_import_item_sources.VariantImportItemSources",
        *,
        config_overrides: Optional[AsyncOmicsClientConfig] = None,
        run_left_normalization: Optional[
            "aws_sdk_omics.types.run_left_normalization.RunLeftNormalization"
        ] = None,
        annotation_fields: Optional[
            "aws_sdk_omics.types.annotation_field_map.AnnotationFieldMap"
        ] = None,
    ) -> "aws_sdk_omics.types.start_variant_import_response.StartVariantImportResponse":
        """<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Starts a variant import job.</p>

        Args:
            destination_name: <p>The destination variant store for the job.</p>
            role_arn: <p>A service role for the job.</p>
            items: <p>Items to import.</p>
            run_left_normalization: <p>The job's left normalization setting.</p>
            annotation_fields: <p>The annotation schema generated by the parsed annotation data.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_omics.types.start_variant_import_request.StartVariantImportRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_omics.types.start_variant_import_response.StartVariantImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.start_variant_import_job

            (
                output,
                http_response,
            ) = await aws_sdk_omics._operations.omics.start_variant_import_job.async_start_variant_import_job(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.start_variant_import_request.StartVariantImportRequest = {}  # type: ignore[typeddict-item]
        input_["destination_name"] = destination_name
        input_["role_arn"] = role_arn
        input_["items"] = items
        if run_left_normalization is not None:
            input_["run_left_normalization"] = run_left_normalization
        if annotation_fields is not None:
            input_["annotation_fields"] = annotation_fields

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def read(
        self,
        job_id: "aws_sdk_omics.types.resource_id.ResourceId",
        *,
        config_overrides: Optional[AsyncOmicsClientConfig] = None,
    ) -> "aws_sdk_omics.types.get_variant_import_response.GetVariantImportResponse":
        """<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Gets information about a variant import job.</p>

        Args:
            job_id: <p>The job's ID.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_omics.types.get_variant_import_request.GetVariantImportRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_omics.types.get_variant_import_response.GetVariantImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.get_variant_import_job

            (
                output,
                http_response,
            ) = await aws_sdk_omics._operations.omics.get_variant_import_job.async_get_variant_import_job(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.get_variant_import_request.GetVariantImportRequest = {}  # type: ignore[typeddict-item]
        input_["job_id"] = job_id

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def delete(
        self,
        job_id: "aws_sdk_omics.types.resource_id.ResourceId",
        *,
        config_overrides: Optional[AsyncOmicsClientConfig] = None,
    ) -> (
        "aws_sdk_omics.types.cancel_variant_import_response.CancelVariantImportResponse"
    ):
        """<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Cancels a variant import job.</p>

        Args:
            job_id: <p>The job's ID.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_omics.types.cancel_variant_import_request.CancelVariantImportRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_omics.types.cancel_variant_import_response.CancelVariantImportResponse"
        ]:
            import aws_sdk_omics._operations.omics.cancel_variant_import_job

            (
                output,
                http_response,
            ) = await aws_sdk_omics._operations.omics.cancel_variant_import_job.async_cancel_variant_import_job(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.cancel_variant_import_request.CancelVariantImportRequest = {}  # type: ignore[typeddict-item]
        input_["job_id"] = job_id

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output

    async def list(
        self,
        *,
        config_overrides: Optional[AsyncOmicsClientConfig] = None,
        max_results: Optional[int] = None,
        ids: Optional["aws_sdk_omics.types.id_list.IdList"] = None,
        next_token: Optional[str] = None,
        filter: Optional[
            "aws_sdk_omics.types.list_variant_import_jobs_filter.ListVariantImportJobsFilter"
        ] = None,
    ) -> "aws_sdk_omics.types.list_variant_import_jobs_response.ListVariantImportJobsResponse":
        """<important> <p>Amazon Web Services HealthOmics variant stores and annotation stores are no longer open to new customers. Existing customers can continue to use the service as normal. For more information, see <a href=\"https://docs.aws.amazon.com/omics/latest/dev/variant-store-availability-change.html\"> Amazon Web Services HealthOmics variant store and annotation store availability change</a>.</p> </important> <p>Retrieves a list of variant import jobs.</p>

        Args:
            max_results: <p>The maximum number of import jobs to return in one page of results.</p>
            ids: <p>A list of job IDs.</p>
            next_token: <p>Specify the pagination token from a previous request to retrieve the next page of results.</p>
            filter: <p>A filter to apply to the list.</p>
        """

        async def _handler(
            req: "AsyncOperationRequest[aws_sdk_omics.types.list_variant_import_jobs_request.ListVariantImportJobsRequest]",
        ) -> AsyncOperationResponse[
            "aws_sdk_omics.types.list_variant_import_jobs_response.ListVariantImportJobsResponse"
        ]:
            import aws_sdk_omics._operations.omics.list_variant_import_jobs

            (
                output,
                http_response,
            ) = await aws_sdk_omics._operations.omics.list_variant_import_jobs.async_list_variant_import_jobs(
                req.options, req.input
            )
            return AsyncOperationResponse(output=output, response=http_response)

        interceptors_, options_ = self._service.operation_options(config_overrides)
        input_: aws_sdk_omics.types.list_variant_import_jobs_request.ListVariantImportJobsRequest = {}  # type: ignore[typeddict-item]
        if max_results is not None:
            input_["max_results"] = max_results
        if ids is not None:
            input_["ids"] = ids
        if next_token is not None:
            input_["next_token"] = next_token
        if filter is not None:
            input_["filter"] = filter

        response = await aexecute_pipeline(
            AsyncOperationRequest(input=input_, options=options_),
            handler=_handler,
            interceptors=list(interceptors_),
        )
        return response.output
