"""Generated from Smithy shape ``com.amazonaws.polly#VoiceId``."""

from typing import Literal, TypeAlias, cast

VoiceId: TypeAlias = Literal[
    "Aditi",
    "Amy",
    "Astrid",
    "Bianca",
    "Brian",
    "Camila",
    "Carla",
    "Carmen",
    "Celine",
    "Chantal",
    "Conchita",
    "Cristiano",
    "Dora",
    "Emma",
    "Enrique",
    "Ewa",
    "Filiz",
    "Gabrielle",
    "Geraint",
    "Giorgio",
    "Gwyneth",
    "Hans",
    "Ines",
    "Ivy",
    "Jacek",
    "Jan",
    "Joanna",
    "Joey",
    "Justin",
    "Karl",
    "Kendra",
    "Kevin",
    "Kimberly",
    "Lea",
    "Liv",
    "Lotte",
    "Lucia",
    "Lupe",
    "Mads",
    "Maja",
    "Marlene",
    "Mathieu",
    "Matthew",
    "Maxim",
    "Mia",
    "Miguel",
    "Mizuki",
    "Naja",
    "Nicole",
    "Olivia",
    "Penelope",
    "Raveena",
    "Ricardo",
    "Ruben",
    "Russell",
    "Salli",
    "Seoyeon",
    "Takumi",
    "Tatyana",
    "Vicki",
    "Vitoria",
    "Zeina",
    "Zhiyu",
    "Aria",
    "Ayanda",
    "Arlet",
    "Hannah",
    "Arthur",
    "Daniel",
    "Liam",
    "Pedro",
    "Kajal",
    "Hiujin",
    "Laura",
    "Elin",
    "Ida",
    "Suvi",
    "Ola",
    "Hala",
    "Andres",
    "Sergio",
    "Remi",
    "Adriano",
    "Thiago",
    "Ruth",
    "Stephen",
    "Kazuha",
    "Tomoko",
    "Niamh",
    "Sofie",
    "Lisa",
    "Isabelle",
    "Zayd",
    "Danielle",
    "Gregory",
    "Burcu",
    "Jitka",
    "Sabrina",
    "Jasmine",
    "Jihye",
    "Ambre",
    "Beatrice",
    "Florian",
    "Lennart",
    "Lorenzo",
    "Tiffany",
]


# --- restJson1 ser/de ---
def serialize_json(value: VoiceId) -> str:
    return value


def deserialize_json(data: str) -> VoiceId:
    return cast(VoiceId, data)
