"""Generated from Smithy shape ``com.amazonaws.lambda#CallbackDetails``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

if TYPE_CHECKING:
    import aws_sdk_lambda.types.callback_id
    import aws_sdk_lambda.types.error_object
    import aws_sdk_lambda.types.operation_payload


class CallbackDetails(TypedDict):
    callback_id: NotRequired["aws_sdk_lambda.types.callback_id.CallbackId"]
    """<p>The callback ID. Callback IDs are generated by the <code>DurableContext</code> when a durable function calls <code>ctx.waitForCallback</code>.</p>"""
    result: NotRequired["aws_sdk_lambda.types.operation_payload.OperationPayload"]
    """<p>The response payload from the callback operation as a string.</p>"""
    error: NotRequired["aws_sdk_lambda.types.error_object.ErrorObject"]
    """<p>An error object that contains details about the failure.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: CallbackDetails) -> dict:
    out: dict = {}
    if "callback_id" in value:
        out["CallbackId"] = value["callback_id"]
    if "result" in value:
        out["Result"] = value["result"]
    if "error" in value:
        import aws_sdk_lambda.types.error_object

        out["Error"] = aws_sdk_lambda.types.error_object.serialize_json(value["error"])
    return out


def deserialize_json(data: dict) -> CallbackDetails:
    out: CallbackDetails = {}  # type: ignore[typeddict-item]
    if "CallbackId" in data:
        out["callback_id"] = data["CallbackId"]
    if "Result" in data:
        out["result"] = data["Result"]
    if "Error" in data:
        import aws_sdk_lambda.types.error_object

        out["error"] = aws_sdk_lambda.types.error_object.deserialize_json(data["Error"])
    return out
