"""Generated from Smithy shape ``com.amazonaws.ivschat#DeleteMessageResponse``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import aws_sdk_ivschat.types.id


class DeleteMessageResponse(TypedDict, closed=True):
    id: NotRequired["aws_sdk_ivschat.types.id.ID"]
    """<p>Operation identifier, generated by Amazon IVS Chat.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: DeleteMessageResponse) -> dict:
    out: dict = {}
    if "id" in value:
        out["id"] = value["id"]
    return out


def deserialize_json(data: dict) -> DeleteMessageResponse:
    out: DeleteMessageResponse = {}  # type: ignore[typeddict-item]
    if "id" in data:
        out["id"] = data["id"]
    return out
