"""Generated from Smithy shape ``com.amazonaws.ivschat#SendEventResponse``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

if TYPE_CHECKING:
    import aws_sdk_ivschat.types.id


class SendEventResponse(TypedDict):
    id: NotRequired["aws_sdk_ivschat.types.id.ID"]
    """<p>An identifier generated by Amazon IVS Chat. This identifier must be used in subsequent operations for this message, such as DeleteMessage.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: SendEventResponse) -> dict:
    out: dict = {}
    if "id" in value:
        out["id"] = value["id"]
    return out


def deserialize_json(data: dict) -> SendEventResponse:
    out: SendEventResponse = {}  # type: ignore[typeddict-item]
    if "id" in data:
        out["id"] = data["id"]
    return out
