"""Generated from Smithy shape ``com.amazonaws.trustedadvisor#OrganizationRecommendationSummary``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_trustedadvisor.errors import DeserializationError

if TYPE_CHECKING:
    import datetime

    import capo_trustedadvisor.types.organization_recommendation_arn
    import capo_trustedadvisor.types.recommendation_aws_service_list
    import capo_trustedadvisor.types.recommendation_lifecycle_stage
    import capo_trustedadvisor.types.recommendation_pillar_list
    import capo_trustedadvisor.types.recommendation_pillar_specific_aggregates
    import capo_trustedadvisor.types.recommendation_resources_aggregates
    import capo_trustedadvisor.types.recommendation_source
    import capo_trustedadvisor.types.recommendation_status
    import capo_trustedadvisor.types.recommendation_type


class OrganizationRecommendationSummary(TypedDict, closed=True):
    id: "str"
    """<p>The ID which identifies where the Recommendation was produced</p>"""
    type: "capo_trustedadvisor.types.recommendation_type.RecommendationType"
    """<p>Whether the Recommendation was automated or generated by AWS Trusted Advisor Priority</p>"""
    check_arn: NotRequired["str"]
    """<p>The AWS Trusted Advisor Check ARN that relates to the Recommendation</p>"""
    status: "capo_trustedadvisor.types.recommendation_status.RecommendationStatus"
    """<p>The status of the Recommendation</p>"""
    lifecycle_stage: NotRequired[
        "capo_trustedadvisor.types.recommendation_lifecycle_stage.RecommendationLifecycleStage"
    ]
    """<p>The lifecycle stage from AWS Trusted Advisor Priority</p>"""
    pillars: (
        "capo_trustedadvisor.types.recommendation_pillar_list.RecommendationPillarList"
    )
    """<p>The Pillars that the Recommendation is optimizing</p>"""
    source: "capo_trustedadvisor.types.recommendation_source.RecommendationSource"
    """<p>The source of the Recommendation</p>"""
    aws_services: NotRequired[
        "capo_trustedadvisor.types.recommendation_aws_service_list.RecommendationAwsServiceList"
    ]
    """<p>The AWS Services that the Recommendation applies to</p>"""
    name: "str"
    """<p>The name of the AWS Trusted Advisor Recommendation</p>"""
    resources_aggregates: "capo_trustedadvisor.types.recommendation_resources_aggregates.RecommendationResourcesAggregates"
    """<p>An aggregation of all resources</p>"""
    pillar_specific_aggregates: NotRequired[
        "capo_trustedadvisor.types.recommendation_pillar_specific_aggregates.RecommendationPillarSpecificAggregates"
    ]
    """<p>The pillar aggregations for cost savings</p>"""
    created_at: NotRequired["datetime.datetime"]
    """<p>When the Recommendation was created, if created by AWS Trusted Advisor Priority</p>"""
    last_updated_at: NotRequired["datetime.datetime"]
    """<p>When the Recommendation was last updated</p>"""
    arn: "capo_trustedadvisor.types.organization_recommendation_arn.OrganizationRecommendationArn"
    """<p>The ARN of the Recommendation</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: OrganizationRecommendationSummary) -> dict:
    out: dict = {}
    out["id"] = value["id"]
    import capo_trustedadvisor.types.recommendation_type

    out["type"] = capo_trustedadvisor.types.recommendation_type.serialize_json(
        value["type"]
    )
    if "check_arn" in value:
        out["checkArn"] = value["check_arn"]
    import capo_trustedadvisor.types.recommendation_status

    out["status"] = capo_trustedadvisor.types.recommendation_status.serialize_json(
        value["status"]
    )
    if "lifecycle_stage" in value:
        import capo_trustedadvisor.types.recommendation_lifecycle_stage

        out["lifecycleStage"] = (
            capo_trustedadvisor.types.recommendation_lifecycle_stage.serialize_json(
                value["lifecycle_stage"]
            )
        )
    import capo_trustedadvisor.types.recommendation_pillar_list

    out["pillars"] = (
        capo_trustedadvisor.types.recommendation_pillar_list.serialize_json(
            value["pillars"]
        )
    )
    import capo_trustedadvisor.types.recommendation_source

    out["source"] = capo_trustedadvisor.types.recommendation_source.serialize_json(
        value["source"]
    )
    if "aws_services" in value:
        import capo_trustedadvisor.types.recommendation_aws_service_list

        out["awsServices"] = (
            capo_trustedadvisor.types.recommendation_aws_service_list.serialize_json(
                value["aws_services"]
            )
        )
    out["name"] = value["name"]
    import capo_trustedadvisor.types.recommendation_resources_aggregates

    out["resourcesAggregates"] = (
        capo_trustedadvisor.types.recommendation_resources_aggregates.serialize_json(
            value["resources_aggregates"]
        )
    )
    if "pillar_specific_aggregates" in value:
        import capo_trustedadvisor.types.recommendation_pillar_specific_aggregates

        out["pillarSpecificAggregates"] = (
            capo_trustedadvisor.types.recommendation_pillar_specific_aggregates.serialize_json(
                value["pillar_specific_aggregates"]
            )
        )
    if "created_at" in value:
        import capo_trustedadvisor.types._prelude.timestamp

        out["createdAt"] = capo_trustedadvisor.types._prelude.timestamp.serialize_json(
            value["created_at"]
        )
    if "last_updated_at" in value:
        import capo_trustedadvisor.types._prelude.timestamp

        out["lastUpdatedAt"] = (
            capo_trustedadvisor.types._prelude.timestamp.serialize_json(
                value["last_updated_at"]
            )
        )
    out["arn"] = value["arn"]
    return out


def deserialize_json(data: dict) -> OrganizationRecommendationSummary:
    out: OrganizationRecommendationSummary = {}  # type: ignore[typeddict-item]
    if "id" in data:
        out["id"] = data["id"]
    else:
        raise DeserializationError("OrganizationRecommendationSummary.id required")
    if "type" in data:
        import capo_trustedadvisor.types.recommendation_type

        out["type"] = capo_trustedadvisor.types.recommendation_type.deserialize_json(
            data["type"]
        )
    else:
        raise DeserializationError("OrganizationRecommendationSummary.type required")
    if "checkArn" in data:
        out["check_arn"] = data["checkArn"]
    if "status" in data:
        import capo_trustedadvisor.types.recommendation_status

        out["status"] = (
            capo_trustedadvisor.types.recommendation_status.deserialize_json(
                data["status"]
            )
        )
    else:
        raise DeserializationError("OrganizationRecommendationSummary.status required")
    if "lifecycleStage" in data:
        import capo_trustedadvisor.types.recommendation_lifecycle_stage

        out["lifecycle_stage"] = (
            capo_trustedadvisor.types.recommendation_lifecycle_stage.deserialize_json(
                data["lifecycleStage"]
            )
        )
    if "pillars" in data:
        import capo_trustedadvisor.types.recommendation_pillar_list

        out["pillars"] = (
            capo_trustedadvisor.types.recommendation_pillar_list.deserialize_json(
                data["pillars"]
            )
        )
    else:
        raise DeserializationError("OrganizationRecommendationSummary.pillars required")
    if "source" in data:
        import capo_trustedadvisor.types.recommendation_source

        out["source"] = (
            capo_trustedadvisor.types.recommendation_source.deserialize_json(
                data["source"]
            )
        )
    else:
        raise DeserializationError("OrganizationRecommendationSummary.source required")
    if "awsServices" in data:
        import capo_trustedadvisor.types.recommendation_aws_service_list

        out["aws_services"] = (
            capo_trustedadvisor.types.recommendation_aws_service_list.deserialize_json(
                data["awsServices"]
            )
        )
    if "name" in data:
        out["name"] = data["name"]
    else:
        raise DeserializationError("OrganizationRecommendationSummary.name required")
    if "resourcesAggregates" in data:
        import capo_trustedadvisor.types.recommendation_resources_aggregates

        out["resources_aggregates"] = (
            capo_trustedadvisor.types.recommendation_resources_aggregates.deserialize_json(
                data["resourcesAggregates"]
            )
        )
    else:
        raise DeserializationError(
            "OrganizationRecommendationSummary.resources_aggregates required"
        )
    if "pillarSpecificAggregates" in data:
        import capo_trustedadvisor.types.recommendation_pillar_specific_aggregates

        out["pillar_specific_aggregates"] = (
            capo_trustedadvisor.types.recommendation_pillar_specific_aggregates.deserialize_json(
                data["pillarSpecificAggregates"]
            )
        )
    if "createdAt" in data:
        import capo_trustedadvisor.types._prelude.timestamp

        out["created_at"] = (
            capo_trustedadvisor.types._prelude.timestamp.deserialize_json(
                data["createdAt"]
            )
        )
    if "lastUpdatedAt" in data:
        import capo_trustedadvisor.types._prelude.timestamp

        out["last_updated_at"] = (
            capo_trustedadvisor.types._prelude.timestamp.deserialize_json(
                data["lastUpdatedAt"]
            )
        )
    if "arn" in data:
        out["arn"] = data["arn"]
    else:
        raise DeserializationError("OrganizationRecommendationSummary.arn required")
    return out
