"""Generated from Smithy shape ``com.amazonaws.m2#ClientToken``."""

from typing import TypeAlias

"""A client token is a unique, case-sensitive string of up to 128 ASCII characters with ASCII values of 33-126 inclusive. It is generated by the client to ensure idempotent operations, allowing safe retries without unintended side effects."""
ClientToken: TypeAlias = str
