"""Generated from Smithy shape ``com.amazonaws.m2#CreateApplicationRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_m2.errors import DeserializationError

if TYPE_CHECKING:
    import capo_m2.types.arn
    import capo_m2.types.client_token
    import capo_m2.types.definition
    import capo_m2.types.engine_type
    import capo_m2.types.entity_description
    import capo_m2.types.entity_name
    import capo_m2.types.tag_map


class CreateApplicationRequest(TypedDict, closed=True):
    name: "capo_m2.types.entity_name.EntityName"
    """<p>The unique identifier of the application.</p>"""
    description: NotRequired["capo_m2.types.entity_description.EntityDescription"]
    """<p>The description of the application.</p>"""
    engine_type: "capo_m2.types.engine_type.EngineType"
    """<p>The type of the target platform for this application.</p>"""
    definition: "capo_m2.types.definition.Definition"
    """<p>The application definition for this application. You can specify either inline JSON or an S3 bucket location.</p>"""
    tags: NotRequired["capo_m2.types.tag_map.TagMap"]
    """<p>A list of tags to apply to the application.</p>"""
    client_token: NotRequired["capo_m2.types.client_token.ClientToken"]
    """<p>A client token is a unique, case-sensitive string of up to 128 ASCII characters with ASCII values of 33-126 inclusive. It's generated by the client to ensure idempotent operations, allowing for safe retries without unintended side effects.</p>"""
    kms_key_id: NotRequired["str"]
    """<p>The identifier of a customer managed key.</p>"""
    role_arn: NotRequired["capo_m2.types.arn.Arn"]
    """<p>The Amazon Resource Name (ARN) that identifies a role that the application uses to access Amazon Web Services resources that are not part of the application or are in a different Amazon Web Services account.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: CreateApplicationRequest) -> dict:
    out: dict = {}
    out["name"] = value["name"]
    if "description" in value:
        out["description"] = value["description"]
    out["engineType"] = value["engine_type"]
    import capo_m2.types.definition

    out["definition"] = capo_m2.types.definition.serialize_json(value["definition"])
    if "tags" in value:
        import capo_m2.types.tag_map

        out["tags"] = capo_m2.types.tag_map.serialize_json(value["tags"])
    if "client_token" in value:
        out["clientToken"] = value["client_token"]
    if "kms_key_id" in value:
        out["kmsKeyId"] = value["kms_key_id"]
    if "role_arn" in value:
        out["roleArn"] = value["role_arn"]
    return out


def deserialize_json(data: dict) -> CreateApplicationRequest:
    out: CreateApplicationRequest = {}  # type: ignore[typeddict-item]
    if "name" in data:
        out["name"] = data["name"]
    else:
        raise DeserializationError("CreateApplicationRequest.name required")
    if "description" in data:
        out["description"] = data["description"]
    if "engineType" in data:
        out["engine_type"] = data["engineType"]
    else:
        raise DeserializationError("CreateApplicationRequest.engine_type required")
    if "definition" in data:
        import capo_m2.types.definition

        out["definition"] = capo_m2.types.definition.deserialize_json(
            data["definition"]
        )
    else:
        raise DeserializationError("CreateApplicationRequest.definition required")
    if "tags" in data:
        import capo_m2.types.tag_map

        out["tags"] = capo_m2.types.tag_map.deserialize_json(data["tags"])
    if "clientToken" in data:
        out["client_token"] = data["clientToken"]
    if "kmsKeyId" in data:
        out["kms_key_id"] = data["kmsKeyId"]
    if "roleArn" in data:
        out["role_arn"] = data["roleArn"]
    return out
