"""Generated from Smithy shape ``com.amazonaws.workspacesweb#CreateBrowserSettingsRequest``."""

from typing import TYPE_CHECKING, TypedDict
from typing_extensions import NotRequired
if TYPE_CHECKING:
    import aws_sdk_workspaces_web.types.browser_policy
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.encryption_context_map
    import aws_sdk_workspaces_web.types.key_arn
    import aws_sdk_workspaces_web.types.tag_list
    import aws_sdk_workspaces_web.types.web_content_filtering_policy

class CreateBrowserSettingsRequest(TypedDict):
    tags: NotRequired["aws_sdk_workspaces_web.types.tag_list.TagList"]
    """<p>The tags to add to the browser settings resource. A tag is a key-value pair.</p>"""
    customer_managed_key: NotRequired["aws_sdk_workspaces_web.types.key_arn.keyArn"]
    """<p>The custom managed key of the browser settings.</p>"""
    additional_encryption_context: NotRequired["aws_sdk_workspaces_web.types.encryption_context_map.EncryptionContextMap"]
    """<p>Additional encryption context of the browser settings.</p>"""
    browser_policy: NotRequired["aws_sdk_workspaces_web.types.browser_policy.BrowserPolicy"]
    """<p>A JSON string containing Chrome Enterprise policies that will be applied to all streaming sessions.</p>"""
    client_token: NotRequired["aws_sdk_workspaces_web.types.client_token.ClientToken"]
    """<p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request.</p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK. </p>"""
    web_content_filtering_policy: NotRequired["aws_sdk_workspaces_web.types.web_content_filtering_policy.WebContentFilteringPolicy"]
    """<p>The policy that specifies which URLs end users are allowed to access or which URLs or domain categories they are restricted from accessing for enhanced security.</p>"""

# --- restJson1 ser/de ---
def serialize_json(value: CreateBrowserSettingsRequest) -> dict:
    out: dict = {}
    if "tags" in value:
        import aws_sdk_workspaces_web.types.tag_list
        out["tags"] = aws_sdk_workspaces_web.types.tag_list.serialize_json(value["tags"])
    if "customer_managed_key" in value:
        out["customerManagedKey"] = value["customer_managed_key"]
    if "additional_encryption_context" in value:
        import aws_sdk_workspaces_web.types.encryption_context_map
        out["additionalEncryptionContext"] = aws_sdk_workspaces_web.types.encryption_context_map.serialize_json(value["additional_encryption_context"])
    if "browser_policy" in value:
        out["browserPolicy"] = value["browser_policy"]
    if "client_token" in value:
        out["clientToken"] = value["client_token"]
    if "web_content_filtering_policy" in value:
        import aws_sdk_workspaces_web.types.web_content_filtering_policy
        out["webContentFilteringPolicy"] = aws_sdk_workspaces_web.types.web_content_filtering_policy.serialize_json(value["web_content_filtering_policy"])
    return out


def deserialize_json(data: dict) -> CreateBrowserSettingsRequest:
    out: CreateBrowserSettingsRequest = {}  # type: ignore[typeddict-item]
    if "tags" in data:
        import aws_sdk_workspaces_web.types.tag_list
        out["tags"] = aws_sdk_workspaces_web.types.tag_list.deserialize_json(data["tags"])
    if "customerManagedKey" in data:
        out["customer_managed_key"] = data["customerManagedKey"]
    if "additionalEncryptionContext" in data:
        import aws_sdk_workspaces_web.types.encryption_context_map
        out["additional_encryption_context"] = aws_sdk_workspaces_web.types.encryption_context_map.deserialize_json(data["additionalEncryptionContext"])
    if "browserPolicy" in data:
        out["browser_policy"] = data["browserPolicy"]
    if "clientToken" in data:
        out["client_token"] = data["clientToken"]
    if "webContentFilteringPolicy" in data:
        import aws_sdk_workspaces_web.types.web_content_filtering_policy
        out["web_content_filtering_policy"] = aws_sdk_workspaces_web.types.web_content_filtering_policy.deserialize_json(data["webContentFilteringPolicy"])
    return out