"""Generated from Smithy shape ``com.amazonaws.workspacesweb#UpdateDataProtectionSettingsRequest``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

if TYPE_CHECKING:
    import aws_sdk_workspaces_web.types.arn
    import aws_sdk_workspaces_web.types.client_token
    import aws_sdk_workspaces_web.types.description_safe
    import aws_sdk_workspaces_web.types.display_name_safe
    import aws_sdk_workspaces_web.types.inline_redaction_configuration


class UpdateDataProtectionSettingsRequest(TypedDict):
    data_protection_settings_arn: "aws_sdk_workspaces_web.types.arn.ARN"
    """<p>The ARN of the data protection settings.</p>"""
    inline_redaction_configuration: NotRequired[
        "aws_sdk_workspaces_web.types.inline_redaction_configuration.InlineRedactionConfiguration"
    ]
    """<p>The inline redaction configuration of the data protection settings that will be applied to all sessions.</p>"""
    display_name: NotRequired[
        "aws_sdk_workspaces_web.types.display_name_safe.DisplayNameSafe"
    ]
    """<p>The display name of the data protection settings.</p>"""
    description: NotRequired[
        "aws_sdk_workspaces_web.types.description_safe.DescriptionSafe"
    ]
    """<p>The description of the data protection settings.</p>"""
    client_token: NotRequired["aws_sdk_workspaces_web.types.client_token.ClientToken"]
    """<p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token return the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: UpdateDataProtectionSettingsRequest) -> dict:
    out: dict = {}
    if "inline_redaction_configuration" in value:
        import aws_sdk_workspaces_web.types.inline_redaction_configuration

        out["inlineRedactionConfiguration"] = (
            aws_sdk_workspaces_web.types.inline_redaction_configuration.serialize_json(
                value["inline_redaction_configuration"]
            )
        )
    if "display_name" in value:
        out["displayName"] = value["display_name"]
    if "description" in value:
        out["description"] = value["description"]
    if "client_token" in value:
        out["clientToken"] = value["client_token"]
    return out


def deserialize_json(data: dict) -> UpdateDataProtectionSettingsRequest:
    out: UpdateDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
    if "inlineRedactionConfiguration" in data:
        import aws_sdk_workspaces_web.types.inline_redaction_configuration

        out["inline_redaction_configuration"] = (
            aws_sdk_workspaces_web.types.inline_redaction_configuration.deserialize_json(
                data["inlineRedactionConfiguration"]
            )
        )
    if "displayName" in data:
        out["display_name"] = data["displayName"]
    if "description" in data:
        out["description"] = data["description"]
    if "clientToken" in data:
        out["client_token"] = data["clientToken"]
    return out
