"""Generated from Smithy shape ``com.amazonaws.identitystore#ThrottlingException``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_identitystore.errors import ServiceError

if TYPE_CHECKING:
    import capo_identitystore.types.exception_message
    import capo_identitystore.types.request_id
    import capo_identitystore.types.retry_after_seconds
    import capo_identitystore.types.throttling_exception_reason


class ThrottlingException_(TypedDict, closed=True):
    message: NotRequired["capo_identitystore.types.exception_message.ExceptionMessage"]
    request_id: NotRequired["capo_identitystore.types.request_id.RequestId"]
    """<p>The identifier for each request. This value is a globally unique ID that is generated by the identity store service for each sent request, and is then returned inside the exception if the request fails.</p>"""
    retry_after_seconds: (
        "capo_identitystore.types.retry_after_seconds.RetryAfterSeconds"
    )
    """<p>The number of seconds to wait before retrying the next request.</p>"""
    reason: NotRequired[
        "capo_identitystore.types.throttling_exception_reason.ThrottlingExceptionReason"
    ]
    """<p>Indicates the reason for the throttling error when the service is unable to access a Customer Managed KMS key. For non-KMS permission errors, this field is not included.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ThrottlingException_) -> dict:
    out: dict = {}
    if "message" in value:
        out["Message"] = value["message"]
    if "request_id" in value:
        out["RequestId"] = value["request_id"]
    if "reason" in value:
        import capo_identitystore.types.throttling_exception_reason

        out["Reason"] = (
            capo_identitystore.types.throttling_exception_reason.serialize_aws_json_1_1(
                value["reason"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> ThrottlingException_:
    out: ThrottlingException_ = {}  # type: ignore[typeddict-item]
    if "Message" in data:
        out["message"] = data["Message"]
    if "RequestId" in data:
        out["request_id"] = data["RequestId"]
    if "Reason" in data:
        import capo_identitystore.types.throttling_exception_reason

        out["reason"] = (
            capo_identitystore.types.throttling_exception_reason.deserialize_aws_json_1_1(
                data["Reason"]
            )
        )
    return out


class ThrottlingException(ServiceError):
    """Modeled error for Smithy shape ``com.amazonaws.identitystore#ThrottlingException``."""

    code: str | None = "ThrottlingException"

    def __init__(self, data: ThrottlingException_):
        super().__init__(
            "client",
            is_throttling_error=True,
            is_retryable=True,
            code="ThrottlingException",
        )
        self.data = data

    @classmethod
    def from_aws_json_1_1(cls, data: dict) -> "ThrottlingException":
        return cls(deserialize_aws_json_1_1(data))
