"""Generated from Smithy shape ``com.amazonaws.athena#ListApplicationDPUSizesInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_athena.types.max_application_dpu_sizes_count
    import capo_athena.types.token


class ListApplicationDPUSizesInput(TypedDict, closed=True):
    max_results: NotRequired[
        "capo_athena.types.max_application_dpu_sizes_count.MaxApplicationDPUSizesCount"
    ]
    """<p>Specifies the maximum number of results to return.</p>"""
    next_token: NotRequired["capo_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListApplicationDPUSizesInput) -> dict:
    out: dict = {}
    if "max_results" in value:
        out["MaxResults"] = value["max_results"]
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListApplicationDPUSizesInput:
    out: ListApplicationDPUSizesInput = {}  # type: ignore[typeddict-item]
    if "MaxResults" in data:
        out["max_results"] = data["MaxResults"]
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    return out
