"""Generated from Smithy shape ``com.amazonaws.athena#ListPreparedStatementsOutput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_athena.types.prepared_statements_list
    import capo_athena.types.token


class ListPreparedStatementsOutput(TypedDict, closed=True):
    prepared_statements: NotRequired[
        "capo_athena.types.prepared_statements_list.PreparedStatementsList"
    ]
    """<p>The list of prepared statements for the workgroup.</p>"""
    next_token: NotRequired["capo_athena.types.token.Token"]
    """<p>A token generated by the Athena service that specifies where to continue pagination if a previous request was truncated. To obtain the next set of pages, pass in the <code>NextToken</code> from the response object of the previous page call.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListPreparedStatementsOutput) -> dict:
    out: dict = {}
    if "prepared_statements" in value:
        import capo_athena.types.prepared_statements_list

        out["PreparedStatements"] = (
            capo_athena.types.prepared_statements_list.serialize_aws_json_1_1(
                value["prepared_statements"]
            )
        )
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListPreparedStatementsOutput:
    out: ListPreparedStatementsOutput = {}  # type: ignore[typeddict-item]
    if "PreparedStatements" in data:
        import capo_athena.types.prepared_statements_list

        out["prepared_statements"] = (
            capo_athena.types.prepared_statements_list.deserialize_aws_json_1_1(
                data["PreparedStatements"]
            )
        )
    if "NextToken" in data:
        out["next_token"] = data["NextToken"]
    return out
