"""Generated from Smithy shape ``com.amazonaws.inspector#CreateAssessmentTemplateRequest``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

from aws_sdk_inspector.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_inspector.types.arn
    import aws_sdk_inspector.types.assessment_run_duration
    import aws_sdk_inspector.types.assessment_template_name
    import aws_sdk_inspector.types.assessment_template_rules_package_arn_list
    import aws_sdk_inspector.types.user_attribute_list


class CreateAssessmentTemplateRequest(TypedDict):
    assessment_target_arn: "aws_sdk_inspector.types.arn.Arn"
    """<p>The ARN that specifies the assessment target for which you want to create the assessment template.</p>"""
    assessment_template_name: (
        "aws_sdk_inspector.types.assessment_template_name.AssessmentTemplateName"
    )
    """<p>The user-defined name that identifies the assessment template that you want to create. You can create several assessment templates for an assessment target. The names of the assessment templates that correspond to a particular assessment target must be unique.</p>"""
    duration_in_seconds: (
        "aws_sdk_inspector.types.assessment_run_duration.AssessmentRunDuration"
    )
    """<p>The duration of the assessment run in seconds.</p>"""
    rules_package_arns: "aws_sdk_inspector.types.assessment_template_rules_package_arn_list.AssessmentTemplateRulesPackageArnList"
    """<p>The ARNs that specify the rules packages that you want to attach to the assessment template.</p>"""
    user_attributes_for_findings: NotRequired[
        "aws_sdk_inspector.types.user_attribute_list.UserAttributeList"
    ]
    """<p>The user-defined attributes that are assigned to every finding that is generated by the assessment run that uses this assessment template. An attribute is a key and value pair (an <a>Attribute</a> object). Within an assessment template, each key must be unique.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: CreateAssessmentTemplateRequest) -> dict:
    out: dict = {}
    out["assessmentTargetArn"] = value["assessment_target_arn"]
    out["assessmentTemplateName"] = value["assessment_template_name"]
    out["durationInSeconds"] = value["duration_in_seconds"]
    import aws_sdk_inspector.types.assessment_template_rules_package_arn_list

    out["rulesPackageArns"] = (
        aws_sdk_inspector.types.assessment_template_rules_package_arn_list.serialize_aws_json_1_1(
            value["rules_package_arns"]
        )
    )
    if "user_attributes_for_findings" in value:
        import aws_sdk_inspector.types.user_attribute_list

        out["userAttributesForFindings"] = (
            aws_sdk_inspector.types.user_attribute_list.serialize_aws_json_1_1(
                value["user_attributes_for_findings"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> CreateAssessmentTemplateRequest:
    out: CreateAssessmentTemplateRequest = {}  # type: ignore[typeddict-item]
    if "assessmentTargetArn" in data:
        out["assessment_target_arn"] = data["assessmentTargetArn"]
    else:
        raise DeserializationError(
            "CreateAssessmentTemplateRequest.assessment_target_arn required"
        )
    if "assessmentTemplateName" in data:
        out["assessment_template_name"] = data["assessmentTemplateName"]
    else:
        raise DeserializationError(
            "CreateAssessmentTemplateRequest.assessment_template_name required"
        )
    if "durationInSeconds" in data:
        out["duration_in_seconds"] = data["durationInSeconds"]
    else:
        raise DeserializationError(
            "CreateAssessmentTemplateRequest.duration_in_seconds required"
        )
    if "rulesPackageArns" in data:
        import aws_sdk_inspector.types.assessment_template_rules_package_arn_list

        out["rules_package_arns"] = (
            aws_sdk_inspector.types.assessment_template_rules_package_arn_list.deserialize_aws_json_1_1(
                data["rulesPackageArns"]
            )
        )
    else:
        raise DeserializationError(
            "CreateAssessmentTemplateRequest.rules_package_arns required"
        )
    if "userAttributesForFindings" in data:
        import aws_sdk_inspector.types.user_attribute_list

        out["user_attributes_for_findings"] = (
            aws_sdk_inspector.types.user_attribute_list.deserialize_aws_json_1_1(
                data["userAttributesForFindings"]
            )
        )
    return out
