"""Generated from Smithy shape ``com.amazonaws.finspace#ListEnvironmentsRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_finspace.types.pagination_token
    import capo_finspace.types.result_limit


class ListEnvironmentsRequest(TypedDict, closed=True):
    next_token: NotRequired["capo_finspace.types.pagination_token.PaginationToken"]
    """<p>A token generated by FinSpace that specifies where to continue pagination if a previous request was truncated. To get the next set of pages, pass in the <code>nextToken</code>nextToken value from the response object of the previous page call.</p>"""
    max_results: "capo_finspace.types.result_limit.ResultLimit"
    """<p>The maximum number of results to return in this request.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ListEnvironmentsRequest) -> dict:
    out: dict = {}
    return out


def deserialize_json(data: dict) -> ListEnvironmentsRequest:
    out: ListEnvironmentsRequest = {}  # type: ignore[typeddict-item]
    return out
