"""Generated from Smithy shape ``com.amazonaws.bedrockagentcorecontrol#EpisodicMemoryStrategyInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_bedrock_agentcore_control.errors import DeserializationError

if TYPE_CHECKING:
    import capo_bedrock_agentcore_control.types.description
    import capo_bedrock_agentcore_control.types.episodic_reflection_configuration_input
    import capo_bedrock_agentcore_control.types.memory_record_schema
    import capo_bedrock_agentcore_control.types.name
    import capo_bedrock_agentcore_control.types.namespaces_list


class EpisodicMemoryStrategyInput(TypedDict, closed=True):
    name: "capo_bedrock_agentcore_control.types.name.Name"
    """<p>The name of the episodic memory strategy.</p>"""
    description: NotRequired[
        "capo_bedrock_agentcore_control.types.description.Description"
    ]
    """<p>The description of the episodic memory strategy.</p>"""
    namespaces: NotRequired[
        "capo_bedrock_agentcore_control.types.namespaces_list.NamespacesList"
    ]
    """<p>This is a legacy parameter, use <code>namespaceTemplates</code>. The namespaces for which to create episodes.</p>"""
    namespace_templates: NotRequired[
        "capo_bedrock_agentcore_control.types.namespaces_list.NamespacesList"
    ]
    """<p>The namespaceTemplates for which to create episodes.</p>"""
    reflection_configuration: NotRequired[
        "capo_bedrock_agentcore_control.types.episodic_reflection_configuration_input.EpisodicReflectionConfigurationInput"
    ]
    """<p>The configuration for the reflections created with the episodic memory strategy.</p>"""
    memory_record_schema: NotRequired[
        "capo_bedrock_agentcore_control.types.memory_record_schema.MemoryRecordSchema"
    ]
    """<p>Schema for metadata fields on records generated by this strategy.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: EpisodicMemoryStrategyInput) -> dict:
    out: dict = {}
    out["name"] = value["name"]
    if "description" in value:
        out["description"] = value["description"]
    if "namespaces" in value:
        import capo_bedrock_agentcore_control.types.namespaces_list

        out["namespaces"] = (
            capo_bedrock_agentcore_control.types.namespaces_list.serialize_json(
                value["namespaces"]
            )
        )
    if "namespace_templates" in value:
        import capo_bedrock_agentcore_control.types.namespaces_list

        out["namespaceTemplates"] = (
            capo_bedrock_agentcore_control.types.namespaces_list.serialize_json(
                value["namespace_templates"]
            )
        )
    if "reflection_configuration" in value:
        import capo_bedrock_agentcore_control.types.episodic_reflection_configuration_input

        out["reflectionConfiguration"] = (
            capo_bedrock_agentcore_control.types.episodic_reflection_configuration_input.serialize_json(
                value["reflection_configuration"]
            )
        )
    if "memory_record_schema" in value:
        import capo_bedrock_agentcore_control.types.memory_record_schema

        out["memoryRecordSchema"] = (
            capo_bedrock_agentcore_control.types.memory_record_schema.serialize_json(
                value["memory_record_schema"]
            )
        )
    return out


def deserialize_json(data: dict) -> EpisodicMemoryStrategyInput:
    out: EpisodicMemoryStrategyInput = {}  # type: ignore[typeddict-item]
    if data.get("name") is not None:
        out["name"] = data["name"]
    else:
        raise DeserializationError("EpisodicMemoryStrategyInput.name required")
    if data.get("description") is not None:
        out["description"] = data["description"]
    if data.get("namespaces") is not None:
        import capo_bedrock_agentcore_control.types.namespaces_list

        out["namespaces"] = (
            capo_bedrock_agentcore_control.types.namespaces_list.deserialize_json(
                data["namespaces"]
            )
        )
    if data.get("namespaceTemplates") is not None:
        import capo_bedrock_agentcore_control.types.namespaces_list

        out["namespace_templates"] = (
            capo_bedrock_agentcore_control.types.namespaces_list.deserialize_json(
                data["namespaceTemplates"]
            )
        )
    if data.get("reflectionConfiguration") is not None:
        import capo_bedrock_agentcore_control.types.episodic_reflection_configuration_input

        out["reflection_configuration"] = (
            capo_bedrock_agentcore_control.types.episodic_reflection_configuration_input.deserialize_json(
                data["reflectionConfiguration"]
            )
        )
    if data.get("memoryRecordSchema") is not None:
        import capo_bedrock_agentcore_control.types.memory_record_schema

        out["memory_record_schema"] = (
            capo_bedrock_agentcore_control.types.memory_record_schema.deserialize_json(
                data["memoryRecordSchema"]
            )
        )
    return out
