"""Generated from Smithy shape ``com.amazonaws.backup#DescribeScanJobOutput``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

from aws_sdk_backup.errors import DeserializationError

if TYPE_CHECKING:
    import datetime

    import aws_sdk_backup.types.malware_scanner
    import aws_sdk_backup.types.scan_job_creator
    import aws_sdk_backup.types.scan_mode
    import aws_sdk_backup.types.scan_resource_type
    import aws_sdk_backup.types.scan_result_info
    import aws_sdk_backup.types.scan_state


class DescribeScanJobOutput(TypedDict):
    account_id: "str"
    """<p>Returns the account ID that owns the scan job.</p> <p>Pattern: <code>^[0-9]{12}$</code> </p>"""
    backup_vault_arn: "str"
    """<p>An Amazon Resource Name (ARN) that uniquely identifies a backup vault; for example, <code>arn:aws:backup:us-east-1:123456789012:backup-vault:aBackupVault</code> </p>"""
    backup_vault_name: "str"
    """<p>The name of a logical container where backups are stored. Backup vaults are identified by names that are unique to the account used to create them and the Amazon Web Services Region where they are created.</p> <p>Pattern: <code>^[a-zA-Z0-9\-\_\.]{2,50}$</code> </p>"""
    completion_date: NotRequired["datetime.datetime"]
    """<p>The date and time that a backup index finished creation, in Unix format and Coordinated Universal Time (UTC). The value of <code>CompletionDate</code> is accurate to milliseconds. For example, the value 1516925490.087 represents Friday, January 26, 2018 12:11:30.087 AM.</p>"""
    continuous_scan_end_time: NotRequired["datetime.datetime"]
    """<p>The point in time the scan job scanned up to for a continuous backup.</p>"""
    continuous_scan_start_time: NotRequired["datetime.datetime"]
    """<p>The point in time the scan job started scan from for a continuous backup.</p>"""
    created_by: "aws_sdk_backup.types.scan_job_creator.ScanJobCreator"
    creation_date: "datetime.datetime"
    """<p>The date and time that a backup index finished creation, in Unix format and Coordinated Universal Time (UTC). The value of <code>CreationDate</code> is accurate to milliseconds. For example, the value 1516925490.087 represents Friday, January 26, 2018 12:11:30.087 AM.</p>"""
    iam_role_arn: "str"
    """<p>An Amazon Resource Name (ARN) that uniquely identifies a backup vault; for example, <code>arn:aws:iam::123456789012:role/S3Access</code>.</p>"""
    malware_scanner: "aws_sdk_backup.types.malware_scanner.MalwareScanner"
    """<p>The scanning engine used for the corresponding scan job. Currently only <code>GUARDUTY</code> is supported.</p>"""
    recovery_point_arn: "str"
    """<p>An ARN that uniquely identifies the target recovery point for scanning.; for example, <code>arn:aws:backup:us-east-1:123456789012:recovery-point:1EB3B5E7-9EB0-435A-A80B-108B488B0D45</code>.</p>"""
    resource_arn: "str"
    """<p>An ARN that uniquely identifies the source resource of the corresponding recovery point ARN.</p>"""
    resource_name: "str"
    """<p>The non-unique name of the resource that belongs to the specified backup.</p>"""
    resource_type: "aws_sdk_backup.types.scan_resource_type.ScanResourceType"
    """<p>The type of Amazon Web Services Resource to be backed up; for example, an Amazon Elastic Block Store (Amazon EBS) volume.</p> <p>Pattern: <code>^[a-zA-Z0-9\-\_\.]{1,50}$</code> </p>"""
    scan_base_recovery_point_arn: NotRequired["str"]
    """<p>An ARN that uniquely identifies the base recovery point for scanning. This field will only be populated when an incremental scan job has taken place.</p>"""
    scan_id: NotRequired["str"]
    """<p>The scan ID generated by Amazon GuardDuty for the corresponding Scan Job ID request from Backup.</p>"""
    scan_job_id: "str"
    """<p>The scan job ID that uniquely identified the request to Backup.</p>"""
    scan_mode: "aws_sdk_backup.types.scan_mode.ScanMode"
    """<p>Specifies the scan type used for the scan job.</p>"""
    scan_result: NotRequired["aws_sdk_backup.types.scan_result_info.ScanResultInfo"]
    """<p> Contains the <code>ScanResultsStatus</code> for the scanning job and returns <code>THREATS_FOUND</code> or <code>NO_THREATS_FOUND</code> for completed jobs.</p>"""
    scanner_role_arn: "str"
    """<p>Specifies the scanner IAM role ARN used to for the scan job.</p>"""
    state: "aws_sdk_backup.types.scan_state.ScanState"
    """<p>The current state of a scan job.</p>"""
    status_message: NotRequired["str"]
    """<p>A detailed message explaining the status of the job to back up a resource.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: DescribeScanJobOutput) -> dict:
    out: dict = {}
    out["AccountId"] = value["account_id"]
    out["BackupVaultArn"] = value["backup_vault_arn"]
    out["BackupVaultName"] = value["backup_vault_name"]
    if "completion_date" in value:
        import aws_sdk_backup.types._prelude.timestamp

        out["CompletionDate"] = aws_sdk_backup.types._prelude.timestamp.serialize_json(
            value["completion_date"]
        )
    if "continuous_scan_end_time" in value:
        import aws_sdk_backup.types._prelude.timestamp

        out["ContinuousScanEndTime"] = (
            aws_sdk_backup.types._prelude.timestamp.serialize_json(
                value["continuous_scan_end_time"]
            )
        )
    if "continuous_scan_start_time" in value:
        import aws_sdk_backup.types._prelude.timestamp

        out["ContinuousScanStartTime"] = (
            aws_sdk_backup.types._prelude.timestamp.serialize_json(
                value["continuous_scan_start_time"]
            )
        )
    import aws_sdk_backup.types.scan_job_creator

    out["CreatedBy"] = aws_sdk_backup.types.scan_job_creator.serialize_json(
        value["created_by"]
    )
    import aws_sdk_backup.types._prelude.timestamp

    out["CreationDate"] = aws_sdk_backup.types._prelude.timestamp.serialize_json(
        value["creation_date"]
    )
    out["IamRoleArn"] = value["iam_role_arn"]
    import aws_sdk_backup.types.malware_scanner

    out["MalwareScanner"] = aws_sdk_backup.types.malware_scanner.serialize_json(
        value["malware_scanner"]
    )
    out["RecoveryPointArn"] = value["recovery_point_arn"]
    out["ResourceArn"] = value["resource_arn"]
    out["ResourceName"] = value["resource_name"]
    import aws_sdk_backup.types.scan_resource_type

    out["ResourceType"] = aws_sdk_backup.types.scan_resource_type.serialize_json(
        value["resource_type"]
    )
    if "scan_base_recovery_point_arn" in value:
        out["ScanBaseRecoveryPointArn"] = value["scan_base_recovery_point_arn"]
    if "scan_id" in value:
        out["ScanId"] = value["scan_id"]
    out["ScanJobId"] = value["scan_job_id"]
    import aws_sdk_backup.types.scan_mode

    out["ScanMode"] = aws_sdk_backup.types.scan_mode.serialize_json(value["scan_mode"])
    if "scan_result" in value:
        import aws_sdk_backup.types.scan_result_info

        out["ScanResult"] = aws_sdk_backup.types.scan_result_info.serialize_json(
            value["scan_result"]
        )
    out["ScannerRoleArn"] = value["scanner_role_arn"]
    import aws_sdk_backup.types.scan_state

    out["State"] = aws_sdk_backup.types.scan_state.serialize_json(value["state"])
    if "status_message" in value:
        out["StatusMessage"] = value["status_message"]
    return out


def deserialize_json(data: dict) -> DescribeScanJobOutput:
    out: DescribeScanJobOutput = {}  # type: ignore[typeddict-item]
    if "AccountId" in data:
        out["account_id"] = data["AccountId"]
    else:
        raise DeserializationError("DescribeScanJobOutput.account_id required")
    if "BackupVaultArn" in data:
        out["backup_vault_arn"] = data["BackupVaultArn"]
    else:
        raise DeserializationError("DescribeScanJobOutput.backup_vault_arn required")
    if "BackupVaultName" in data:
        out["backup_vault_name"] = data["BackupVaultName"]
    else:
        raise DeserializationError("DescribeScanJobOutput.backup_vault_name required")
    if "CompletionDate" in data:
        import aws_sdk_backup.types._prelude.timestamp

        out["completion_date"] = (
            aws_sdk_backup.types._prelude.timestamp.deserialize_json(
                data["CompletionDate"]
            )
        )
    if "ContinuousScanEndTime" in data:
        import aws_sdk_backup.types._prelude.timestamp

        out["continuous_scan_end_time"] = (
            aws_sdk_backup.types._prelude.timestamp.deserialize_json(
                data["ContinuousScanEndTime"]
            )
        )
    if "ContinuousScanStartTime" in data:
        import aws_sdk_backup.types._prelude.timestamp

        out["continuous_scan_start_time"] = (
            aws_sdk_backup.types._prelude.timestamp.deserialize_json(
                data["ContinuousScanStartTime"]
            )
        )
    if "CreatedBy" in data:
        import aws_sdk_backup.types.scan_job_creator

        out["created_by"] = aws_sdk_backup.types.scan_job_creator.deserialize_json(
            data["CreatedBy"]
        )
    else:
        raise DeserializationError("DescribeScanJobOutput.created_by required")
    if "CreationDate" in data:
        import aws_sdk_backup.types._prelude.timestamp

        out["creation_date"] = aws_sdk_backup.types._prelude.timestamp.deserialize_json(
            data["CreationDate"]
        )
    else:
        raise DeserializationError("DescribeScanJobOutput.creation_date required")
    if "IamRoleArn" in data:
        out["iam_role_arn"] = data["IamRoleArn"]
    else:
        raise DeserializationError("DescribeScanJobOutput.iam_role_arn required")
    if "MalwareScanner" in data:
        import aws_sdk_backup.types.malware_scanner

        out["malware_scanner"] = aws_sdk_backup.types.malware_scanner.deserialize_json(
            data["MalwareScanner"]
        )
    else:
        raise DeserializationError("DescribeScanJobOutput.malware_scanner required")
    if "RecoveryPointArn" in data:
        out["recovery_point_arn"] = data["RecoveryPointArn"]
    else:
        raise DeserializationError("DescribeScanJobOutput.recovery_point_arn required")
    if "ResourceArn" in data:
        out["resource_arn"] = data["ResourceArn"]
    else:
        raise DeserializationError("DescribeScanJobOutput.resource_arn required")
    if "ResourceName" in data:
        out["resource_name"] = data["ResourceName"]
    else:
        raise DeserializationError("DescribeScanJobOutput.resource_name required")
    if "ResourceType" in data:
        import aws_sdk_backup.types.scan_resource_type

        out["resource_type"] = aws_sdk_backup.types.scan_resource_type.deserialize_json(
            data["ResourceType"]
        )
    else:
        raise DeserializationError("DescribeScanJobOutput.resource_type required")
    if "ScanBaseRecoveryPointArn" in data:
        out["scan_base_recovery_point_arn"] = data["ScanBaseRecoveryPointArn"]
    if "ScanId" in data:
        out["scan_id"] = data["ScanId"]
    if "ScanJobId" in data:
        out["scan_job_id"] = data["ScanJobId"]
    else:
        raise DeserializationError("DescribeScanJobOutput.scan_job_id required")
    if "ScanMode" in data:
        import aws_sdk_backup.types.scan_mode

        out["scan_mode"] = aws_sdk_backup.types.scan_mode.deserialize_json(
            data["ScanMode"]
        )
    else:
        raise DeserializationError("DescribeScanJobOutput.scan_mode required")
    if "ScanResult" in data:
        import aws_sdk_backup.types.scan_result_info

        out["scan_result"] = aws_sdk_backup.types.scan_result_info.deserialize_json(
            data["ScanResult"]
        )
    if "ScannerRoleArn" in data:
        out["scanner_role_arn"] = data["ScannerRoleArn"]
    else:
        raise DeserializationError("DescribeScanJobOutput.scanner_role_arn required")
    if "State" in data:
        import aws_sdk_backup.types.scan_state

        out["state"] = aws_sdk_backup.types.scan_state.deserialize_json(data["State"])
    else:
        raise DeserializationError("DescribeScanJobOutput.state required")
    if "StatusMessage" in data:
        out["status_message"] = data["StatusMessage"]
    return out
