"""Generated from Smithy shape ``com.amazonaws.lookoutequipment#ModelSummary``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

if TYPE_CHECKING:
    import aws_sdk_lookoutequipment.types.dataset_arn
    import aws_sdk_lookoutequipment.types.dataset_name
    import aws_sdk_lookoutequipment.types.model_arn
    import aws_sdk_lookoutequipment.types.model_diagnostics_output_configuration
    import aws_sdk_lookoutequipment.types.model_name
    import aws_sdk_lookoutequipment.types.model_quality
    import aws_sdk_lookoutequipment.types.model_status
    import aws_sdk_lookoutequipment.types.model_version
    import aws_sdk_lookoutequipment.types.model_version_arn
    import aws_sdk_lookoutequipment.types.model_version_status
    import aws_sdk_lookoutequipment.types.retraining_scheduler_status
    import aws_sdk_lookoutequipment.types.timestamp


class ModelSummary(TypedDict):
    model_name: NotRequired["aws_sdk_lookoutequipment.types.model_name.ModelName"]
    """<p>The name of the machine learning model. </p>"""
    model_arn: NotRequired["aws_sdk_lookoutequipment.types.model_arn.ModelArn"]
    """<p> The Amazon Resource Name (ARN) of the machine learning model. </p>"""
    dataset_name: NotRequired["aws_sdk_lookoutequipment.types.dataset_name.DatasetName"]
    """<p>The name of the dataset being used for the machine learning model. </p>"""
    dataset_arn: NotRequired["aws_sdk_lookoutequipment.types.dataset_arn.DatasetArn"]
    """<p> The Amazon Resource Name (ARN) of the dataset used to create the model. </p>"""
    status: NotRequired["aws_sdk_lookoutequipment.types.model_status.ModelStatus"]
    """<p>Indicates the status of the machine learning model. </p>"""
    created_at: NotRequired["aws_sdk_lookoutequipment.types.timestamp.Timestamp"]
    """<p>The time at which the specific model was created. </p>"""
    active_model_version: NotRequired[
        "aws_sdk_lookoutequipment.types.model_version.ModelVersion"
    ]
    """<p>The model version that the inference scheduler uses to run an inference execution.</p>"""
    active_model_version_arn: NotRequired[
        "aws_sdk_lookoutequipment.types.model_version_arn.ModelVersionArn"
    ]
    """<p>The Amazon Resource Name (ARN) of the model version that is set as active. The active model version is the model version that the inference scheduler uses to run an inference execution.</p>"""
    latest_scheduled_retraining_status: NotRequired[
        "aws_sdk_lookoutequipment.types.model_version_status.ModelVersionStatus"
    ]
    """<p>Indicates the status of the most recent scheduled retraining run. </p>"""
    latest_scheduled_retraining_model_version: NotRequired[
        "aws_sdk_lookoutequipment.types.model_version.ModelVersion"
    ]
    """<p>Indicates the most recent model version that was generated by retraining. </p>"""
    latest_scheduled_retraining_start_time: NotRequired[
        "aws_sdk_lookoutequipment.types.timestamp.Timestamp"
    ]
    """<p>Indicates the start time of the most recent scheduled retraining run. </p>"""
    next_scheduled_retraining_start_date: NotRequired[
        "aws_sdk_lookoutequipment.types.timestamp.Timestamp"
    ]
    """<p>Indicates the date that the next scheduled retraining run will start on. Lookout for Equipment truncates the time you provide to <a href=\"https://docs.aws.amazon.com/https:/docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-types.html#parameter-type-timestamp\">the nearest UTC day</a>.</p>"""
    retraining_scheduler_status: NotRequired[
        "aws_sdk_lookoutequipment.types.retraining_scheduler_status.RetrainingSchedulerStatus"
    ]
    """<p>Indicates the status of the retraining scheduler. </p>"""
    model_diagnostics_output_configuration: NotRequired[
        "aws_sdk_lookoutequipment.types.model_diagnostics_output_configuration.ModelDiagnosticsOutputConfiguration"
    ]
    model_quality: NotRequired[
        "aws_sdk_lookoutequipment.types.model_quality.ModelQuality"
    ]
    """<p>Provides a quality assessment for a model that uses labels. If Lookout for Equipment determines that the model quality is poor based on training metrics, the value is <code>POOR_QUALITY_DETECTED</code>. Otherwise, the value is <code>QUALITY_THRESHOLD_MET</code>.</p> <p>If the model is unlabeled, the model quality can't be assessed and the value of <code>ModelQuality</code> is <code>CANNOT_DETERMINE_QUALITY</code>. In this situation, you can get a model quality assessment by adding labels to the input dataset and retraining the model.</p> <p>For information about using labels with your models, see <a href=\"https://docs.aws.amazon.com/lookout-for-equipment/latest/ug/understanding-labeling.html\">Understanding labeling</a>.</p> <p>For information about improving the quality of a model, see <a href=\"https://docs.aws.amazon.com/lookout-for-equipment/latest/ug/best-practices.html\">Best practices with Amazon Lookout for Equipment</a>.</p>"""


# --- awsJson1_0 ser/de ---
def serialize_aws_json_1_0(value: ModelSummary) -> dict:
    out: dict = {}
    if "model_name" in value:
        out["ModelName"] = value["model_name"]
    if "model_arn" in value:
        out["ModelArn"] = value["model_arn"]
    if "dataset_name" in value:
        out["DatasetName"] = value["dataset_name"]
    if "dataset_arn" in value:
        out["DatasetArn"] = value["dataset_arn"]
    if "status" in value:
        import aws_sdk_lookoutequipment.types.model_status

        out["Status"] = (
            aws_sdk_lookoutequipment.types.model_status.serialize_aws_json_1_0(
                value["status"]
            )
        )
    if "created_at" in value:
        import aws_sdk_lookoutequipment.types.timestamp

        out["CreatedAt"] = (
            aws_sdk_lookoutequipment.types.timestamp.serialize_aws_json_1_0(
                value["created_at"]
            )
        )
    if "active_model_version" in value:
        out["ActiveModelVersion"] = value["active_model_version"]
    if "active_model_version_arn" in value:
        out["ActiveModelVersionArn"] = value["active_model_version_arn"]
    if "latest_scheduled_retraining_status" in value:
        import aws_sdk_lookoutequipment.types.model_version_status

        out["LatestScheduledRetrainingStatus"] = (
            aws_sdk_lookoutequipment.types.model_version_status.serialize_aws_json_1_0(
                value["latest_scheduled_retraining_status"]
            )
        )
    if "latest_scheduled_retraining_model_version" in value:
        out["LatestScheduledRetrainingModelVersion"] = value[
            "latest_scheduled_retraining_model_version"
        ]
    if "latest_scheduled_retraining_start_time" in value:
        import aws_sdk_lookoutequipment.types.timestamp

        out["LatestScheduledRetrainingStartTime"] = (
            aws_sdk_lookoutequipment.types.timestamp.serialize_aws_json_1_0(
                value["latest_scheduled_retraining_start_time"]
            )
        )
    if "next_scheduled_retraining_start_date" in value:
        import aws_sdk_lookoutequipment.types.timestamp

        out["NextScheduledRetrainingStartDate"] = (
            aws_sdk_lookoutequipment.types.timestamp.serialize_aws_json_1_0(
                value["next_scheduled_retraining_start_date"]
            )
        )
    if "retraining_scheduler_status" in value:
        import aws_sdk_lookoutequipment.types.retraining_scheduler_status

        out["RetrainingSchedulerStatus"] = (
            aws_sdk_lookoutequipment.types.retraining_scheduler_status.serialize_aws_json_1_0(
                value["retraining_scheduler_status"]
            )
        )
    if "model_diagnostics_output_configuration" in value:
        import aws_sdk_lookoutequipment.types.model_diagnostics_output_configuration

        out["ModelDiagnosticsOutputConfiguration"] = (
            aws_sdk_lookoutequipment.types.model_diagnostics_output_configuration.serialize_aws_json_1_0(
                value["model_diagnostics_output_configuration"]
            )
        )
    if "model_quality" in value:
        import aws_sdk_lookoutequipment.types.model_quality

        out["ModelQuality"] = (
            aws_sdk_lookoutequipment.types.model_quality.serialize_aws_json_1_0(
                value["model_quality"]
            )
        )
    return out


def deserialize_aws_json_1_0(data: dict) -> ModelSummary:
    out: ModelSummary = {}  # type: ignore[typeddict-item]
    if "ModelName" in data:
        out["model_name"] = data["ModelName"]
    if "ModelArn" in data:
        out["model_arn"] = data["ModelArn"]
    if "DatasetName" in data:
        out["dataset_name"] = data["DatasetName"]
    if "DatasetArn" in data:
        out["dataset_arn"] = data["DatasetArn"]
    if "Status" in data:
        import aws_sdk_lookoutequipment.types.model_status

        out["status"] = (
            aws_sdk_lookoutequipment.types.model_status.deserialize_aws_json_1_0(
                data["Status"]
            )
        )
    if "CreatedAt" in data:
        import aws_sdk_lookoutequipment.types.timestamp

        out["created_at"] = (
            aws_sdk_lookoutequipment.types.timestamp.deserialize_aws_json_1_0(
                data["CreatedAt"]
            )
        )
    if "ActiveModelVersion" in data:
        out["active_model_version"] = data["ActiveModelVersion"]
    if "ActiveModelVersionArn" in data:
        out["active_model_version_arn"] = data["ActiveModelVersionArn"]
    if "LatestScheduledRetrainingStatus" in data:
        import aws_sdk_lookoutequipment.types.model_version_status

        out["latest_scheduled_retraining_status"] = (
            aws_sdk_lookoutequipment.types.model_version_status.deserialize_aws_json_1_0(
                data["LatestScheduledRetrainingStatus"]
            )
        )
    if "LatestScheduledRetrainingModelVersion" in data:
        out["latest_scheduled_retraining_model_version"] = data[
            "LatestScheduledRetrainingModelVersion"
        ]
    if "LatestScheduledRetrainingStartTime" in data:
        import aws_sdk_lookoutequipment.types.timestamp

        out["latest_scheduled_retraining_start_time"] = (
            aws_sdk_lookoutequipment.types.timestamp.deserialize_aws_json_1_0(
                data["LatestScheduledRetrainingStartTime"]
            )
        )
    if "NextScheduledRetrainingStartDate" in data:
        import aws_sdk_lookoutequipment.types.timestamp

        out["next_scheduled_retraining_start_date"] = (
            aws_sdk_lookoutequipment.types.timestamp.deserialize_aws_json_1_0(
                data["NextScheduledRetrainingStartDate"]
            )
        )
    if "RetrainingSchedulerStatus" in data:
        import aws_sdk_lookoutequipment.types.retraining_scheduler_status

        out["retraining_scheduler_status"] = (
            aws_sdk_lookoutequipment.types.retraining_scheduler_status.deserialize_aws_json_1_0(
                data["RetrainingSchedulerStatus"]
            )
        )
    if "ModelDiagnosticsOutputConfiguration" in data:
        import aws_sdk_lookoutequipment.types.model_diagnostics_output_configuration

        out["model_diagnostics_output_configuration"] = (
            aws_sdk_lookoutequipment.types.model_diagnostics_output_configuration.deserialize_aws_json_1_0(
                data["ModelDiagnosticsOutputConfiguration"]
            )
        )
    if "ModelQuality" in data:
        import aws_sdk_lookoutequipment.types.model_quality

        out["model_quality"] = (
            aws_sdk_lookoutequipment.types.model_quality.deserialize_aws_json_1_0(
                data["ModelQuality"]
            )
        )
    return out
