"""Generated from Smithy shape ``com.amazonaws.omics#GetAnnotationImportResponse``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_omics.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_omics.types.annotation_field_map
    import aws_sdk_omics.types.annotation_import_item_details
    import aws_sdk_omics.types.arn
    import aws_sdk_omics.types.completion_time
    import aws_sdk_omics.types.creation_time
    import aws_sdk_omics.types.format_options
    import aws_sdk_omics.types.job_status
    import aws_sdk_omics.types.job_status_msg
    import aws_sdk_omics.types.resource_id
    import aws_sdk_omics.types.run_left_normalization
    import aws_sdk_omics.types.store_name
    import aws_sdk_omics.types.update_time
    import aws_sdk_omics.types.version_name


class GetAnnotationImportResponse(TypedDict, closed=True):
    id: "aws_sdk_omics.types.resource_id.ResourceId"
    """<p>The job's ID.</p>"""
    destination_name: "aws_sdk_omics.types.store_name.StoreName"
    """<p>The job's destination annotation store.</p>"""
    version_name: "aws_sdk_omics.types.version_name.VersionName"
    """<p> The name of the annotation store version. </p>"""
    role_arn: "aws_sdk_omics.types.arn.Arn"
    """<p>The job's service role ARN.</p>"""
    status: "aws_sdk_omics.types.job_status.JobStatus"
    """<p>The job's status.</p>"""
    status_message: "aws_sdk_omics.types.job_status_msg.JobStatusMsg"
    """<p>The job's status message.</p>"""
    creation_time: "aws_sdk_omics.types.creation_time.CreationTime"
    """<p>When the job was created.</p>"""
    update_time: "aws_sdk_omics.types.update_time.UpdateTime"
    """<p>When the job was updated.</p>"""
    completion_time: "aws_sdk_omics.types.completion_time.CompletionTime"
    """<p>When the job completed.</p>"""
    items: (
        "aws_sdk_omics.types.annotation_import_item_details.AnnotationImportItemDetails"
    )
    """<p>The job's imported items.</p>"""
    run_left_normalization: (
        "aws_sdk_omics.types.run_left_normalization.RunLeftNormalization"
    )
    """<p>The job's left normalization setting.</p>"""
    format_options: "aws_sdk_omics.types.format_options.FormatOptions"
    annotation_fields: NotRequired[
        "aws_sdk_omics.types.annotation_field_map.AnnotationFieldMap"
    ]
    """<p>The annotation schema generated by the parsed annotation data.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: GetAnnotationImportResponse) -> dict:
    out: dict = {}
    out["id"] = value["id"]
    out["destinationName"] = value["destination_name"]
    out["versionName"] = value["version_name"]
    out["roleArn"] = value["role_arn"]
    out["status"] = value["status"]
    out["statusMessage"] = value["status_message"]
    import aws_sdk_omics.types.creation_time

    out["creationTime"] = aws_sdk_omics.types.creation_time.serialize_json(
        value["creation_time"]
    )
    import aws_sdk_omics.types.update_time

    out["updateTime"] = aws_sdk_omics.types.update_time.serialize_json(
        value["update_time"]
    )
    import aws_sdk_omics.types.completion_time

    out["completionTime"] = aws_sdk_omics.types.completion_time.serialize_json(
        value["completion_time"]
    )
    import aws_sdk_omics.types.annotation_import_item_details

    out["items"] = aws_sdk_omics.types.annotation_import_item_details.serialize_json(
        value["items"]
    )
    out["runLeftNormalization"] = value.get("run_left_normalization", False)
    import aws_sdk_omics.types.format_options

    out["formatOptions"] = aws_sdk_omics.types.format_options.serialize_json(
        value["format_options"]
    )
    if "annotation_fields" in value:
        import aws_sdk_omics.types.annotation_field_map

        out["annotationFields"] = (
            aws_sdk_omics.types.annotation_field_map.serialize_json(
                value["annotation_fields"]
            )
        )
    return out


def deserialize_json(data: dict) -> GetAnnotationImportResponse:
    out: GetAnnotationImportResponse = {}  # type: ignore[typeddict-item]
    if "id" in data:
        out["id"] = data["id"]
    else:
        raise DeserializationError("GetAnnotationImportResponse.id required")
    if "destinationName" in data:
        out["destination_name"] = data["destinationName"]
    else:
        raise DeserializationError(
            "GetAnnotationImportResponse.destination_name required"
        )
    if "versionName" in data:
        out["version_name"] = data["versionName"]
    else:
        raise DeserializationError("GetAnnotationImportResponse.version_name required")
    if "roleArn" in data:
        out["role_arn"] = data["roleArn"]
    else:
        raise DeserializationError("GetAnnotationImportResponse.role_arn required")
    if "status" in data:
        out["status"] = data["status"]
    else:
        raise DeserializationError("GetAnnotationImportResponse.status required")
    if "statusMessage" in data:
        out["status_message"] = data["statusMessage"]
    else:
        raise DeserializationError(
            "GetAnnotationImportResponse.status_message required"
        )
    if "creationTime" in data:
        import aws_sdk_omics.types.creation_time

        out["creation_time"] = aws_sdk_omics.types.creation_time.deserialize_json(
            data["creationTime"]
        )
    else:
        raise DeserializationError("GetAnnotationImportResponse.creation_time required")
    if "updateTime" in data:
        import aws_sdk_omics.types.update_time

        out["update_time"] = aws_sdk_omics.types.update_time.deserialize_json(
            data["updateTime"]
        )
    else:
        raise DeserializationError("GetAnnotationImportResponse.update_time required")
    if "completionTime" in data:
        import aws_sdk_omics.types.completion_time

        out["completion_time"] = aws_sdk_omics.types.completion_time.deserialize_json(
            data["completionTime"]
        )
    else:
        raise DeserializationError(
            "GetAnnotationImportResponse.completion_time required"
        )
    if "items" in data:
        import aws_sdk_omics.types.annotation_import_item_details

        out["items"] = (
            aws_sdk_omics.types.annotation_import_item_details.deserialize_json(
                data["items"]
            )
        )
    else:
        raise DeserializationError("GetAnnotationImportResponse.items required")
    if "runLeftNormalization" in data:
        out["run_left_normalization"] = data["runLeftNormalization"]
    else:
        out["run_left_normalization"] = False
    if "formatOptions" in data:
        import aws_sdk_omics.types.format_options

        out["format_options"] = aws_sdk_omics.types.format_options.deserialize_json(
            data["formatOptions"]
        )
    else:
        raise DeserializationError(
            "GetAnnotationImportResponse.format_options required"
        )
    if "annotationFields" in data:
        import aws_sdk_omics.types.annotation_field_map

        out["annotation_fields"] = (
            aws_sdk_omics.types.annotation_field_map.deserialize_json(
                data["annotationFields"]
            )
        )
    return out
