"""Generated from Smithy shape ``com.amazonaws.omics#VariantImportJobItem``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_omics.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_omics.types.annotation_field_map
    import aws_sdk_omics.types.arn
    import aws_sdk_omics.types.completion_time
    import aws_sdk_omics.types.creation_time
    import aws_sdk_omics.types.job_status
    import aws_sdk_omics.types.run_left_normalization
    import aws_sdk_omics.types.update_time


class VariantImportJobItem(TypedDict, closed=True):
    id: "str"
    """<p>The job's ID.</p>"""
    destination_name: "str"
    """<p>The job's destination variant store.</p>"""
    role_arn: "aws_sdk_omics.types.arn.Arn"
    """<p>The job's service role ARN.</p>"""
    status: "aws_sdk_omics.types.job_status.JobStatus"
    """<p>The job's status.</p>"""
    creation_time: "aws_sdk_omics.types.creation_time.CreationTime"
    """<p>When the job was created.</p>"""
    update_time: "aws_sdk_omics.types.update_time.UpdateTime"
    """<p>When the job was updated.</p>"""
    completion_time: NotRequired["aws_sdk_omics.types.completion_time.CompletionTime"]
    """<p>When the job completed.</p>"""
    run_left_normalization: (
        "aws_sdk_omics.types.run_left_normalization.RunLeftNormalization"
    )
    """<p>The job's left normalization setting.</p>"""
    annotation_fields: NotRequired[
        "aws_sdk_omics.types.annotation_field_map.AnnotationFieldMap"
    ]
    """<p> The annotation schema generated by the parsed annotation data. </p>"""


# --- restJson1 ser/de ---
def serialize_json(value: VariantImportJobItem) -> dict:
    out: dict = {}
    out["id"] = value["id"]
    out["destinationName"] = value["destination_name"]
    out["roleArn"] = value["role_arn"]
    out["status"] = value["status"]
    import aws_sdk_omics.types.creation_time

    out["creationTime"] = aws_sdk_omics.types.creation_time.serialize_json(
        value["creation_time"]
    )
    import aws_sdk_omics.types.update_time

    out["updateTime"] = aws_sdk_omics.types.update_time.serialize_json(
        value["update_time"]
    )
    if "completion_time" in value:
        import aws_sdk_omics.types.completion_time

        out["completionTime"] = aws_sdk_omics.types.completion_time.serialize_json(
            value["completion_time"]
        )
    out["runLeftNormalization"] = value.get("run_left_normalization", False)
    if "annotation_fields" in value:
        import aws_sdk_omics.types.annotation_field_map

        out["annotationFields"] = (
            aws_sdk_omics.types.annotation_field_map.serialize_json(
                value["annotation_fields"]
            )
        )
    return out


def deserialize_json(data: dict) -> VariantImportJobItem:
    out: VariantImportJobItem = {}  # type: ignore[typeddict-item]
    if "id" in data:
        out["id"] = data["id"]
    else:
        raise DeserializationError("VariantImportJobItem.id required")
    if "destinationName" in data:
        out["destination_name"] = data["destinationName"]
    else:
        raise DeserializationError("VariantImportJobItem.destination_name required")
    if "roleArn" in data:
        out["role_arn"] = data["roleArn"]
    else:
        raise DeserializationError("VariantImportJobItem.role_arn required")
    if "status" in data:
        out["status"] = data["status"]
    else:
        raise DeserializationError("VariantImportJobItem.status required")
    if "creationTime" in data:
        import aws_sdk_omics.types.creation_time

        out["creation_time"] = aws_sdk_omics.types.creation_time.deserialize_json(
            data["creationTime"]
        )
    else:
        raise DeserializationError("VariantImportJobItem.creation_time required")
    if "updateTime" in data:
        import aws_sdk_omics.types.update_time

        out["update_time"] = aws_sdk_omics.types.update_time.deserialize_json(
            data["updateTime"]
        )
    else:
        raise DeserializationError("VariantImportJobItem.update_time required")
    if "completionTime" in data:
        import aws_sdk_omics.types.completion_time

        out["completion_time"] = aws_sdk_omics.types.completion_time.deserialize_json(
            data["completionTime"]
        )
    if "runLeftNormalization" in data:
        out["run_left_normalization"] = data["runLeftNormalization"]
    else:
        out["run_left_normalization"] = False
    if "annotationFields" in data:
        import aws_sdk_omics.types.annotation_field_map

        out["annotation_fields"] = (
            aws_sdk_omics.types.annotation_field_map.deserialize_json(
                data["annotationFields"]
            )
        )
    return out
