"""Generated from Smithy shape ``com.amazonaws.bedrockagentcorecontrol#ModifyMemoryStrategyInput``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

from aws_sdk_bedrock_agentcore_control.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_bedrock_agentcore_control.types.description
    import aws_sdk_bedrock_agentcore_control.types.memory_record_schema
    import aws_sdk_bedrock_agentcore_control.types.modify_strategy_configuration
    import aws_sdk_bedrock_agentcore_control.types.namespaces_list


class ModifyMemoryStrategyInput(TypedDict):
    memory_strategy_id: "str"
    """<p>The unique identifier of the memory strategy to modify.</p>"""
    description: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.description.Description"
    ]
    """<p>The updated description of the memory strategy.</p>"""
    namespaces: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.namespaces_list.NamespacesList"
    ]
    """<p>This is a legacy parameter, use <code>namespaceTemplates</code>. The updated namespaces for the memory strategy.</p>"""
    namespace_templates: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.namespaces_list.NamespacesList"
    ]
    """<p>The updated namespaceTemplates for the memory strategy.</p>"""
    configuration: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.modify_strategy_configuration.ModifyStrategyConfiguration"
    ]
    """<p>The updated configuration for the memory strategy.</p>"""
    memory_record_schema: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.memory_record_schema.MemoryRecordSchema"
    ]
    """<p>Updated metadata schema for records generated by this strategy.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ModifyMemoryStrategyInput) -> dict:
    out: dict = {}
    out["memoryStrategyId"] = value["memory_strategy_id"]
    if "description" in value:
        out["description"] = value["description"]
    if "namespaces" in value:
        import aws_sdk_bedrock_agentcore_control.types.namespaces_list

        out["namespaces"] = (
            aws_sdk_bedrock_agentcore_control.types.namespaces_list.serialize_json(
                value["namespaces"]
            )
        )
    if "namespace_templates" in value:
        import aws_sdk_bedrock_agentcore_control.types.namespaces_list

        out["namespaceTemplates"] = (
            aws_sdk_bedrock_agentcore_control.types.namespaces_list.serialize_json(
                value["namespace_templates"]
            )
        )
    if "configuration" in value:
        import aws_sdk_bedrock_agentcore_control.types.modify_strategy_configuration

        out["configuration"] = (
            aws_sdk_bedrock_agentcore_control.types.modify_strategy_configuration.serialize_json(
                value["configuration"]
            )
        )
    if "memory_record_schema" in value:
        import aws_sdk_bedrock_agentcore_control.types.memory_record_schema

        out["memoryRecordSchema"] = (
            aws_sdk_bedrock_agentcore_control.types.memory_record_schema.serialize_json(
                value["memory_record_schema"]
            )
        )
    return out


def deserialize_json(data: dict) -> ModifyMemoryStrategyInput:
    out: ModifyMemoryStrategyInput = {}  # type: ignore[typeddict-item]
    if "memoryStrategyId" in data:
        out["memory_strategy_id"] = data["memoryStrategyId"]
    else:
        raise DeserializationError(
            "ModifyMemoryStrategyInput.memory_strategy_id required"
        )
    if "description" in data:
        out["description"] = data["description"]
    if "namespaces" in data:
        import aws_sdk_bedrock_agentcore_control.types.namespaces_list

        out["namespaces"] = (
            aws_sdk_bedrock_agentcore_control.types.namespaces_list.deserialize_json(
                data["namespaces"]
            )
        )
    if "namespaceTemplates" in data:
        import aws_sdk_bedrock_agentcore_control.types.namespaces_list

        out["namespace_templates"] = (
            aws_sdk_bedrock_agentcore_control.types.namespaces_list.deserialize_json(
                data["namespaceTemplates"]
            )
        )
    if "configuration" in data:
        import aws_sdk_bedrock_agentcore_control.types.modify_strategy_configuration

        out["configuration"] = (
            aws_sdk_bedrock_agentcore_control.types.modify_strategy_configuration.deserialize_json(
                data["configuration"]
            )
        )
    if "memoryRecordSchema" in data:
        import aws_sdk_bedrock_agentcore_control.types.memory_record_schema

        out["memory_record_schema"] = (
            aws_sdk_bedrock_agentcore_control.types.memory_record_schema.deserialize_json(
                data["memoryRecordSchema"]
            )
        )
    return out
