"""Generated from Smithy shape ``com.amazonaws.bedrockagentcorecontrol#UserPreferenceMemoryStrategyInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_bedrock_agentcore_control.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_bedrock_agentcore_control.types.description
    import aws_sdk_bedrock_agentcore_control.types.memory_record_schema
    import aws_sdk_bedrock_agentcore_control.types.name
    import aws_sdk_bedrock_agentcore_control.types.namespaces_list


class UserPreferenceMemoryStrategyInput(TypedDict, closed=True):
    name: "aws_sdk_bedrock_agentcore_control.types.name.Name"
    """<p>The name of the user preference memory strategy.</p>"""
    description: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.description.Description"
    ]
    """<p>The description of the user preference memory strategy.</p>"""
    namespaces: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.namespaces_list.NamespacesList"
    ]
    """<p>This is a legacy parameter, use <code>namespaceTemplates</code>. The namespaces associated with the user preference memory strategy.</p>"""
    namespace_templates: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.namespaces_list.NamespacesList"
    ]
    """<p>The namespaceTemplates associated with the user preference memory strategy.</p>"""
    memory_record_schema: NotRequired[
        "aws_sdk_bedrock_agentcore_control.types.memory_record_schema.MemoryRecordSchema"
    ]
    """<p>Schema for metadata fields on records generated by this strategy.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: UserPreferenceMemoryStrategyInput) -> dict:
    out: dict = {}
    out["name"] = value["name"]
    if "description" in value:
        out["description"] = value["description"]
    if "namespaces" in value:
        import aws_sdk_bedrock_agentcore_control.types.namespaces_list

        out["namespaces"] = (
            aws_sdk_bedrock_agentcore_control.types.namespaces_list.serialize_json(
                value["namespaces"]
            )
        )
    if "namespace_templates" in value:
        import aws_sdk_bedrock_agentcore_control.types.namespaces_list

        out["namespaceTemplates"] = (
            aws_sdk_bedrock_agentcore_control.types.namespaces_list.serialize_json(
                value["namespace_templates"]
            )
        )
    if "memory_record_schema" in value:
        import aws_sdk_bedrock_agentcore_control.types.memory_record_schema

        out["memoryRecordSchema"] = (
            aws_sdk_bedrock_agentcore_control.types.memory_record_schema.serialize_json(
                value["memory_record_schema"]
            )
        )
    return out


def deserialize_json(data: dict) -> UserPreferenceMemoryStrategyInput:
    out: UserPreferenceMemoryStrategyInput = {}  # type: ignore[typeddict-item]
    if "name" in data:
        out["name"] = data["name"]
    else:
        raise DeserializationError("UserPreferenceMemoryStrategyInput.name required")
    if "description" in data:
        out["description"] = data["description"]
    if "namespaces" in data:
        import aws_sdk_bedrock_agentcore_control.types.namespaces_list

        out["namespaces"] = (
            aws_sdk_bedrock_agentcore_control.types.namespaces_list.deserialize_json(
                data["namespaces"]
            )
        )
    if "namespaceTemplates" in data:
        import aws_sdk_bedrock_agentcore_control.types.namespaces_list

        out["namespace_templates"] = (
            aws_sdk_bedrock_agentcore_control.types.namespaces_list.deserialize_json(
                data["namespaceTemplates"]
            )
        )
    if "memoryRecordSchema" in data:
        import aws_sdk_bedrock_agentcore_control.types.memory_record_schema

        out["memory_record_schema"] = (
            aws_sdk_bedrock_agentcore_control.types.memory_record_schema.deserialize_json(
                data["memoryRecordSchema"]
            )
        )
    return out
