"""Generated from Smithy shape ``com.amazonaws.appsync#DisassociateMergedGraphqlApiRequest``."""

from typing import TYPE_CHECKING, TypedDict

if TYPE_CHECKING:
    import aws_sdk_appsync.types.string


class DisassociateMergedGraphqlApiRequest(TypedDict):
    source_api_identifier: "aws_sdk_appsync.types.string.String"
    """<p>The identifier of the AppSync Source API. This is generated by the AppSync service. In most cases, source APIs (especially in your account) only require the API ID value or ARN of the source API. However, source APIs from other accounts (cross-account use cases) strictly require the full resource ARN of the source API.</p>"""
    association_id: "aws_sdk_appsync.types.string.String"
    """<p>The ID generated by the AppSync service for the source API association.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: DisassociateMergedGraphqlApiRequest) -> dict:
    out: dict = {}
    return out


def deserialize_json(data: dict) -> DisassociateMergedGraphqlApiRequest:
    out: DisassociateMergedGraphqlApiRequest = {}  # type: ignore[typeddict-item]
    return out
