"""Generated from Smithy shape ``com.amazonaws.qapps#QQueryCard``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

from aws_sdk_qapps.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_qapps.types.attribute_filter
    import aws_sdk_qapps.types.card_output_source
    import aws_sdk_qapps.types.card_type
    import aws_sdk_qapps.types.dependency_list
    import aws_sdk_qapps.types.memory_reference_list
    import aws_sdk_qapps.types.prompt
    import aws_sdk_qapps.types.title
    import aws_sdk_qapps.types.uuid


class QQueryCard(TypedDict):
    id: "aws_sdk_qapps.types.uuid.UUID"
    """<p>The unique identifier of the query card. </p>"""
    title: "aws_sdk_qapps.types.title.Title"
    """<p>The title or label of the query card.</p>"""
    dependencies: "aws_sdk_qapps.types.dependency_list.DependencyList"
    """<p>Any dependencies or requirements for the query card.</p>"""
    type: "aws_sdk_qapps.types.card_type.CardType"
    """<p>The type of the card.</p>"""
    prompt: "aws_sdk_qapps.types.prompt.Prompt"
    """<p>The prompt or instructions displayed for the query card.</p>"""
    output_source: "aws_sdk_qapps.types.card_output_source.CardOutputSource"
    """<p>The source or type of output generated by the query card.</p>"""
    attribute_filter: NotRequired[
        "aws_sdk_qapps.types.attribute_filter.AttributeFilter"
    ]
    """<p>The Amazon Q Business filters applied in this query card when resolving data sources</p>"""
    memory_references: NotRequired[
        "aws_sdk_qapps.types.memory_reference_list.MemoryReferenceList"
    ]
    """<p>Any dependencies for the query card, where the dependencies are references to the collected responses.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: QQueryCard) -> dict:
    out: dict = {}
    out["id"] = value["id"]
    out["title"] = value["title"]
    import aws_sdk_qapps.types.dependency_list

    out["dependencies"] = aws_sdk_qapps.types.dependency_list.serialize_json(
        value["dependencies"]
    )
    import aws_sdk_qapps.types.card_type

    out["type"] = aws_sdk_qapps.types.card_type.serialize_json(value["type"])
    out["prompt"] = value["prompt"]
    import aws_sdk_qapps.types.card_output_source

    out["outputSource"] = aws_sdk_qapps.types.card_output_source.serialize_json(
        value["output_source"]
    )
    if "attribute_filter" in value:
        import aws_sdk_qapps.types.attribute_filter

        out["attributeFilter"] = aws_sdk_qapps.types.attribute_filter.serialize_json(
            value["attribute_filter"]
        )
    if "memory_references" in value:
        import aws_sdk_qapps.types.memory_reference_list

        out["memoryReferences"] = (
            aws_sdk_qapps.types.memory_reference_list.serialize_json(
                value["memory_references"]
            )
        )
    return out


def deserialize_json(data: dict) -> QQueryCard:
    out: QQueryCard = {}  # type: ignore[typeddict-item]
    if "id" in data:
        out["id"] = data["id"]
    else:
        raise DeserializationError("QQueryCard.id required")
    if "title" in data:
        out["title"] = data["title"]
    else:
        raise DeserializationError("QQueryCard.title required")
    if "dependencies" in data:
        import aws_sdk_qapps.types.dependency_list

        out["dependencies"] = aws_sdk_qapps.types.dependency_list.deserialize_json(
            data["dependencies"]
        )
    else:
        raise DeserializationError("QQueryCard.dependencies required")
    if "type" in data:
        import aws_sdk_qapps.types.card_type

        out["type"] = aws_sdk_qapps.types.card_type.deserialize_json(data["type"])
    else:
        raise DeserializationError("QQueryCard.type required")
    if "prompt" in data:
        out["prompt"] = data["prompt"]
    else:
        raise DeserializationError("QQueryCard.prompt required")
    if "outputSource" in data:
        import aws_sdk_qapps.types.card_output_source

        out["output_source"] = aws_sdk_qapps.types.card_output_source.deserialize_json(
            data["outputSource"]
        )
    else:
        raise DeserializationError("QQueryCard.output_source required")
    if "attributeFilter" in data:
        import aws_sdk_qapps.types.attribute_filter

        out["attribute_filter"] = aws_sdk_qapps.types.attribute_filter.deserialize_json(
            data["attributeFilter"]
        )
    if "memoryReferences" in data:
        import aws_sdk_qapps.types.memory_reference_list

        out["memory_references"] = (
            aws_sdk_qapps.types.memory_reference_list.deserialize_json(
                data["memoryReferences"]
            )
        )
    return out
