"""Generated from Smithy shape ``com.amazonaws.transcribe#LanguageCode``."""

from typing import Literal, TypeAlias, cast

LanguageCode: TypeAlias = Literal[
    "af-ZA",
    "ar-AE",
    "ar-SA",
    "am-ET",
    "cy-GB",
    "da-DK",
    "de-CH",
    "de-DE",
    "en-AB",
    "en-AU",
    "en-GB",
    "en-IE",
    "en-IN",
    "en-US",
    "en-WL",
    "es-ES",
    "es-MX",
    "es-US",
    "fa-AF",
    "fa-IR",
    "fr-CA",
    "fr-FR",
    "ga-IE",
    "gd-GB",
    "he-IL",
    "hi-IN",
    "ht-HT",
    "id-ID",
    "it-IT",
    "ja-JP",
    "jv-ID",
    "km-KH",
    "ko-KR",
    "my-MM",
    "ms-MY",
    "nl-NL",
    "pt-BR",
    "pt-PT",
    "ru-RU",
    "ta-IN",
    "te-IN",
    "tr-TR",
    "zh-CN",
    "zh-TW",
    "th-TH",
    "en-ZA",
    "en-NZ",
    "vi-VN",
    "sv-SE",
    "ab-GE",
    "ast-ES",
    "az-AZ",
    "ba-RU",
    "be-BY",
    "bg-BG",
    "bn-IN",
    "bs-BA",
    "ca-ES",
    "ckb-IQ",
    "ckb-IR",
    "cs-CZ",
    "cy-WL",
    "el-GR",
    "et-EE",
    "et-ET",
    "eu-ES",
    "fi-FI",
    "gl-ES",
    "gu-IN",
    "ha-NG",
    "hr-HR",
    "hu-HU",
    "hy-AM",
    "is-IS",
    "ka-GE",
    "kab-DZ",
    "kk-KZ",
    "kn-IN",
    "ky-KG",
    "lg-IN",
    "lt-LT",
    "lv-LV",
    "mhr-RU",
    "mi-NZ",
    "mk-MK",
    "ml-IN",
    "mn-MN",
    "mr-IN",
    "mt-MT",
    "no-NO",
    "ne-NP",
    "or-IN",
    "pa-IN",
    "pl-PL",
    "ps-AF",
    "ro-RO",
    "rw-RW",
    "si-LK",
    "sk-SK",
    "sl-SI",
    "so-SO",
    "sq-AL",
    "sr-RS",
    "su-ID",
    "sw-BI",
    "sw-KE",
    "sw-RW",
    "sw-TZ",
    "sw-UG",
    "tl-PH",
    "tt-RU",
    "ug-CN",
    "uk-UA",
    "uz-UZ",
    "wo-SN",
    "zh-HK",
    "zu-ZA",
]


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: LanguageCode) -> str:
    return value


def deserialize_aws_json_1_1(data: str) -> LanguageCode:
    return cast(LanguageCode, data)
