"""Generated from Smithy shape ``com.amazonaws.cloudtrail#GetChannelResponse``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_cloudtrail.types.channel_arn
    import capo_cloudtrail.types.channel_name
    import capo_cloudtrail.types.destinations
    import capo_cloudtrail.types.ingestion_status
    import capo_cloudtrail.types.source
    import capo_cloudtrail.types.source_config


class GetChannelResponse(TypedDict, closed=True):
    channel_arn: NotRequired["capo_cloudtrail.types.channel_arn.ChannelArn"]
    """<p>The ARN of an channel returned by a <code>GetChannel</code> request.</p>"""
    name: NotRequired["capo_cloudtrail.types.channel_name.ChannelName"]
    """<p> The name of the CloudTrail channel. For service-linked channels, the name is <code>aws-service-channel/service-name/custom-suffix</code> where <code>service-name</code> represents the name of the Amazon Web Services service that created the channel and <code>custom-suffix</code> represents the suffix generated by the Amazon Web Services service. </p>"""
    source: NotRequired["capo_cloudtrail.types.source.Source"]
    """<p>The source for the CloudTrail channel.</p>"""
    source_config: NotRequired["capo_cloudtrail.types.source_config.SourceConfig"]
    """<p> Provides information about the advanced event selectors configured for the channel, and whether the channel applies to all Regions or a single Region. </p>"""
    destinations: NotRequired["capo_cloudtrail.types.destinations.Destinations"]
    """<p>The destinations for the channel. For channels created for integrations, the destinations are the event data stores that log events arriving through the channel. For service-linked channels, the destination is the Amazon Web Services service that created the service-linked channel to receive events.</p>"""
    ingestion_status: NotRequired[
        "capo_cloudtrail.types.ingestion_status.IngestionStatus"
    ]
    """<p>A table showing information about the most recent successful and failed attempts to ingest events.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: GetChannelResponse) -> dict:
    out: dict = {}
    if "channel_arn" in value:
        out["ChannelArn"] = value["channel_arn"]
    if "name" in value:
        out["Name"] = value["name"]
    if "source" in value:
        out["Source"] = value["source"]
    if "source_config" in value:
        import capo_cloudtrail.types.source_config

        out["SourceConfig"] = (
            capo_cloudtrail.types.source_config.serialize_aws_json_1_1(
                value["source_config"]
            )
        )
    if "destinations" in value:
        import capo_cloudtrail.types.destinations

        out["Destinations"] = capo_cloudtrail.types.destinations.serialize_aws_json_1_1(
            value["destinations"]
        )
    if "ingestion_status" in value:
        import capo_cloudtrail.types.ingestion_status

        out["IngestionStatus"] = (
            capo_cloudtrail.types.ingestion_status.serialize_aws_json_1_1(
                value["ingestion_status"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> GetChannelResponse:
    out: GetChannelResponse = {}  # type: ignore[typeddict-item]
    if "ChannelArn" in data:
        out["channel_arn"] = data["ChannelArn"]
    if "Name" in data:
        out["name"] = data["Name"]
    if "Source" in data:
        out["source"] = data["Source"]
    if "SourceConfig" in data:
        import capo_cloudtrail.types.source_config

        out["source_config"] = (
            capo_cloudtrail.types.source_config.deserialize_aws_json_1_1(
                data["SourceConfig"]
            )
        )
    if "Destinations" in data:
        import capo_cloudtrail.types.destinations

        out["destinations"] = (
            capo_cloudtrail.types.destinations.deserialize_aws_json_1_1(
                data["Destinations"]
            )
        )
    if "IngestionStatus" in data:
        import capo_cloudtrail.types.ingestion_status

        out["ingestion_status"] = (
            capo_cloudtrail.types.ingestion_status.deserialize_aws_json_1_1(
                data["IngestionStatus"]
            )
        )
    return out
