"""Generated from Smithy shape ``com.amazonaws.chatbot#CreateCustomActionRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_chatbot.errors import DeserializationError

if TYPE_CHECKING:
    import capo_chatbot.types.client_token
    import capo_chatbot.types.custom_action_alias_name
    import capo_chatbot.types.custom_action_attachment_list
    import capo_chatbot.types.custom_action_definition
    import capo_chatbot.types.custom_action_name
    import capo_chatbot.types.tag_list


class CreateCustomActionRequest(TypedDict, closed=True):
    definition: "capo_chatbot.types.custom_action_definition.CustomActionDefinition"
    """<p>The definition of the command to run when invoked as an alias or as an action button.</p>"""
    alias_name: NotRequired[
        "capo_chatbot.types.custom_action_alias_name.CustomActionAliasName"
    ]
    """<p>The name used to invoke this action in a chat channel. For example, <code>@aws run my-alias</code>.</p>"""
    attachments: NotRequired[
        "capo_chatbot.types.custom_action_attachment_list.CustomActionAttachmentList"
    ]
    """<p>Defines when this custom action button should be attached to a notification.</p>"""
    tags: NotRequired["capo_chatbot.types.tag_list.TagList"]
    """<p>A map of tags assigned to a resource. A tag is a string-to-string map of key-value pairs.</p>"""
    client_token: NotRequired["capo_chatbot.types.client_token.ClientToken"]
    """<p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request.</p> <p>If you do not specify a client token, one is automatically generated by the SDK.</p>"""
    action_name: "capo_chatbot.types.custom_action_name.CustomActionName"
    """<p>The name of the custom action. This name is included in the Amazon Resource Name (ARN).</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: CreateCustomActionRequest) -> dict:
    out: dict = {}
    import capo_chatbot.types.custom_action_definition

    out["Definition"] = capo_chatbot.types.custom_action_definition.serialize_json(
        value["definition"]
    )
    if "alias_name" in value:
        out["AliasName"] = value["alias_name"]
    if "attachments" in value:
        import capo_chatbot.types.custom_action_attachment_list

        out["Attachments"] = (
            capo_chatbot.types.custom_action_attachment_list.serialize_json(
                value["attachments"]
            )
        )
    if "tags" in value:
        import capo_chatbot.types.tag_list

        out["Tags"] = capo_chatbot.types.tag_list.serialize_json(value["tags"])
    if "client_token" in value:
        out["ClientToken"] = value["client_token"]
    out["ActionName"] = value["action_name"]
    return out


def deserialize_json(data: dict) -> CreateCustomActionRequest:
    out: CreateCustomActionRequest = {}  # type: ignore[typeddict-item]
    if "Definition" in data:
        import capo_chatbot.types.custom_action_definition

        out["definition"] = (
            capo_chatbot.types.custom_action_definition.deserialize_json(
                data["Definition"]
            )
        )
    else:
        raise DeserializationError("CreateCustomActionRequest.definition required")
    if "AliasName" in data:
        out["alias_name"] = data["AliasName"]
    if "Attachments" in data:
        import capo_chatbot.types.custom_action_attachment_list

        out["attachments"] = (
            capo_chatbot.types.custom_action_attachment_list.deserialize_json(
                data["Attachments"]
            )
        )
    if "Tags" in data:
        import capo_chatbot.types.tag_list

        out["tags"] = capo_chatbot.types.tag_list.deserialize_json(data["Tags"])
    if "ClientToken" in data:
        out["client_token"] = data["ClientToken"]
    if "ActionName" in data:
        out["action_name"] = data["ActionName"]
    else:
        raise DeserializationError("CreateCustomActionRequest.action_name required")
    return out
