"""Generated from Smithy shape ``com.amazonaws.lexmodelsv2#OpensearchConfiguration``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_lex_models_v2.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_lex_models_v2.types.boolean
    import aws_sdk_lex_models_v2.types.domain_endpoint
    import aws_sdk_lex_models_v2.types.exact_response_fields
    import aws_sdk_lex_models_v2.types.os_include_fields
    import aws_sdk_lex_models_v2.types.os_index_name


class OpensearchConfiguration(TypedDict, closed=True):
    domain_endpoint: "aws_sdk_lex_models_v2.types.domain_endpoint.DomainEndpoint"
    """<p>The endpoint of the Amazon OpenSearch Service domain.</p>"""
    index_name: "aws_sdk_lex_models_v2.types.os_index_name.OSIndexName"
    """<p>The name of the Amazon OpenSearch Service index.</p>"""
    exact_response: "aws_sdk_lex_models_v2.types.boolean.Boolean"
    """<p>Specifies whether to return an exact response or to return an answer generated by the model using the fields you specify from the database.</p>"""
    exact_response_fields: NotRequired[
        "aws_sdk_lex_models_v2.types.exact_response_fields.ExactResponseFields"
    ]
    """<p>Contains the names of the fields used for an exact response to the user.</p>"""
    include_fields: NotRequired[
        "aws_sdk_lex_models_v2.types.os_include_fields.OSIncludeFields"
    ]
    """<p>Contains a list of fields from the Amazon OpenSearch Service that the model can use to generate the answer to the query.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: OpensearchConfiguration) -> dict:
    out: dict = {}
    out["domainEndpoint"] = value["domain_endpoint"]
    out["indexName"] = value["index_name"]
    out["exactResponse"] = value.get("exact_response", False)
    if "exact_response_fields" in value:
        import aws_sdk_lex_models_v2.types.exact_response_fields

        out["exactResponseFields"] = (
            aws_sdk_lex_models_v2.types.exact_response_fields.serialize_json(
                value["exact_response_fields"]
            )
        )
    if "include_fields" in value:
        import aws_sdk_lex_models_v2.types.os_include_fields

        out["includeFields"] = (
            aws_sdk_lex_models_v2.types.os_include_fields.serialize_json(
                value["include_fields"]
            )
        )
    return out


def deserialize_json(data: dict) -> OpensearchConfiguration:
    out: OpensearchConfiguration = {}  # type: ignore[typeddict-item]
    if "domainEndpoint" in data:
        out["domain_endpoint"] = data["domainEndpoint"]
    else:
        raise DeserializationError("OpensearchConfiguration.domain_endpoint required")
    if "indexName" in data:
        out["index_name"] = data["indexName"]
    else:
        raise DeserializationError("OpensearchConfiguration.index_name required")
    if "exactResponse" in data:
        out["exact_response"] = data["exactResponse"]
    else:
        out["exact_response"] = False
    if "exactResponseFields" in data:
        import aws_sdk_lex_models_v2.types.exact_response_fields

        out["exact_response_fields"] = (
            aws_sdk_lex_models_v2.types.exact_response_fields.deserialize_json(
                data["exactResponseFields"]
            )
        )
    if "includeFields" in data:
        import aws_sdk_lex_models_v2.types.os_include_fields

        out["include_fields"] = (
            aws_sdk_lex_models_v2.types.os_include_fields.deserialize_json(
                data["includeFields"]
            )
        )
    return out
