"""Generated from Smithy shape ``com.amazonaws.databrew#DatabaseOutput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_databrew.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_databrew.types.database_output_mode
    import aws_sdk_databrew.types.database_table_output_options
    import aws_sdk_databrew.types.glue_connection_name


class DatabaseOutput(TypedDict, closed=True):
    glue_connection_name: (
        "aws_sdk_databrew.types.glue_connection_name.GlueConnectionName"
    )
    """<p>The Glue connection that stores the connection information for the target database.</p>"""
    database_options: "aws_sdk_databrew.types.database_table_output_options.DatabaseTableOutputOptions"
    """<p>Represents options that specify how and where DataBrew writes the database output generated by recipe jobs.</p>"""
    database_output_mode: NotRequired[
        "aws_sdk_databrew.types.database_output_mode.DatabaseOutputMode"
    ]
    """<p>The output mode to write into the database. Currently supported option: NEW_TABLE.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: DatabaseOutput) -> dict:
    out: dict = {}
    out["GlueConnectionName"] = value["glue_connection_name"]
    import aws_sdk_databrew.types.database_table_output_options

    out["DatabaseOptions"] = (
        aws_sdk_databrew.types.database_table_output_options.serialize_json(
            value["database_options"]
        )
    )
    if "database_output_mode" in value:
        import aws_sdk_databrew.types.database_output_mode

        out["DatabaseOutputMode"] = (
            aws_sdk_databrew.types.database_output_mode.serialize_json(
                value["database_output_mode"]
            )
        )
    return out


def deserialize_json(data: dict) -> DatabaseOutput:
    out: DatabaseOutput = {}  # type: ignore[typeddict-item]
    if "GlueConnectionName" in data:
        out["glue_connection_name"] = data["GlueConnectionName"]
    else:
        raise DeserializationError("DatabaseOutput.glue_connection_name required")
    if "DatabaseOptions" in data:
        import aws_sdk_databrew.types.database_table_output_options

        out["database_options"] = (
            aws_sdk_databrew.types.database_table_output_options.deserialize_json(
                data["DatabaseOptions"]
            )
        )
    else:
        raise DeserializationError("DatabaseOutput.database_options required")
    if "DatabaseOutputMode" in data:
        import aws_sdk_databrew.types.database_output_mode

        out["database_output_mode"] = (
            aws_sdk_databrew.types.database_output_mode.deserialize_json(
                data["DatabaseOutputMode"]
            )
        )
    return out
