"""Generated from Smithy shape ``com.amazonaws.databrew#ListRulesetsRequest``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

if TYPE_CHECKING:
    import aws_sdk_databrew.types.arn
    import aws_sdk_databrew.types.max_results100
    import aws_sdk_databrew.types.next_token


class ListRulesetsRequest(TypedDict):
    target_arn: NotRequired["aws_sdk_databrew.types.arn.Arn"]
    """<p>The Amazon Resource Name (ARN) of a resource (dataset). Using this parameter indicates to return only those rulesets that are associated with the specified resource.</p>"""
    max_results: NotRequired["aws_sdk_databrew.types.max_results100.MaxResults100"]
    """<p>The maximum number of results to return in this request.</p>"""
    next_token: NotRequired["aws_sdk_databrew.types.next_token.NextToken"]
    """<p>A token generated by DataBrew that specifies where to continue pagination if a previous request was truncated. To get the next set of pages, pass in the NextToken value from the response object of the previous page call.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ListRulesetsRequest) -> dict:
    out: dict = {}
    return out


def deserialize_json(data: dict) -> ListRulesetsRequest:
    out: ListRulesetsRequest = {}  # type: ignore[typeddict-item]
    return out
