"""Generated from Smithy shape ``com.amazonaws.databrew#Output``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_databrew.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_databrew.types.column_name_list
    import aws_sdk_databrew.types.compression_format
    import aws_sdk_databrew.types.max_output_files
    import aws_sdk_databrew.types.output_format
    import aws_sdk_databrew.types.output_format_options
    import aws_sdk_databrew.types.overwrite_output
    import aws_sdk_databrew.types.s3_location


class Output(TypedDict, closed=True):
    compression_format: NotRequired[
        "aws_sdk_databrew.types.compression_format.CompressionFormat"
    ]
    """<p>The compression algorithm used to compress the output text of the job.</p>"""
    format: NotRequired["aws_sdk_databrew.types.output_format.OutputFormat"]
    """<p>The data format of the output of the job.</p>"""
    partition_columns: NotRequired[
        "aws_sdk_databrew.types.column_name_list.ColumnNameList"
    ]
    """<p>The names of one or more partition columns for the output of the job.</p>"""
    location: "aws_sdk_databrew.types.s3_location.S3Location"
    """<p>The location in Amazon S3 where the job writes its output.</p>"""
    overwrite: "aws_sdk_databrew.types.overwrite_output.OverwriteOutput"
    """<p>A value that, if true, means that any data in the location specified for output is overwritten with new output.</p>"""
    format_options: NotRequired[
        "aws_sdk_databrew.types.output_format_options.OutputFormatOptions"
    ]
    """<p>Represents options that define how DataBrew formats job output files.</p>"""
    max_output_files: NotRequired[
        "aws_sdk_databrew.types.max_output_files.MaxOutputFiles"
    ]
    """<p>Maximum number of files to be generated by the job and written to the output folder. For output partitioned by column(s), the MaxOutputFiles value is the maximum number of files per partition.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: Output) -> dict:
    out: dict = {}
    if "compression_format" in value:
        import aws_sdk_databrew.types.compression_format

        out["CompressionFormat"] = (
            aws_sdk_databrew.types.compression_format.serialize_json(
                value["compression_format"]
            )
        )
    if "format" in value:
        import aws_sdk_databrew.types.output_format

        out["Format"] = aws_sdk_databrew.types.output_format.serialize_json(
            value["format"]
        )
    if "partition_columns" in value:
        import aws_sdk_databrew.types.column_name_list

        out["PartitionColumns"] = (
            aws_sdk_databrew.types.column_name_list.serialize_json(
                value["partition_columns"]
            )
        )
    import aws_sdk_databrew.types.s3_location

    out["Location"] = aws_sdk_databrew.types.s3_location.serialize_json(
        value["location"]
    )
    out["Overwrite"] = value.get("overwrite", False)
    if "format_options" in value:
        import aws_sdk_databrew.types.output_format_options

        out["FormatOptions"] = (
            aws_sdk_databrew.types.output_format_options.serialize_json(
                value["format_options"]
            )
        )
    if "max_output_files" in value:
        out["MaxOutputFiles"] = value["max_output_files"]
    return out


def deserialize_json(data: dict) -> Output:
    out: Output = {}  # type: ignore[typeddict-item]
    if "CompressionFormat" in data:
        import aws_sdk_databrew.types.compression_format

        out["compression_format"] = (
            aws_sdk_databrew.types.compression_format.deserialize_json(
                data["CompressionFormat"]
            )
        )
    if "Format" in data:
        import aws_sdk_databrew.types.output_format

        out["format"] = aws_sdk_databrew.types.output_format.deserialize_json(
            data["Format"]
        )
    if "PartitionColumns" in data:
        import aws_sdk_databrew.types.column_name_list

        out["partition_columns"] = (
            aws_sdk_databrew.types.column_name_list.deserialize_json(
                data["PartitionColumns"]
            )
        )
    if "Location" in data:
        import aws_sdk_databrew.types.s3_location

        out["location"] = aws_sdk_databrew.types.s3_location.deserialize_json(
            data["Location"]
        )
    else:
        raise DeserializationError("Output.location required")
    if "Overwrite" in data:
        out["overwrite"] = data["Overwrite"]
    else:
        out["overwrite"] = False
    if "FormatOptions" in data:
        import aws_sdk_databrew.types.output_format_options

        out["format_options"] = (
            aws_sdk_databrew.types.output_format_options.deserialize_json(
                data["FormatOptions"]
            )
        )
    if "MaxOutputFiles" in data:
        out["max_output_files"] = data["MaxOutputFiles"]
    return out
