"""Generated from Smithy shape ``com.amazonaws.amplify#StartDeploymentRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import aws_sdk_amplify.types.app_id
    import aws_sdk_amplify.types.branch_name
    import aws_sdk_amplify.types.job_id
    import aws_sdk_amplify.types.source_url
    import aws_sdk_amplify.types.source_url_type


class StartDeploymentRequest(TypedDict, closed=True):
    app_id: "aws_sdk_amplify.types.app_id.AppId"
    """<p>The unique ID for an Amplify app. </p>"""
    branch_name: "aws_sdk_amplify.types.branch_name.BranchName"
    """<p>The name of the branch to use for the deployment job. </p>"""
    job_id: NotRequired["aws_sdk_amplify.types.job_id.JobId"]
    """<p>The job ID for this deployment that is generated by the <code>CreateDeployment</code> request. </p>"""
    source_url: NotRequired["aws_sdk_amplify.types.source_url.SourceUrl"]
    """<p>The source URL for the deployment that is used when calling <code>StartDeployment</code> without <code>CreateDeployment</code>. The source URL can be either an HTTP GET URL that is publicly accessible and downloads a single .zip file, or an Amazon S3 bucket and prefix.</p>"""
    source_url_type: NotRequired["aws_sdk_amplify.types.source_url_type.SourceUrlType"]
    """<p>The type of source specified by the <code>sourceURL</code>. If the value is <code>ZIP</code>, the source is a .zip file. If the value is <code>BUCKET_PREFIX</code>, the source is an Amazon S3 bucket and prefix. If no value is specified, the default is <code>ZIP</code>.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: StartDeploymentRequest) -> dict:
    out: dict = {}
    if "job_id" in value:
        out["jobId"] = value["job_id"]
    if "source_url" in value:
        out["sourceUrl"] = value["source_url"]
    if "source_url_type" in value:
        import aws_sdk_amplify.types.source_url_type

        out["sourceUrlType"] = aws_sdk_amplify.types.source_url_type.serialize_json(
            value["source_url_type"]
        )
    return out


def deserialize_json(data: dict) -> StartDeploymentRequest:
    out: StartDeploymentRequest = {}  # type: ignore[typeddict-item]
    if "jobId" in data:
        out["job_id"] = data["jobId"]
    if "sourceUrl" in data:
        out["source_url"] = data["sourceUrl"]
    if "sourceUrlType" in data:
        import aws_sdk_amplify.types.source_url_type

        out["source_url_type"] = aws_sdk_amplify.types.source_url_type.deserialize_json(
            data["sourceUrlType"]
        )
    return out
