"""Generated from Smithy shape ``com.amazonaws.omics#StartAnnotationImportRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_omics.errors import DeserializationError

if TYPE_CHECKING:
    import capo_omics.types.annotation_field_map
    import capo_omics.types.annotation_import_item_sources
    import capo_omics.types.arn
    import capo_omics.types.format_options
    import capo_omics.types.run_left_normalization
    import capo_omics.types.store_name
    import capo_omics.types.version_name


class StartAnnotationImportRequest(TypedDict, closed=True):
    destination_name: "capo_omics.types.store_name.StoreName"
    """<p>A destination annotation store for the job.</p>"""
    role_arn: "capo_omics.types.arn.Arn"
    """<p>A service role for the job.</p>"""
    items: "capo_omics.types.annotation_import_item_sources.AnnotationImportItemSources"
    """<p>Items to import.</p>"""
    version_name: NotRequired["capo_omics.types.version_name.VersionName"]
    """<p> The name of the annotation store version. </p>"""
    format_options: NotRequired["capo_omics.types.format_options.FormatOptions"]
    """<p>Formatting options for the annotation file.</p>"""
    run_left_normalization: (
        "capo_omics.types.run_left_normalization.RunLeftNormalization"
    )
    """<p>The job's left normalization setting.</p>"""
    annotation_fields: NotRequired[
        "capo_omics.types.annotation_field_map.AnnotationFieldMap"
    ]
    """<p>The annotation schema generated by the parsed annotation data.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: StartAnnotationImportRequest) -> dict:
    out: dict = {}
    out["destinationName"] = value["destination_name"]
    out["roleArn"] = value["role_arn"]
    import capo_omics.types.annotation_import_item_sources

    out["items"] = capo_omics.types.annotation_import_item_sources.serialize_json(
        value["items"]
    )
    if "version_name" in value:
        out["versionName"] = value["version_name"]
    if "format_options" in value:
        import capo_omics.types.format_options

        out["formatOptions"] = capo_omics.types.format_options.serialize_json(
            value["format_options"]
        )
    out["runLeftNormalization"] = value.get("run_left_normalization", False)
    if "annotation_fields" in value:
        import capo_omics.types.annotation_field_map

        out["annotationFields"] = capo_omics.types.annotation_field_map.serialize_json(
            value["annotation_fields"]
        )
    return out


def deserialize_json(data: dict) -> StartAnnotationImportRequest:
    out: StartAnnotationImportRequest = {}  # type: ignore[typeddict-item]
    if "destinationName" in data:
        out["destination_name"] = data["destinationName"]
    else:
        raise DeserializationError(
            "StartAnnotationImportRequest.destination_name required"
        )
    if "roleArn" in data:
        out["role_arn"] = data["roleArn"]
    else:
        raise DeserializationError("StartAnnotationImportRequest.role_arn required")
    if "items" in data:
        import capo_omics.types.annotation_import_item_sources

        out["items"] = capo_omics.types.annotation_import_item_sources.deserialize_json(
            data["items"]
        )
    else:
        raise DeserializationError("StartAnnotationImportRequest.items required")
    if "versionName" in data:
        out["version_name"] = data["versionName"]
    if "formatOptions" in data:
        import capo_omics.types.format_options

        out["format_options"] = capo_omics.types.format_options.deserialize_json(
            data["formatOptions"]
        )
    if "runLeftNormalization" in data:
        out["run_left_normalization"] = data["runLeftNormalization"]
    else:
        out["run_left_normalization"] = False
    if "annotationFields" in data:
        import capo_omics.types.annotation_field_map

        out["annotation_fields"] = (
            capo_omics.types.annotation_field_map.deserialize_json(
                data["annotationFields"]
            )
        )
    return out
