"""Generated from Smithy shape ``com.amazonaws.lightsail#UpdateRelationalDatabaseRequest``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

from aws_sdk_lightsail.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_lightsail.types.boolean
    import aws_sdk_lightsail.types.resource_name
    import aws_sdk_lightsail.types.sensitive_string
    import aws_sdk_lightsail.types.string


class UpdateRelationalDatabaseRequest(TypedDict):
    relational_database_name: "aws_sdk_lightsail.types.resource_name.ResourceName"
    """<p>The name of your Lightsail database resource to update.</p>"""
    master_user_password: NotRequired[
        "aws_sdk_lightsail.types.sensitive_string.SensitiveString"
    ]
    r"""<p>The password for the master user. The password can include any printable ASCII character except \"/\", \"\"\", or \"@\".</p> <p>My<b>SQL</b> </p> <p>Constraints: Must contain from 8 to 41 characters.</p> <p> <b>PostgreSQL</b> </p> <p>Constraints: Must contain from 8 to 128 characters.</p>"""
    rotate_master_user_password: NotRequired["aws_sdk_lightsail.types.boolean.boolean"]
    """<p>When <code>true</code>, the master user password is changed to a new strong password generated by Lightsail.</p> <p>Use the <code>get relational database master user password</code> operation to get the new password.</p>"""
    preferred_backup_window: NotRequired["aws_sdk_lightsail.types.string.string"]
    """<p>The daily time range during which automated backups are created for your database if automated backups are enabled.</p> <p>Constraints:</p> <ul> <li> <p>Must be in the <code>hh24:mi-hh24:mi</code> format.</p> <p>Example: <code>16:00-16:30</code> </p> </li> <li> <p>Specified in Coordinated Universal Time (UTC).</p> </li> <li> <p>Must not conflict with the preferred maintenance window.</p> </li> <li> <p>Must be at least 30 minutes.</p> </li> </ul>"""
    preferred_maintenance_window: NotRequired["aws_sdk_lightsail.types.string.string"]
    """<p>The weekly time range during which system maintenance can occur on your database.</p> <p>The default is a 30-minute window selected at random from an 8-hour block of time for each Amazon Web Services Region, occurring on a random day of the week.</p> <p>Constraints:</p> <ul> <li> <p>Must be in the <code>ddd:hh24:mi-ddd:hh24:mi</code> format.</p> </li> <li> <p>Valid days: Mon, Tue, Wed, Thu, Fri, Sat, Sun.</p> </li> <li> <p>Must be at least 30 minutes.</p> </li> <li> <p>Specified in Coordinated Universal Time (UTC).</p> </li> <li> <p>Example: <code>Tue:17:00-Tue:17:30</code> </p> </li> </ul>"""
    enable_backup_retention: NotRequired["aws_sdk_lightsail.types.boolean.boolean"]
    """<p>When <code>true</code>, enables automated backup retention for your database.</p> <p>Updates are applied during the next maintenance window because this can result in an outage.</p>"""
    disable_backup_retention: NotRequired["aws_sdk_lightsail.types.boolean.boolean"]
    """<p>When <code>true</code>, disables automated backup retention for your database.</p> <p>Disabling backup retention deletes all automated database backups. Before disabling this, you may want to create a snapshot of your database using the <code>create relational database snapshot</code> operation.</p> <p>Updates are applied during the next maintenance window because this can result in an outage.</p>"""
    publicly_accessible: NotRequired["aws_sdk_lightsail.types.boolean.boolean"]
    """<p>Specifies the accessibility options for your database. A value of <code>true</code> specifies a database that is available to resources outside of your Lightsail account. A value of <code>false</code> specifies a database that is available only to your Lightsail resources in the same region as your database.</p>"""
    apply_immediately: NotRequired["aws_sdk_lightsail.types.boolean.boolean"]
    """<p>When <code>true</code>, applies changes immediately. When <code>false</code>, applies changes during the preferred maintenance window. Some changes may cause an outage.</p> <p>Default: <code>false</code> </p>"""
    ca_certificate_identifier: NotRequired["aws_sdk_lightsail.types.string.string"]
    """<p>Indicates the certificate that needs to be associated with the database.</p>"""
    relational_database_blueprint_id: NotRequired[
        "aws_sdk_lightsail.types.string.string"
    ]
    r"""<p>This parameter is used to update the major version of the database. Enter the <code>blueprintId</code> for the major version that you want to update to.</p> <p>Use the <a href=\"https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_GetRelationalDatabaseBlueprints.html\">GetRelationalDatabaseBlueprints</a> action to get a list of available blueprint IDs.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: UpdateRelationalDatabaseRequest) -> dict:
    out: dict = {}
    out["relationalDatabaseName"] = value["relational_database_name"]
    if "master_user_password" in value:
        out["masterUserPassword"] = value["master_user_password"]
    if "rotate_master_user_password" in value:
        out["rotateMasterUserPassword"] = value["rotate_master_user_password"]
    if "preferred_backup_window" in value:
        out["preferredBackupWindow"] = value["preferred_backup_window"]
    if "preferred_maintenance_window" in value:
        out["preferredMaintenanceWindow"] = value["preferred_maintenance_window"]
    if "enable_backup_retention" in value:
        out["enableBackupRetention"] = value["enable_backup_retention"]
    if "disable_backup_retention" in value:
        out["disableBackupRetention"] = value["disable_backup_retention"]
    if "publicly_accessible" in value:
        out["publiclyAccessible"] = value["publicly_accessible"]
    if "apply_immediately" in value:
        out["applyImmediately"] = value["apply_immediately"]
    if "ca_certificate_identifier" in value:
        out["caCertificateIdentifier"] = value["ca_certificate_identifier"]
    if "relational_database_blueprint_id" in value:
        out["relationalDatabaseBlueprintId"] = value["relational_database_blueprint_id"]
    return out


def deserialize_aws_json_1_1(data: dict) -> UpdateRelationalDatabaseRequest:
    out: UpdateRelationalDatabaseRequest = {}  # type: ignore[typeddict-item]
    if "relationalDatabaseName" in data:
        out["relational_database_name"] = data["relationalDatabaseName"]
    else:
        raise DeserializationError(
            "UpdateRelationalDatabaseRequest.relational_database_name required"
        )
    if "masterUserPassword" in data:
        out["master_user_password"] = data["masterUserPassword"]
    if "rotateMasterUserPassword" in data:
        out["rotate_master_user_password"] = data["rotateMasterUserPassword"]
    if "preferredBackupWindow" in data:
        out["preferred_backup_window"] = data["preferredBackupWindow"]
    if "preferredMaintenanceWindow" in data:
        out["preferred_maintenance_window"] = data["preferredMaintenanceWindow"]
    if "enableBackupRetention" in data:
        out["enable_backup_retention"] = data["enableBackupRetention"]
    if "disableBackupRetention" in data:
        out["disable_backup_retention"] = data["disableBackupRetention"]
    if "publiclyAccessible" in data:
        out["publicly_accessible"] = data["publiclyAccessible"]
    if "applyImmediately" in data:
        out["apply_immediately"] = data["applyImmediately"]
    if "caCertificateIdentifier" in data:
        out["ca_certificate_identifier"] = data["caCertificateIdentifier"]
    if "relationalDatabaseBlueprintId" in data:
        out["relational_database_blueprint_id"] = data["relationalDatabaseBlueprintId"]
    return out
