"""Generated from Smithy shape ``com.amazonaws.swf#RecordActivityTaskHeartbeatInput``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

from aws_sdk_swf.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_swf.types.limited_data
    import aws_sdk_swf.types.task_token


class RecordActivityTaskHeartbeatInput(TypedDict):
    task_token: "aws_sdk_swf.types.task_token.TaskToken"
    """<p>The <code>taskToken</code> of the <a>ActivityTask</a>.</p> <important> <p> <code>taskToken</code> is generated by the service and should be treated as an opaque value. If the task is passed to another process, its <code>taskToken</code> must also be passed. This enables it to provide its progress and respond with results. </p> </important>"""
    details: NotRequired["aws_sdk_swf.types.limited_data.LimitedData"]
    """<p>If specified, contains details about the progress of the task.</p>"""


# --- awsJson1_0 ser/de ---
def serialize_aws_json_1_0(value: RecordActivityTaskHeartbeatInput) -> dict:
    out: dict = {}
    out["taskToken"] = value["task_token"]
    if "details" in value:
        out["details"] = value["details"]
    return out


def deserialize_aws_json_1_0(data: dict) -> RecordActivityTaskHeartbeatInput:
    out: RecordActivityTaskHeartbeatInput = {}  # type: ignore[typeddict-item]
    if "taskToken" in data:
        out["task_token"] = data["taskToken"]
    else:
        raise DeserializationError(
            "RecordActivityTaskHeartbeatInput.task_token required"
        )
    if "details" in data:
        out["details"] = data["details"]
    return out
