"""Generated from Smithy shape ``com.amazonaws.swf#RespondActivityTaskCanceledInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from aws_sdk_swf.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_swf.types.data
    import aws_sdk_swf.types.task_token


class RespondActivityTaskCanceledInput(TypedDict, closed=True):
    task_token: "aws_sdk_swf.types.task_token.TaskToken"
    """<p>The <code>taskToken</code> of the <a>ActivityTask</a>.</p> <important> <p> <code>taskToken</code> is generated by the service and should be treated as an opaque value. If the task is passed to another process, its <code>taskToken</code> must also be passed. This enables it to provide its progress and respond with results.</p> </important>"""
    details: NotRequired["aws_sdk_swf.types.data.Data"]
    """<p> Information about the cancellation.</p>"""


# --- awsJson1_0 ser/de ---
def serialize_aws_json_1_0(value: RespondActivityTaskCanceledInput) -> dict:
    out: dict = {}
    out["taskToken"] = value["task_token"]
    if "details" in value:
        out["details"] = value["details"]
    return out


def deserialize_aws_json_1_0(data: dict) -> RespondActivityTaskCanceledInput:
    out: RespondActivityTaskCanceledInput = {}  # type: ignore[typeddict-item]
    if "taskToken" in data:
        out["task_token"] = data["taskToken"]
    else:
        raise DeserializationError(
            "RespondActivityTaskCanceledInput.task_token required"
        )
    if "details" in data:
        out["details"] = data["details"]
    return out
