"""Generated from Smithy shape ``com.amazonaws.datazone#Timezone``."""

import datetime
import decimal
from typing import AsyncIterator, Iterator, Literal, TypeAlias, cast
from aws_sdk_datazone.errors import DeserializationError
from aws_sdk_datazone._protocol.xml import Element, SubElement
import base64
from email.utils import format_datetime as _fmt_http
from email.utils import parsedate_to_datetime as _parse_http

Timezone: TypeAlias = Literal[
    "UTC",
    "AFRICA_JOHANNESBURG",
    "AMERICA_MONTREAL",
    "AMERICA_SAO_PAULO",
    "ASIA_BAHRAIN",
    "ASIA_BANGKOK",
    "ASIA_CALCUTTA",
    "ASIA_DUBAI",
    "ASIA_HONG_KONG",
    "ASIA_JAKARTA",
    "ASIA_KUALA_LUMPUR",
    "ASIA_SEOUL",
    "ASIA_SHANGHAI",
    "ASIA_SINGAPORE",
    "ASIA_TAIPEI",
    "ASIA_TOKYO",
    "AUSTRALIA_MELBOURNE",
    "AUSTRALIA_SYDNEY",
    "CANADA_CENTRAL",
    "CET",
    "CST6CDT",
    "ETC_GMT",
    "ETC_GMT0",
    "ETC_GMT_ADD_0",
    "ETC_GMT_ADD_1",
    "ETC_GMT_ADD_10",
    "ETC_GMT_ADD_11",
    "ETC_GMT_ADD_12",
    "ETC_GMT_ADD_2",
    "ETC_GMT_ADD_3",
    "ETC_GMT_ADD_4",
    "ETC_GMT_ADD_5",
    "ETC_GMT_ADD_6",
    "ETC_GMT_ADD_7",
    "ETC_GMT_ADD_8",
    "ETC_GMT_ADD_9",
    "ETC_GMT_NEG_0",
    "ETC_GMT_NEG_1",
    "ETC_GMT_NEG_10",
    "ETC_GMT_NEG_11",
    "ETC_GMT_NEG_12",
    "ETC_GMT_NEG_13",
    "ETC_GMT_NEG_14",
    "ETC_GMT_NEG_2",
    "ETC_GMT_NEG_3",
    "ETC_GMT_NEG_4",
    "ETC_GMT_NEG_5",
    "ETC_GMT_NEG_6",
    "ETC_GMT_NEG_7",
    "ETC_GMT_NEG_8",
    "ETC_GMT_NEG_9",
    "EUROPE_DUBLIN",
    "EUROPE_LONDON",
    "EUROPE_PARIS",
    "EUROPE_STOCKHOLM",
    "EUROPE_ZURICH",
    "ISRAEL",
    "MEXICO_GENERAL",
    "MST7MDT",
    "PACIFIC_AUCKLAND",
    "US_CENTRAL",
    "US_EASTERN",
    "US_MOUNTAIN",
    "US_PACIFIC",
]


# --- restJson1 ser/de ---
_VALUES: frozenset[str] = frozenset(
    (
        "UTC",
        "AFRICA_JOHANNESBURG",
        "AMERICA_MONTREAL",
        "AMERICA_SAO_PAULO",
        "ASIA_BAHRAIN",
        "ASIA_BANGKOK",
        "ASIA_CALCUTTA",
        "ASIA_DUBAI",
        "ASIA_HONG_KONG",
        "ASIA_JAKARTA",
        "ASIA_KUALA_LUMPUR",
        "ASIA_SEOUL",
        "ASIA_SHANGHAI",
        "ASIA_SINGAPORE",
        "ASIA_TAIPEI",
        "ASIA_TOKYO",
        "AUSTRALIA_MELBOURNE",
        "AUSTRALIA_SYDNEY",
        "CANADA_CENTRAL",
        "CET",
        "CST6CDT",
        "ETC_GMT",
        "ETC_GMT0",
        "ETC_GMT_ADD_0",
        "ETC_GMT_ADD_1",
        "ETC_GMT_ADD_10",
        "ETC_GMT_ADD_11",
        "ETC_GMT_ADD_12",
        "ETC_GMT_ADD_2",
        "ETC_GMT_ADD_3",
        "ETC_GMT_ADD_4",
        "ETC_GMT_ADD_5",
        "ETC_GMT_ADD_6",
        "ETC_GMT_ADD_7",
        "ETC_GMT_ADD_8",
        "ETC_GMT_ADD_9",
        "ETC_GMT_NEG_0",
        "ETC_GMT_NEG_1",
        "ETC_GMT_NEG_10",
        "ETC_GMT_NEG_11",
        "ETC_GMT_NEG_12",
        "ETC_GMT_NEG_13",
        "ETC_GMT_NEG_14",
        "ETC_GMT_NEG_2",
        "ETC_GMT_NEG_3",
        "ETC_GMT_NEG_4",
        "ETC_GMT_NEG_5",
        "ETC_GMT_NEG_6",
        "ETC_GMT_NEG_7",
        "ETC_GMT_NEG_8",
        "ETC_GMT_NEG_9",
        "EUROPE_DUBLIN",
        "EUROPE_LONDON",
        "EUROPE_PARIS",
        "EUROPE_STOCKHOLM",
        "EUROPE_ZURICH",
        "ISRAEL",
        "MEXICO_GENERAL",
        "MST7MDT",
        "PACIFIC_AUCKLAND",
        "US_CENTRAL",
        "US_EASTERN",
        "US_MOUNTAIN",
        "US_PACIFIC",
    )
)


def serialize_json(value: Timezone) -> str:
    return value


def deserialize_json(data: str) -> Timezone:
    if data not in _VALUES:
        raise DeserializationError(f"unknown Timezone value: {data!r}")
    return cast(Timezone, data)
