"""Generated from Smithy shape ``com.amazonaws.bedrockruntime#GuardrailContextualGroundingFilter``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_bedrock_runtime.errors import DeserializationError

if TYPE_CHECKING:
    import capo_bedrock_runtime.types.guardrail_contextual_grounding_filter_type
    import capo_bedrock_runtime.types.guardrail_contextual_grounding_policy_action


class GuardrailContextualGroundingFilter(TypedDict, closed=True):
    type: "capo_bedrock_runtime.types.guardrail_contextual_grounding_filter_type.GuardrailContextualGroundingFilterType"
    """<p>The contextual grounding filter type.</p>"""
    threshold: "float"
    """<p>The threshold used by contextual grounding filter to determine whether the content is grounded or not.</p>"""
    score: "float"
    """<p>The score generated by contextual grounding filter.</p>"""
    action: "capo_bedrock_runtime.types.guardrail_contextual_grounding_policy_action.GuardrailContextualGroundingPolicyAction"
    """<p>The action performed by the guardrails contextual grounding filter.</p>"""
    detected: NotRequired["bool"]
    """<p>Indicates whether content that fails the contextual grounding evaluation (grounding or relevance score less than the corresponding threshold) was detected.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: GuardrailContextualGroundingFilter) -> dict:
    out: dict = {}
    import capo_bedrock_runtime.types.guardrail_contextual_grounding_filter_type

    out["type"] = (
        capo_bedrock_runtime.types.guardrail_contextual_grounding_filter_type.serialize_json(
            value["type"]
        )
    )
    out["threshold"] = (
        "NaN"
        if value["threshold"] != value["threshold"]
        else "Infinity"
        if value["threshold"] == float("inf")
        else "-Infinity"
        if value["threshold"] == float("-inf")
        else value["threshold"]
    )
    out["score"] = (
        "NaN"
        if value["score"] != value["score"]
        else "Infinity"
        if value["score"] == float("inf")
        else "-Infinity"
        if value["score"] == float("-inf")
        else value["score"]
    )
    import capo_bedrock_runtime.types.guardrail_contextual_grounding_policy_action

    out["action"] = (
        capo_bedrock_runtime.types.guardrail_contextual_grounding_policy_action.serialize_json(
            value["action"]
        )
    )
    if "detected" in value:
        out["detected"] = value["detected"]
    return out


def deserialize_json(data: dict) -> GuardrailContextualGroundingFilter:
    out: GuardrailContextualGroundingFilter = {}  # type: ignore[typeddict-item]
    if data.get("type") is not None:
        import capo_bedrock_runtime.types.guardrail_contextual_grounding_filter_type

        out["type"] = (
            capo_bedrock_runtime.types.guardrail_contextual_grounding_filter_type.deserialize_json(
                data["type"]
            )
        )
    else:
        raise DeserializationError("GuardrailContextualGroundingFilter.type required")
    if data.get("threshold") is not None:
        out["threshold"] = float(data["threshold"])
    else:
        raise DeserializationError(
            "GuardrailContextualGroundingFilter.threshold required"
        )
    if data.get("score") is not None:
        out["score"] = float(data["score"])
    else:
        raise DeserializationError("GuardrailContextualGroundingFilter.score required")
    if data.get("action") is not None:
        import capo_bedrock_runtime.types.guardrail_contextual_grounding_policy_action

        out["action"] = (
            capo_bedrock_runtime.types.guardrail_contextual_grounding_policy_action.deserialize_json(
                data["action"]
            )
        )
    else:
        raise DeserializationError("GuardrailContextualGroundingFilter.action required")
    if data.get("detected") is not None:
        out["detected"] = data["detected"]
    return out
