"""Generated from Smithy shape ``com.amazonaws.apigatewayv2#UpdateRouteRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_apigatewayv2.types.__boolean
    import capo_apigatewayv2.types.__string
    import capo_apigatewayv2.types.authorization_scopes
    import capo_apigatewayv2.types.authorization_type
    import capo_apigatewayv2.types.id
    import capo_apigatewayv2.types.route_models
    import capo_apigatewayv2.types.route_parameters
    import capo_apigatewayv2.types.selection_expression
    import capo_apigatewayv2.types.selection_key
    import capo_apigatewayv2.types.string_with_length_between1_and64
    import capo_apigatewayv2.types.string_with_length_between1_and128


class UpdateRouteRequest(TypedDict, closed=True):
    api_id: "capo_apigatewayv2.types.__string.__string"
    """<p>The API identifier.</p>"""
    api_key_required: NotRequired["capo_apigatewayv2.types.__boolean.__boolean"]
    """<p>Specifies whether an API key is required for the route. Supported only for WebSocket APIs.</p>"""
    authorization_scopes: NotRequired[
        "capo_apigatewayv2.types.authorization_scopes.AuthorizationScopes"
    ]
    """<p>The authorization scopes supported by this route.</p>"""
    authorization_type: NotRequired[
        "capo_apigatewayv2.types.authorization_type.AuthorizationType"
    ]
    """<p>The authorization type for the route. For WebSocket APIs, valid values are NONE for open access, AWS_IAM for using AWS IAM permissions, and CUSTOM for using a Lambda authorizer For HTTP APIs, valid values are NONE for open access, JWT for using JSON Web Tokens, AWS_IAM for using AWS IAM permissions, and CUSTOM for using a Lambda authorizer.</p>"""
    authorizer_id: NotRequired["capo_apigatewayv2.types.id.Id"]
    """<p>The identifier of the Authorizer resource to be associated with this route. The authorizer identifier is generated by API Gateway when you created the authorizer.</p>"""
    model_selection_expression: NotRequired[
        "capo_apigatewayv2.types.selection_expression.SelectionExpression"
    ]
    """<p>The model selection expression for the route. Supported only for WebSocket APIs.</p>"""
    operation_name: NotRequired[
        "capo_apigatewayv2.types.string_with_length_between1_and64.StringWithLengthBetween1And64"
    ]
    """<p>The operation name for the route.</p>"""
    request_models: NotRequired["capo_apigatewayv2.types.route_models.RouteModels"]
    """<p>The request models for the route. Supported only for WebSocket APIs.</p>"""
    request_parameters: NotRequired[
        "capo_apigatewayv2.types.route_parameters.RouteParameters"
    ]
    """<p>The request parameters for the route. Supported only for WebSocket APIs.</p>"""
    route_id: "capo_apigatewayv2.types.__string.__string"
    """<p>The route ID.</p>"""
    route_key: NotRequired["capo_apigatewayv2.types.selection_key.SelectionKey"]
    """<p>The route key for the route.</p>"""
    route_response_selection_expression: NotRequired[
        "capo_apigatewayv2.types.selection_expression.SelectionExpression"
    ]
    """<p>The route response selection expression for the route. Supported only for WebSocket APIs.</p>"""
    target: NotRequired[
        "capo_apigatewayv2.types.string_with_length_between1_and128.StringWithLengthBetween1And128"
    ]
    """<p>The target for the route.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: UpdateRouteRequest) -> dict:
    out: dict = {}
    if "api_key_required" in value:
        out["apiKeyRequired"] = value["api_key_required"]
    if "authorization_scopes" in value:
        import capo_apigatewayv2.types.authorization_scopes

        out["authorizationScopes"] = (
            capo_apigatewayv2.types.authorization_scopes.serialize_json(
                value["authorization_scopes"]
            )
        )
    if "authorization_type" in value:
        import capo_apigatewayv2.types.authorization_type

        out["authorizationType"] = (
            capo_apigatewayv2.types.authorization_type.serialize_json(
                value["authorization_type"]
            )
        )
    if "authorizer_id" in value:
        out["authorizerId"] = value["authorizer_id"]
    if "model_selection_expression" in value:
        out["modelSelectionExpression"] = value["model_selection_expression"]
    if "operation_name" in value:
        out["operationName"] = value["operation_name"]
    if "request_models" in value:
        import capo_apigatewayv2.types.route_models

        out["requestModels"] = capo_apigatewayv2.types.route_models.serialize_json(
            value["request_models"]
        )
    if "request_parameters" in value:
        import capo_apigatewayv2.types.route_parameters

        out["requestParameters"] = (
            capo_apigatewayv2.types.route_parameters.serialize_json(
                value["request_parameters"]
            )
        )
    if "route_key" in value:
        out["routeKey"] = value["route_key"]
    if "route_response_selection_expression" in value:
        out["routeResponseSelectionExpression"] = value[
            "route_response_selection_expression"
        ]
    if "target" in value:
        out["target"] = value["target"]
    return out


def deserialize_json(data: dict) -> UpdateRouteRequest:
    out: UpdateRouteRequest = {}  # type: ignore[typeddict-item]
    if "apiKeyRequired" in data:
        out["api_key_required"] = data["apiKeyRequired"]
    if "authorizationScopes" in data:
        import capo_apigatewayv2.types.authorization_scopes

        out["authorization_scopes"] = (
            capo_apigatewayv2.types.authorization_scopes.deserialize_json(
                data["authorizationScopes"]
            )
        )
    if "authorizationType" in data:
        import capo_apigatewayv2.types.authorization_type

        out["authorization_type"] = (
            capo_apigatewayv2.types.authorization_type.deserialize_json(
                data["authorizationType"]
            )
        )
    if "authorizerId" in data:
        out["authorizer_id"] = data["authorizerId"]
    if "modelSelectionExpression" in data:
        out["model_selection_expression"] = data["modelSelectionExpression"]
    if "operationName" in data:
        out["operation_name"] = data["operationName"]
    if "requestModels" in data:
        import capo_apigatewayv2.types.route_models

        out["request_models"] = capo_apigatewayv2.types.route_models.deserialize_json(
            data["requestModels"]
        )
    if "requestParameters" in data:
        import capo_apigatewayv2.types.route_parameters

        out["request_parameters"] = (
            capo_apigatewayv2.types.route_parameters.deserialize_json(
                data["requestParameters"]
            )
        )
    if "routeKey" in data:
        out["route_key"] = data["routeKey"]
    if "routeResponseSelectionExpression" in data:
        out["route_response_selection_expression"] = data[
            "routeResponseSelectionExpression"
        ]
    if "target" in data:
        out["target"] = data["target"]
    return out
