"""Generated from Smithy shape ``com.amazonaws.redshift#ModifyEventSubscriptionMessage``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_redshift._protocol.xml import Element

if TYPE_CHECKING:
    import capo_redshift.types.boolean_optional
    import capo_redshift.types.event_categories_list
    import capo_redshift.types.source_ids_list
    import capo_redshift.types.string


class ModifyEventSubscriptionMessage(TypedDict, closed=True):
    subscription_name: NotRequired["capo_redshift.types.string.String"]
    """<p>The name of the modified Amazon Redshift event notification subscription.</p>"""
    sns_topic_arn: NotRequired["capo_redshift.types.string.String"]
    """<p>The Amazon Resource Name (ARN) of the SNS topic to be used by the event notification subscription.</p>"""
    source_type: NotRequired["capo_redshift.types.string.String"]
    """<p>The type of source that will be generating the events. For example, if you want to be notified of events generated by a cluster, you would set this parameter to cluster. If this value is not specified, events are returned for all Amazon Redshift objects in your Amazon Web Services account. You must specify a source type in order to specify source IDs.</p> <p>Valid values: cluster, cluster-parameter-group, cluster-security-group, cluster-snapshot, and scheduled-action.</p>"""
    source_ids: NotRequired["capo_redshift.types.source_ids_list.SourceIdsList"]
    """<p>A list of one or more identifiers of Amazon Redshift source objects. All of the objects must be of the same type as was specified in the source type parameter. The event subscription will return only events generated by the specified objects. If not specified, then events are returned for all objects within the source type specified.</p> <p>Example: my-cluster-1, my-cluster-2</p> <p>Example: my-snapshot-20131010</p>"""
    event_categories: NotRequired[
        "capo_redshift.types.event_categories_list.EventCategoriesList"
    ]
    """<p>Specifies the Amazon Redshift event categories to be published by the event notification subscription.</p> <p>Values: configuration, management, monitoring, security, pending</p>"""
    severity: NotRequired["capo_redshift.types.string.String"]
    """<p>Specifies the Amazon Redshift event severity to be published by the event notification subscription.</p> <p>Values: ERROR, INFO</p>"""
    enabled: NotRequired["capo_redshift.types.boolean_optional.BooleanOptional"]
    """<p>A Boolean value indicating if the subscription is enabled. <code>true</code> indicates the subscription is enabled </p>"""


# --- awsQuery ser/de ---
def serialize_query(
    value: ModifyEventSubscriptionMessage, pairs: list[tuple[str, str]], prefix: str
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    if "subscription_name" in value:
        pairs.append((f"{key_prefix}SubscriptionName", str(value["subscription_name"])))
    if "sns_topic_arn" in value:
        pairs.append((f"{key_prefix}SnsTopicArn", str(value["sns_topic_arn"])))
    if "source_type" in value:
        pairs.append((f"{key_prefix}SourceType", str(value["source_type"])))
    if "source_ids" in value:
        import capo_redshift.types.source_ids_list

        capo_redshift.types.source_ids_list.serialize_query(
            value["source_ids"], pairs, f"{key_prefix}SourceIds"
        )
    if "event_categories" in value:
        import capo_redshift.types.event_categories_list

        capo_redshift.types.event_categories_list.serialize_query(
            value["event_categories"], pairs, f"{key_prefix}EventCategories"
        )
    if "severity" in value:
        pairs.append((f"{key_prefix}Severity", str(value["severity"])))
    if "enabled" in value:
        pairs.append((f"{key_prefix}Enabled", "true" if value["enabled"] else "false"))


def deserialize_query(el: Element) -> ModifyEventSubscriptionMessage:
    out: ModifyEventSubscriptionMessage = {}  # type: ignore[typeddict-item]
    child_subscription_name = el.find("SubscriptionName")
    if child_subscription_name is not None:
        out["subscription_name"] = str(child_subscription_name.text or "")
    child_sns_topic_arn = el.find("SnsTopicArn")
    if child_sns_topic_arn is not None:
        out["sns_topic_arn"] = str(child_sns_topic_arn.text or "")
    child_source_type = el.find("SourceType")
    if child_source_type is not None:
        out["source_type"] = str(child_source_type.text or "")
    child_source_ids = el.find("SourceIds")
    if child_source_ids is not None:
        import capo_redshift.types.source_ids_list

        out["source_ids"] = capo_redshift.types.source_ids_list.deserialize_query(
            child_source_ids
        )
    child_event_categories = el.find("EventCategories")
    if child_event_categories is not None:
        import capo_redshift.types.event_categories_list

        out["event_categories"] = (
            capo_redshift.types.event_categories_list.deserialize_query(
                child_event_categories
            )
        )
    child_severity = el.find("Severity")
    if child_severity is not None:
        out["severity"] = str(child_severity.text or "")
    child_enabled = el.find("Enabled")
    if child_enabled is not None:
        out["enabled"] = (child_enabled.text or "").lower() == "true"
    return out
