"""Generated from Smithy shape ``com.amazonaws.customerprofiles#GetProfileRecommendationsResponse``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

if TYPE_CHECKING:
    import aws_sdk_customer_profiles.types.recommendations


class GetProfileRecommendationsResponse(TypedDict):
    recommendations: NotRequired[
        "aws_sdk_customer_profiles.types.recommendations.Recommendations"
    ]
    """<p>List of recommendations generated by the recommender.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: GetProfileRecommendationsResponse) -> dict:
    out: dict = {}
    if "recommendations" in value:
        import aws_sdk_customer_profiles.types.recommendations

        out["Recommendations"] = (
            aws_sdk_customer_profiles.types.recommendations.serialize_json(
                value["recommendations"]
            )
        )
    return out


def deserialize_json(data: dict) -> GetProfileRecommendationsResponse:
    out: GetProfileRecommendationsResponse = {}  # type: ignore[typeddict-item]
    if "Recommendations" in data:
        import aws_sdk_customer_profiles.types.recommendations

        out["recommendations"] = (
            aws_sdk_customer_profiles.types.recommendations.deserialize_json(
                data["Recommendations"]
            )
        )
    return out
