"""Generated from Smithy shape ``com.amazonaws.customerprofiles#ProfileHistoryRecord``."""

from typing import TYPE_CHECKING, TypedDict

from typing_extensions import NotRequired

from aws_sdk_customer_profiles.errors import DeserializationError

if TYPE_CHECKING:
    import aws_sdk_customer_profiles.types.action_type
    import aws_sdk_customer_profiles.types.string1_to255
    import aws_sdk_customer_profiles.types.timestamp
    import aws_sdk_customer_profiles.types.type_name
    import aws_sdk_customer_profiles.types.uuid


class ProfileHistoryRecord(TypedDict):
    id: "aws_sdk_customer_profiles.types.uuid.uuid"
    """<p>The unique identifier of the profile history record.</p>"""
    object_type_name: "aws_sdk_customer_profiles.types.type_name.typeName"
    """<p>The name of the profile object type.</p>"""
    created_at: "aws_sdk_customer_profiles.types.timestamp.timestamp"
    """<p>The timestamp of when the profile history record was created.</p>"""
    last_updated_at: NotRequired["aws_sdk_customer_profiles.types.timestamp.timestamp"]
    """<p>The timestamp of when the profile history record was last updated.</p>"""
    action_type: "aws_sdk_customer_profiles.types.action_type.ActionType"
    """<p>The action type of the profile history record.</p>"""
    profile_object_unique_key: NotRequired[
        "aws_sdk_customer_profiles.types.string1_to255.string1To255"
    ]
    """<p>The unique identifier of the profile object generated by the service.</p>"""
    performed_by: NotRequired[
        "aws_sdk_customer_profiles.types.string1_to255.string1To255"
    ]
    """<p>The Amazon Resource Name (ARN) of the person or service principal who performed the action.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ProfileHistoryRecord) -> dict:
    out: dict = {}
    out["Id"] = value["id"]
    out["ObjectTypeName"] = value["object_type_name"]
    import aws_sdk_customer_profiles.types.timestamp

    out["CreatedAt"] = aws_sdk_customer_profiles.types.timestamp.serialize_json(
        value["created_at"]
    )
    if "last_updated_at" in value:
        import aws_sdk_customer_profiles.types.timestamp

        out["LastUpdatedAt"] = aws_sdk_customer_profiles.types.timestamp.serialize_json(
            value["last_updated_at"]
        )
    import aws_sdk_customer_profiles.types.action_type

    out["ActionType"] = aws_sdk_customer_profiles.types.action_type.serialize_json(
        value["action_type"]
    )
    if "profile_object_unique_key" in value:
        out["ProfileObjectUniqueKey"] = value["profile_object_unique_key"]
    if "performed_by" in value:
        out["PerformedBy"] = value["performed_by"]
    return out


def deserialize_json(data: dict) -> ProfileHistoryRecord:
    out: ProfileHistoryRecord = {}  # type: ignore[typeddict-item]
    if "Id" in data:
        out["id"] = data["Id"]
    else:
        raise DeserializationError("ProfileHistoryRecord.id required")
    if "ObjectTypeName" in data:
        out["object_type_name"] = data["ObjectTypeName"]
    else:
        raise DeserializationError("ProfileHistoryRecord.object_type_name required")
    if "CreatedAt" in data:
        import aws_sdk_customer_profiles.types.timestamp

        out["created_at"] = aws_sdk_customer_profiles.types.timestamp.deserialize_json(
            data["CreatedAt"]
        )
    else:
        raise DeserializationError("ProfileHistoryRecord.created_at required")
    if "LastUpdatedAt" in data:
        import aws_sdk_customer_profiles.types.timestamp

        out["last_updated_at"] = (
            aws_sdk_customer_profiles.types.timestamp.deserialize_json(
                data["LastUpdatedAt"]
            )
        )
    if "ActionType" in data:
        import aws_sdk_customer_profiles.types.action_type

        out["action_type"] = (
            aws_sdk_customer_profiles.types.action_type.deserialize_json(
                data["ActionType"]
            )
        )
    else:
        raise DeserializationError("ProfileHistoryRecord.action_type required")
    if "ProfileObjectUniqueKey" in data:
        out["profile_object_unique_key"] = data["ProfileObjectUniqueKey"]
    if "PerformedBy" in data:
        out["performed_by"] = data["PerformedBy"]
    return out
