"""Generated from Smithy shape ``com.amazonaws.qbusiness#MetadataEvent``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_qbusiness._protocol.eventstream import HeaderValue, Message

if TYPE_CHECKING:
    import capo_qbusiness.types.conversation_id
    import capo_qbusiness.types.message_id
    import capo_qbusiness.types.source_attributions
    import capo_qbusiness.types.string


class MetadataEvent(TypedDict, closed=True):
    conversation_id: NotRequired["capo_qbusiness.types.conversation_id.ConversationId"]
    """<p>The identifier of the conversation with which the generated metadata is associated.</p>"""
    user_message_id: NotRequired["capo_qbusiness.types.message_id.MessageId"]
    """<p>The identifier of an Amazon Q Business end user text input message within the conversation.</p>"""
    system_message_id: NotRequired["capo_qbusiness.types.message_id.MessageId"]
    """<p>The identifier of an Amazon Q Business AI generated message within the conversation.</p>"""
    source_attributions: NotRequired[
        "capo_qbusiness.types.source_attributions.SourceAttributions"
    ]
    """<p>The source documents used to generate the conversation response.</p>"""
    final_text_message: NotRequired["capo_qbusiness.types.string.String"]
    """<p>The final text output message generated by the system.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: MetadataEvent) -> dict:
    out: dict = {}
    if "conversation_id" in value:
        out["conversationId"] = value["conversation_id"]
    if "user_message_id" in value:
        out["userMessageId"] = value["user_message_id"]
    if "system_message_id" in value:
        out["systemMessageId"] = value["system_message_id"]
    if "source_attributions" in value:
        import capo_qbusiness.types.source_attributions

        out["sourceAttributions"] = (
            capo_qbusiness.types.source_attributions.serialize_json(
                value["source_attributions"]
            )
        )
    if "final_text_message" in value:
        out["finalTextMessage"] = value["final_text_message"]
    return out


def deserialize_json(data: dict) -> MetadataEvent:
    out: MetadataEvent = {}  # type: ignore[typeddict-item]
    if "conversationId" in data:
        out["conversation_id"] = data["conversationId"]
    if "userMessageId" in data:
        out["user_message_id"] = data["userMessageId"]
    if "systemMessageId" in data:
        out["system_message_id"] = data["systemMessageId"]
    if "sourceAttributions" in data:
        import capo_qbusiness.types.source_attributions

        out["source_attributions"] = (
            capo_qbusiness.types.source_attributions.deserialize_json(
                data["sourceAttributions"]
            )
        )
    if "finalTextMessage" in data:
        out["final_text_message"] = data["finalTextMessage"]
    return out


def serialize_event_json(value: MetadataEvent) -> bytes:
    headers: dict[str, HeaderValue] = {":event-type": "metadataEvent"}
    payload = b""
    return Message(headers=headers, payload=payload).encode()


def deserialize_event_json(message: Message) -> MetadataEvent:
    headers = message.headers  # noqa: F841
    payload = message.payload  # noqa: F841
    out: MetadataEvent = {}  # type: ignore[typeddict-item]
    return out
